#!/usr/bin/env python3
"""Generate the checked-in C kernel; runtime C++ needs no CasADi installation."""

import argparse
import os
from pathlib import Path

import casadi as ca

from model_contract import MODEL_VERSION, RK4_SUBSTEPS, MAX_RK4_STEP_SEC, require_codegen_version
from slosh_kernel import functions as liquid_functions
from actual_motion_kernel import functions as motion_functions


def generated_functions():
    return liquid_functions() + motion_functions()


def generate(output):
    require_codegen_version(ca.__version__)
    output = output.resolve()
    output.mkdir(parents=True, exist_ok=True)
    previous = Path.cwd()
    try:
        os.chdir(output)
        generator = ca.CodeGenerator("slosh_kernel_generated.c", {"with_header": True})
        for function in generated_functions():
            generator.add(function)
        generator.generate()
        # CasADi emits trailing blanks; normalize in the generator so the
        # checked-in C remains both reproducible and whitespace-clean.
        for name in ("slosh_kernel_generated.c", "slosh_kernel_generated.h"):
            path = Path(name)
            path.write_text("\n".join(line.rstrip() for line in path.read_text().splitlines()) + "\n")
        Path("slosh_kernel_contract.h").write_text(
            "/* Generated by generate_slosh_kernel.py; do not edit. */\n"
            "#pragma once\n"
            f"#define SPMPC_LIQUID_KERNEL_VERSION {MODEL_VERSION}\n"
            f"#define SPMPC_LIQUID_RK4_SUBSTEPS {RK4_SUBSTEPS}\n"
            f"#define SPMPC_LIQUID_MAX_RK4_STEP_SEC {MAX_RK4_STEP_SEC!r}\n")
    finally:
        os.chdir(previous)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path,
                        default=Path(__file__).resolve().parents[2] / "src/dynamics/generated")
    generate(parser.parse_args().output_dir)
