#!/usr/bin/env python3
"""Interactively annotate ROI and reference geometry for liquid measurement."""

import argparse
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

import cv2


WINDOW_NAME = "Liquid ROI Annotation"


@dataclass
class Point:
    x: int
    y: int


def parse_args():
    parser = argparse.ArgumentParser(
        description="Interactively annotate ROI, tube inner walls, still level, and optional ruler points."
    )
    parser.add_argument("--image", required=True, help="Path to the exported PNG/JPG image.")
    parser.add_argument(
        "--mode",
        choices=["px_only", "ruler"],
        default="px_only",
        help="Calibration mode: px_only for pixel-domain calibration, ruler when a background ruler is available.",
    )
    parser.add_argument(
        "--output-yaml",
        default="",
        help="Output YAML path. Defaults to <image_stem>_calibration.yaml next to the image.",
    )
    parser.add_argument(
        "--output-image",
        default="",
        help="Annotated preview image path. Defaults to <image_stem>_annotated.png next to the image.",
    )
    parser.add_argument(
        "--calibration-distance-mm",
        type=float,
        default=None,
        help="Physical distance in mm between the two ruler points. Required only in ruler mode.",
    )
    return parser.parse_args()


def default_output_yaml(image_path: Path) -> Path:
    return image_path.parent / f"{image_path.stem}_calibration.yaml"


def default_output_image(image_path: Path) -> Path:
    return image_path.parent / f"{image_path.stem}_annotated.png"


def point_in_roi(point: Point, roi):
    x, y, w, h = roi
    return x <= point.x <= x + w and y <= point.y <= y + h


def write_yaml(path: Path, image_path: Path, mode: str, roi, left_wall: Point, right_wall: Point,
               still_level: Point, calib_a, calib_b, mm_per_pixel, calibration_distance_mm):
    x, y, w, h = roi
    rel_left = left_wall.x - x
    rel_right = right_wall.x - x
    rel_level = still_level.y - y

    calib_a_str = "null" if calib_a is None else f"[{calib_a.x}, {calib_a.y}]"
    calib_b_str = "null" if calib_b is None else f"[{calib_b.x}, {calib_b.y}]"
    mm_per_pixel_str = "null" if mm_per_pixel is None else f"{mm_per_pixel:.8f}"
    ruler_distance_str = "null" if calibration_distance_mm is None else f"{calibration_distance_mm:.6f}"

    lines = [
        f"# Auto-generated by annotate_liquid_roi.py on {datetime.now().isoformat(timespec='seconds')}",
        "source:",
        f"  image: {image_path}",
        f"  mode: {mode}",
        "roi:",
        f"  x: {x}",
        f"  y: {y}",
        f"  w: {w}",
        f"  h: {h}",
        "tube_inner:",
        f"  x_left: {rel_left}",
        f"  x_right: {rel_right}",
        "calibration:",
        f"  still_level_px: {rel_level}",
        f"  mm_per_pixel: {mm_per_pixel_str}",
        "reference_points_image:",
        f"  left_wall: [{left_wall.x}, {left_wall.y}]",
        f"  right_wall: [{right_wall.x}, {right_wall.y}]",
        f"  still_level: [{still_level.x}, {still_level.y}]",
        f"  ruler_point_a: {calib_a_str}",
        f"  ruler_point_b: {calib_b_str}",
        f"  ruler_distance_mm: {ruler_distance_str}",
        "",
    ]
    path.write_text("\n".join(lines))


def main():
    args = parse_args()
    if args.mode == "ruler" and args.calibration_distance_mm is None:
        print("[ERROR] --calibration-distance-mm is required in ruler mode.", file=sys.stderr)
        return 1

    image_path = Path(args.image).expanduser().resolve()
    if not image_path.exists():
        print(f"[ERROR] image not found: {image_path}", file=sys.stderr)
        return 2

    image = cv2.imread(str(image_path))
    if image is None:
        print(f"[ERROR] failed to read image: {image_path}", file=sys.stderr)
        return 3

    roi = cv2.selectROI("Select ROI", image, showCrosshair=True, fromCenter=False)
    cv2.destroyWindow("Select ROI")
    if roi[2] <= 0 or roi[3] <= 0:
        print("[ERROR] ROI not selected.", file=sys.stderr)
        return 4

    state = {
        "left_wall": None,
        "right_wall": None,
        "still_level": None,
        "calib_a": None,
        "calib_b": None,
    }

    order = ["left_wall", "right_wall", "still_level"]
    if args.mode == "ruler":
        order.extend(["calib_a", "calib_b"])

    labels = {
        "left_wall": "Step 1: click LEFT inner wall inside ROI",
        "right_wall": "Step 2: click RIGHT inner wall inside ROI",
        "still_level": "Step 3: click the UPPER visible still-liquid edge inside ROI",
        "calib_a": "Step 4: click BACKGROUND ruler point A",
        "calib_b": "Step 5: click BACKGROUND ruler point B",
    }

    def current_key():
        for key in order:
            if state[key] is None:
                return key
        return None

    def draw_overlay():
        canvas = image.copy()
        x, y, w, h = roi
        cv2.rectangle(canvas, (x, y), (x + w, y + h), (0, 255, 255), 2)

        cv2.putText(canvas, f"Mode: {args.mode}", (20, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 255), 2)

        if state["left_wall"] is not None:
            cv2.line(canvas, (state["left_wall"].x, y), (state["left_wall"].x, y + h), (255, 0, 0), 2)
        if state["right_wall"] is not None:
            cv2.line(canvas, (state["right_wall"].x, y), (state["right_wall"].x, y + h), (0, 128, 255), 2)
        if state["still_level"] is not None:
            cv2.line(canvas, (x, state["still_level"].y), (x + w, state["still_level"].y), (0, 255, 0), 2)
        if state["calib_a"] is not None:
            cv2.circle(canvas, (state["calib_a"].x, state["calib_a"].y), 5, (255, 0, 255), -1)
        if state["calib_b"] is not None:
            cv2.circle(canvas, (state["calib_b"].x, state["calib_b"].y), 5, (255, 0, 255), -1)
        if state["calib_a"] is not None and state["calib_b"] is not None:
            cv2.line(
                canvas,
                (state["calib_a"].x, state["calib_a"].y),
                (state["calib_b"].x, state["calib_b"].y),
                (255, 0, 255),
                2,
            )

        step = current_key()
        text = labels[step] if step is not None else "Done: press Enter to save, r to reset, q/Esc to quit"
        cv2.putText(canvas, text, (20, 65), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)
        cv2.putText(
            canvas,
            "Inside ROI: left/right wall/still level. Still level: choose the upper visible meniscus edge.",
            (20, 95),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.48,
            (255, 255, 255),
            1,
        )
        ruler_hint = (
            "Ruler mode: click background ruler only, not the tube surface."
            if args.mode == "ruler"
            else "PX-only mode: no ruler clicks required; mm_per_pixel will be left null."
        )
        cv2.putText(
            canvas,
            ruler_hint,
            (20, 120),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.48,
            (255, 255, 255),
            1,
        )
        return canvas

    def on_mouse(event, x, y, _flags, _userdata):
        if event != cv2.EVENT_LBUTTONDOWN:
            return

        key = current_key()
        if key is None:
            return

        point = Point(x, y)
        if key in ("left_wall", "right_wall", "still_level") and not point_in_roi(point, roi):
            print(f"[WARN] {key} must be clicked inside ROI.", file=sys.stderr)
            return

        state[key] = point

    cv2.namedWindow(WINDOW_NAME, cv2.WINDOW_NORMAL)
    cv2.setMouseCallback(WINDOW_NAME, on_mouse)

    while True:
        canvas = draw_overlay()
        cv2.imshow(WINDOW_NAME, canvas)
        key = cv2.waitKey(30) & 0xFF

        if key in (27, ord("q")):
            cv2.destroyAllWindows()
            print("[INFO] annotation cancelled.")
            return 5
        if key == ord("r"):
            for name in order:
                state[name] = None
            continue
        if key in (10, 13):
            if current_key() is not None:
                print("[WARN] annotation not complete yet.", file=sys.stderr)
                continue
            break

    cv2.destroyAllWindows()

    left_wall = state["left_wall"]
    right_wall = state["right_wall"]
    still_level = state["still_level"]
    calib_a = state["calib_a"]
    calib_b = state["calib_b"]

    if left_wall.x > right_wall.x:
        left_wall, right_wall = right_wall, left_wall

    if args.mode == "ruler":
        pixel_span = abs(calib_b.y - calib_a.y)
        if pixel_span < 1:
            print("[ERROR] ruler points must have non-zero vertical distance.", file=sys.stderr)
            return 6
        mm_per_pixel = args.calibration_distance_mm / float(pixel_span)
    else:
        mm_per_pixel = None
        calib_a = None
        calib_b = None

    output_yaml = Path(args.output_yaml).expanduser().resolve() if args.output_yaml else default_output_yaml(image_path)
    output_image = Path(args.output_image).expanduser().resolve() if args.output_image else default_output_image(image_path)

    write_yaml(
        output_yaml,
        image_path,
        args.mode,
        roi,
        left_wall,
        right_wall,
        still_level,
        calib_a,
        calib_b,
        mm_per_pixel,
        args.calibration_distance_mm if args.mode == "ruler" else None,
    )

    annotated = draw_overlay()
    if not cv2.imwrite(str(output_image), annotated):
        print(f"[ERROR] failed to save annotated image: {output_image}", file=sys.stderr)
        return 7

    print(f"[OK] saved calibration yaml: {output_yaml}")
    print(f"[OK] saved annotated image: {output_image}")
    print(f"[OK] tube_inner.x_left = {left_wall.x - roi[0]}")
    print(f"[OK] tube_inner.x_right = {right_wall.x - roi[0]}")
    print(f"[OK] calibration.still_level_px = {still_level.y - roi[1]}")
    if mm_per_pixel is None:
        print("[OK] calibration.mm_per_pixel = null (px_only mode)")
    else:
        print(f"[OK] calibration.mm_per_pixel = {mm_per_pixel:.8f}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
