#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import bisect
import csv
import math
import os
import statistics
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import rosbag


def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Compare offline RealSense liquid-height output against MPC slosh estimates "
            "from the original rosbag on the same time axis."
        )
    )
    parser.add_argument("--bag", required=True, help="Original rosbag containing /slosh/* topics.")
    parser.add_argument("--liquid-csv", required=True, help="liquid_height.csv generated by extract_liquid_height_from_bag.py")
    parser.add_argument("--out-png", required=True, help="Output comparison figure path.")
    parser.add_argument(
        "--out-csv",
        default="",
        help="Optional output CSV path for aligned samples and summary metrics.",
    )
    parser.add_argument(
        "--fit-scale-to-height",
        action="store_true",
        help="Optional exploratory scale fit to /slosh/height. Disabled by default.",
    )
    parser.add_argument(
        "--initial-align-window-sec",
        type=float,
        default=1.0,
        help="Initial time window used to align each series to zero. Default: 1.0 s.",
    )
    parser.add_argument(
        "--initial-align-max-samples",
        type=int,
        default=30,
        help="Maximum number of early samples used for zero alignment per series. Default: 30.",
    )
    parser.add_argument(
        "--no-initial-zero-align",
        action="store_true",
        help="Disable per-series initial zero alignment.",
    )
    return parser.parse_args()


def ensure_parent(path_str):
    Path(path_str).parent.mkdir(parents=True, exist_ok=True)


def load_liquid_csv(path):
    valid_t = []
    valid_mm = []
    report_t = []
    report_mm = []
    rows = []
    with open(path, newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        fieldnames = reader.fieldnames or []
        if "height_peak_rel_mm" not in fieldnames:
            raise RuntimeError("liquid csv is missing height_peak_rel_mm")
        for row in reader:
            rows.append(row)
            stamp = float(row["stamp"])
            mm_raw = row["height_peak_rel_mm"].strip()
            if row["valid"] == "1" and mm_raw:
                valid_t.append(stamp)
                valid_mm.append(float(mm_raw))
            if row["accept_for_peak_report"] == "1" and mm_raw:
                report_t.append(stamp)
                report_mm.append(float(mm_raw))
    if not rows:
        raise RuntimeError("liquid csv has no rows")
    return rows, valid_t, valid_mm, report_t, report_mm


def load_mpc_series(bag_path):
    start = None
    slosh_t = []
    slosh_mm = []
    pred_t = []
    pred_mm = []
    with rosbag.Bag(bag_path) as bag:
        start = bag.get_start_time()
        for topic, msg, t in bag.read_messages(topics=["/slosh/height", "/slosh/height_pred_max"]):
            ts = t.to_sec()
            if topic == "/slosh/height":
                slosh_t.append(ts)
                slosh_mm.append(float(msg.data) * 1000.0)
            else:
                pred_t.append(ts)
                pred_mm.append(float(msg.data) * 1000.0)
    if start is None:
        raise RuntimeError(f"failed to read bag start time: {bag_path}")
    return start, slosh_t, slosh_mm, pred_t, pred_mm


def interpolate_series(sample_times, series_times, series_values):
    if not series_times:
        return [math.nan] * len(sample_times)
    if len(series_times) == 1:
        return [series_values[0]] * len(sample_times)
    out = []
    for ts in sample_times:
        idx = bisect.bisect_left(series_times, ts)
        if idx <= 0:
            out.append(series_values[0])
            continue
        if idx >= len(series_times):
            out.append(series_values[-1])
            continue
        t0 = series_times[idx - 1]
        t1 = series_times[idx]
        v0 = series_values[idx - 1]
        v1 = series_values[idx]
        if t1 <= t0:
            out.append(v1)
            continue
        ratio = (ts - t0) / (t1 - t0)
        out.append(v0 + ratio * (v1 - v0))
    return out


def safe_stats(values):
    clean = [v for v in values if not math.isnan(v)]
    if not clean:
        return {"median": math.nan, "p90": math.nan, "max": math.nan}
    clean_sorted = sorted(clean)
    idx90 = int(round((len(clean_sorted) - 1) * 0.9))
    return {
        "median": statistics.median(clean),
        "p90": clean_sorted[idx90],
        "max": max(clean),
    }


def mae(a, b):
    pairs = [(x, y) for x, y in zip(a, b) if not math.isnan(x) and not math.isnan(y)]
    if not pairs:
        return math.nan
    return sum(abs(x - y) for x, y in pairs) / len(pairs)


def rmse(a, b):
    pairs = [(x, y) for x, y in zip(a, b) if not math.isnan(x) and not math.isnan(y)]
    if not pairs:
        return math.nan
    return math.sqrt(sum((x - y) ** 2 for x, y in pairs) / len(pairs))


def corr(a, b):
    pairs = [(x, y) for x, y in zip(a, b) if not math.isnan(x) and not math.isnan(y)]
    if len(pairs) < 2:
        return math.nan
    xs = [x for x, _ in pairs]
    ys = [y for _, y in pairs]
    mean_x = statistics.mean(xs)
    mean_y = statistics.mean(ys)
    num = sum((x - mean_x) * (y - mean_y) for x, y in pairs)
    den_x = math.sqrt(sum((x - mean_x) ** 2 for x in xs))
    den_y = math.sqrt(sum((y - mean_y) ** 2 for y in ys))
    if den_x <= 0.0 or den_y <= 0.0:
        return math.nan
    return num / (den_x * den_y)


def fit_scale(source, target):
    pairs = [(s, t) for s, t in zip(source, target) if not math.isnan(s) and not math.isnan(t)]
    if not pairs:
        return math.nan
    denom = sum(s * s for s, _ in pairs)
    if denom <= 1e-12:
        return math.nan
    numer = sum(s * t for s, t in pairs)
    return numer / denom


def initial_offset(rel_times, values, window_sec, max_samples):
    pairs = [(t, v) for t, v in zip(rel_times, values) if not math.isnan(v)]
    if not pairs:
        return 0.0
    window_sec = max(0.0, float(window_sec))
    max_samples = max(1, int(max_samples))
    selected = [v for t, v in pairs if t <= window_sec]
    if len(selected) < 3:
        selected = [v for _, v in pairs[:max_samples]]
    else:
        selected = selected[:max_samples]
    if not selected:
        return 0.0
    return statistics.median(selected)


def subtract_offset(values, offset):
    return [math.nan if math.isnan(v) else (v - offset) for v in values]


def format_stat(value):
    if math.isnan(value):
        return "nan"
    return f"{value:.3f}"


def plot_comparison(
    out_png,
    rel_valid_t,
    valid_mm,
    rel_report_t,
    report_mm,
    rel_slosh_t,
    slosh_mm,
    rel_pred_t,
    pred_mm,
    interp_slosh_mm,
    interp_pred_mm,
    fitted_scale,
    fitted_report_mm,
    show_fitted_scale,
    zero_align_enabled,
    visual_offset_mm,
    height_offset_mm,
    pred_offset_mm,
):
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(13, 8), sharex=True)

    valid_label = "RealSense valid peak_rel_mm"
    report_label = "RealSense reported peak_rel_mm"
    slosh_label = "MPC /slosh/height (mm)"
    pred_label = "MPC /slosh/height_pred_max (mm)"
    if zero_align_enabled:
        valid_label += " [zero-aligned]"
        report_label += " [zero-aligned]"
        slosh_label += " [zero-aligned]"
        pred_label += " [zero-aligned]"

    ax1.plot(rel_valid_t, valid_mm, color="#c0c0c0", linewidth=1.1, label=valid_label)
    ax1.scatter(rel_report_t, report_mm, s=12, color="#1f77b4", label=report_label, zorder=3)
    if show_fitted_scale:
        ax1.plot(
            rel_report_t,
            fitted_report_mm,
            color="#2ca02c",
            linewidth=1.2,
            label=f"RealSense scaled to /slosh/height (k={format_stat(fitted_scale)})",
        )
    ax1.plot(rel_slosh_t, slosh_mm, color="#ff7f0e", linewidth=1.2, label=slosh_label)
    ax1.plot(rel_pred_t, pred_mm, color="#d62728", linewidth=1.2, linestyle="--", label=pred_label)
    ax1.axhline(0.0, color="#808080", linewidth=0.9, linestyle=":")
    ax1.set_ylabel("Relative height (mm)")
    ax1.set_title("RealSense vs MPC slosh estimate")
    ax1.legend(loc="upper right")
    ax1.grid(True, alpha=0.25)

    err_height = [v - m for v, m in zip(report_mm, interp_slosh_mm)]
    err_pred = [v - m for v, m in zip(report_mm, interp_pred_mm)]

    ax2.plot(rel_report_t, err_height, color="#1f77b4", linewidth=1.1, label="Raw error vs /slosh/height")
    if show_fitted_scale:
        err_height_scaled = [v - m for v, m in zip(fitted_report_mm, interp_slosh_mm)]
        ax2.plot(rel_report_t, err_height_scaled, color="#2ca02c", linewidth=1.1, label="Scaled error vs /slosh/height")
    else:
        err_height_scaled = [math.nan] * len(err_height)
    ax2.plot(rel_report_t, err_pred, color="#d62728", linewidth=1.1, linestyle="--", label="Raw error vs /slosh/height_pred_max")
    ax2.axhline(0.0, color="#808080", linewidth=0.9, linestyle=":")
    ax2.set_xlabel("Relative time (s)")
    ax2.set_ylabel("Error (mm)")
    ax2.grid(True, alpha=0.25)
    ax2.legend(loc="upper right")

    text = "\n".join(
        ([f"reportable frames: {len(report_mm)}"]
         + (
             [
                 "initial zero alignment: "
                 f"visual={format_stat(visual_offset_mm)}mm "
                 f"height={format_stat(height_offset_mm)}mm "
                 f"pred={format_stat(pred_offset_mm)}mm"
             ]
             if zero_align_enabled
             else ["initial zero alignment: disabled"]
         )
         + [
             f"vs height  MAE={format_stat(mae(report_mm, interp_slosh_mm))}  RMSE={format_stat(rmse(report_mm, interp_slosh_mm))}  Corr={format_stat(corr(report_mm, interp_slosh_mm))}",
             f"vs predMax MAE={format_stat(mae(report_mm, interp_pred_mm))}  RMSE={format_stat(rmse(report_mm, interp_pred_mm))}  Corr={format_stat(corr(report_mm, interp_pred_mm))}",
         ]
         + (
             [
                 f"scale fit k (optional)={format_stat(fitted_scale)}",
                 f"scaled     MAE={format_stat(mae(fitted_report_mm, interp_slosh_mm))}  RMSE={format_stat(rmse(fitted_report_mm, interp_slosh_mm))}  Corr={format_stat(corr(fitted_report_mm, interp_slosh_mm))}",
             ]
             if show_fitted_scale
             else []
         ))
    )
    ax1.text(
        0.01,
        0.99,
        text,
        transform=ax1.transAxes,
        va="top",
        ha="left",
        fontsize=9,
        bbox=dict(boxstyle="round", facecolor="white", alpha=0.85, edgecolor="#cccccc"),
    )

    fig.tight_layout()
    fig.savefig(out_png, dpi=160)
    plt.close(fig)

    return err_height, err_height_scaled, err_pred


def maybe_write_aligned_csv(
    path,
    rel_report_t,
    report_mm,
    fitted_report_mm,
    interp_slosh_mm,
    interp_pred_mm,
    fitted_scale,
    show_fitted_scale,
):
    if not path:
        return
    ensure_parent(path)
    with open(path, "w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        header = [
            "relative_time_s",
            "realsense_reported_peak_rel_mm_zero_aligned",
            "mpc_slosh_height_mm_zero_aligned",
            "mpc_slosh_height_pred_max_mm_zero_aligned",
            "error_vs_height_mm_zero_aligned",
            "error_vs_pred_max_mm_zero_aligned",
        ]
        if show_fitted_scale:
            header.extend(
                [
                    "realsense_scaled_peak_rel_mm_zero_aligned",
                    "scaled_error_vs_height_mm_zero_aligned",
                    "fitted_scale_to_height",
                ]
            )
        writer.writerow(header)
        for t, v, vs, h, p in zip(rel_report_t, report_mm, fitted_report_mm, interp_slosh_mm, interp_pred_mm):
            row = [
                f"{t:.6f}",
                f"{v:.6f}",
                f"{h:.6f}",
                f"{p:.6f}",
                f"{(v-h):.6f}",
                f"{(v-p):.6f}",
            ]
            if show_fitted_scale:
                row.extend(
                    [
                        f"{vs:.6f}",
                        f"{(vs-h):.6f}",
                        f"{fitted_scale:.6f}" if not math.isnan(fitted_scale) else "nan",
                    ]
                )
            writer.writerow(row)


def main():
    args = parse_args()

    rows, valid_t, valid_mm, report_t, report_mm = load_liquid_csv(args.liquid_csv)
    if not report_t:
        raise RuntimeError("no reportable visual frames in liquid csv")

    bag_start, slosh_t, slosh_mm, pred_t, pred_mm = load_mpc_series(args.bag)
    if not slosh_t or not pred_t:
        raise RuntimeError("bag is missing /slosh/height or /slosh/height_pred_max")

    rel_valid_t = [t - bag_start for t in valid_t]
    rel_report_t = [t - bag_start for t in report_t]
    rel_slosh_t = [t - bag_start for t in slosh_t]
    rel_pred_t = [t - bag_start for t in pred_t]

    zero_align_enabled = not args.no_initial_zero_align
    visual_offset_mm = 0.0
    height_offset_mm = 0.0
    pred_offset_mm = 0.0
    if zero_align_enabled:
        visual_offset_mm = initial_offset(rel_report_t, report_mm, args.initial_align_window_sec, args.initial_align_max_samples)
        height_offset_mm = initial_offset(rel_slosh_t, slosh_mm, args.initial_align_window_sec, args.initial_align_max_samples)
        pred_offset_mm = initial_offset(rel_pred_t, pred_mm, args.initial_align_window_sec, args.initial_align_max_samples)
        valid_mm = subtract_offset(valid_mm, visual_offset_mm)
        report_mm = subtract_offset(report_mm, visual_offset_mm)
        slosh_mm = subtract_offset(slosh_mm, height_offset_mm)
        pred_mm = subtract_offset(pred_mm, pred_offset_mm)

    interp_slosh_mm = interpolate_series(report_t, slosh_t, slosh_mm)
    interp_pred_mm = interpolate_series(report_t, pred_t, pred_mm)
    fitted_scale = fit_scale(report_mm, interp_slosh_mm) if args.fit_scale_to_height else math.nan
    fitted_report_mm = [v * fitted_scale if not math.isnan(fitted_scale) else math.nan for v in report_mm]

    ensure_parent(args.out_png)
    err_height, err_height_scaled, err_pred = plot_comparison(
        args.out_png,
        rel_valid_t,
        valid_mm,
        rel_report_t,
        report_mm,
        rel_slosh_t,
        slosh_mm,
        rel_pred_t,
        pred_mm,
        interp_slosh_mm,
        interp_pred_mm,
        fitted_scale,
        fitted_report_mm,
        args.fit_scale_to_height,
        zero_align_enabled,
        visual_offset_mm,
        height_offset_mm,
        pred_offset_mm,
    )

    maybe_write_aligned_csv(
        args.out_csv,
        rel_report_t,
        report_mm,
        fitted_report_mm,
        interp_slosh_mm,
        interp_pred_mm,
        fitted_scale,
        args.fit_scale_to_height,
    )

    stats_visual = safe_stats(report_mm)
    stats_height = safe_stats(interp_slosh_mm)
    stats_pred = safe_stats(interp_pred_mm)

    print(f"[OK] comparison plot: {args.out_png}")
    if args.out_csv:
        print(f"[OK] aligned csv: {args.out_csv}")
    print(f"[INFO] reportable frames: {len(report_mm)}")
    print(
        "[INFO] RealSense reported mm: "
        f"median={format_stat(stats_visual['median'])} "
        f"p90={format_stat(stats_visual['p90'])} "
        f"max={format_stat(stats_visual['max'])}"
    )
    if zero_align_enabled:
        print(
            "[INFO] Initial zero offsets (mm): "
            f"visual={format_stat(visual_offset_mm)} "
            f"height={format_stat(height_offset_mm)} "
            f"pred={format_stat(pred_offset_mm)}"
        )
    print(
        "[INFO] MPC /slosh/height mm (interpolated): "
        f"median={format_stat(stats_height['median'])} "
        f"p90={format_stat(stats_height['p90'])} "
        f"max={format_stat(stats_height['max'])}"
    )
    print(
        "[INFO] MPC /slosh/height_pred_max mm (interpolated): "
        f"median={format_stat(stats_pred['median'])} "
        f"p90={format_stat(stats_pred['p90'])} "
        f"max={format_stat(stats_pred['max'])}"
    )
    print(
        "[INFO] Error vs /slosh/height: "
        f"MAE={format_stat(mae(report_mm, interp_slosh_mm))} "
        f"RMSE={format_stat(rmse(report_mm, interp_slosh_mm))} "
        f"Corr={format_stat(corr(report_mm, interp_slosh_mm))}"
    )
    if args.fit_scale_to_height:
        stats_visual_scaled = safe_stats(fitted_report_mm)
        print(
            "[INFO] Fitted-scale RealSense mm: "
            f"median={format_stat(stats_visual_scaled['median'])} "
            f"p90={format_stat(stats_visual_scaled['p90'])} "
            f"max={format_stat(stats_visual_scaled['max'])}"
        )
        print(
            "[INFO] Scaled error vs /slosh/height: "
            f"k={format_stat(fitted_scale)} "
            f"MAE={format_stat(mae(fitted_report_mm, interp_slosh_mm))} "
            f"RMSE={format_stat(rmse(fitted_report_mm, interp_slosh_mm))} "
            f"Corr={format_stat(corr(fitted_report_mm, interp_slosh_mm))}"
        )
    print(
        "[INFO] Error vs /slosh/height_pred_max: "
        f"MAE={format_stat(mae(report_mm, interp_pred_mm))} "
        f"RMSE={format_stat(rmse(report_mm, interp_pred_mm))} "
        f"Corr={format_stat(corr(report_mm, interp_pred_mm))}"
    )


if __name__ == "__main__":
    main()
