#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import bisect
import csv
import math
import statistics
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import rosbag


def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Compare v2 RealSense liquid-height outputs against MPC slosh estimates "
            "on the same time axis, with center as the current main liquid level "
            "and peak as a secondary diagnostic measure."
        )
    )
    parser.add_argument("--bag", required=True, help="Original rosbag containing /slosh/* topics.")
    parser.add_argument("--liquid-csv", required=True, help="liquid_height_v2.csv generated by extract_liquid_height_v2_from_bag.py")
    parser.add_argument("--out-png", required=True, help="Output comparison figure path.")
    parser.add_argument(
        "--out-csv",
        default="",
        help="Optional output CSV path for aligned samples and summary metrics.",
    )
    parser.add_argument(
        "--initial-align-window-sec",
        type=float,
        default=1.0,
        help="Initial time window used to align each series to zero. Default: 1.0 s.",
    )
    parser.add_argument(
        "--initial-align-max-samples",
        type=int,
        default=30,
        help="Maximum number of early samples used for zero alignment per series. Default: 30.",
    )
    parser.add_argument(
        "--no-initial-zero-align",
        action="store_true",
        help="Disable per-series initial zero alignment.",
    )
    parser.add_argument(
        "--center-bias-correction-mm",
        type=float,
        default=0.0,
        help="Optional constant bias correction applied to height_center_rel_mm_v2 when the corrected column is absent.",
    )
    return parser.parse_args()


def ensure_parent(path_str):
    Path(path_str).parent.mkdir(parents=True, exist_ok=True)


def parse_optional_mm(raw_value):
    text = raw_value.strip()
    if not text:
        return math.nan
    return float(text)


def load_liquid_csv(path, center_bias_correction_mm=0.0):
    valid_t = []
    valid_peak_mm = []
    valid_center_mm = []
    report_t = []
    report_peak_mm = []
    report_center_mm = []
    rows = []
    with open(path, newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        fieldnames = reader.fieldnames or []
        required_fields = [
            "stamp",
            "valid_v2",
            "accept_for_peak_report_v2",
            "height_peak_rel_mm_v2",
            "height_center_rel_mm_v2",
        ]
        for field in required_fields:
            if field not in fieldnames:
                raise RuntimeError(f"liquid csv is missing {field}")
        has_corrected_center = "height_center_rel_mm_bias_corrected_v2" in fieldnames
        center_series_label = (
            "center_rel_mm_bias_corrected_v2"
            if has_corrected_center or float(center_bias_correction_mm) > 0.0
            else "center_rel_mm_v2"
        )
        for row in reader:
            rows.append(row)
            stamp = float(row["stamp"])
            peak_mm = parse_optional_mm(row["height_peak_rel_mm_v2"])
            raw_center_mm = parse_optional_mm(row["height_center_rel_mm_v2"])
            if has_corrected_center:
                center_mm = parse_optional_mm(row["height_center_rel_mm_bias_corrected_v2"])
            elif not math.isnan(raw_center_mm) and float(center_bias_correction_mm) > 0.0:
                center_mm = max(0.0, raw_center_mm - float(center_bias_correction_mm))
            else:
                center_mm = raw_center_mm
            if row["valid_v2"] == "1":
                valid_t.append(stamp)
                valid_peak_mm.append(peak_mm)
                valid_center_mm.append(center_mm)
            if row["accept_for_peak_report_v2"] == "1":
                report_t.append(stamp)
                report_peak_mm.append(peak_mm)
                report_center_mm.append(center_mm)
    if not rows:
        raise RuntimeError("liquid csv has no rows")
    return rows, valid_t, valid_peak_mm, valid_center_mm, report_t, report_peak_mm, report_center_mm, center_series_label


def load_mpc_series(bag_path):
    start = None
    slosh_t = []
    slosh_mm = []
    pred_t = []
    pred_mm = []
    with rosbag.Bag(bag_path) as bag:
        start = bag.get_start_time()
        for topic, msg, t in bag.read_messages(topics=["/slosh/height", "/slosh/height_pred_max"]):
            ts = t.to_sec()
            if topic == "/slosh/height":
                slosh_t.append(ts)
                slosh_mm.append(float(msg.data) * 1000.0)
            else:
                pred_t.append(ts)
                pred_mm.append(float(msg.data) * 1000.0)
    if start is None:
        raise RuntimeError(f"failed to read bag start time: {bag_path}")
    return start, slosh_t, slosh_mm, pred_t, pred_mm


def interpolate_series(sample_times, series_times, series_values):
    if not series_times:
        return [math.nan] * len(sample_times)
    if len(series_times) == 1:
        return [series_values[0]] * len(sample_times)
    out = []
    for ts in sample_times:
        idx = bisect.bisect_left(series_times, ts)
        if idx <= 0:
            out.append(series_values[0])
            continue
        if idx >= len(series_times):
            out.append(series_values[-1])
            continue
        t0 = series_times[idx - 1]
        t1 = series_times[idx]
        v0 = series_values[idx - 1]
        v1 = series_values[idx]
        if t1 <= t0:
            out.append(v1)
            continue
        ratio = (ts - t0) / (t1 - t0)
        out.append(v0 + ratio * (v1 - v0))
    return out


def clean_values(values):
    return [v for v in values if not math.isnan(v)]


def safe_stats(values):
    clean = clean_values(values)
    if not clean:
        return {"median": math.nan, "p90": math.nan, "max": math.nan}
    clean_sorted = sorted(clean)
    idx90 = int(round((len(clean_sorted) - 1) * 0.9))
    return {
        "median": statistics.median(clean),
        "p90": clean_sorted[idx90],
        "max": max(clean),
    }


def mae(a, b):
    pairs = [(x, y) for x, y in zip(a, b) if not math.isnan(x) and not math.isnan(y)]
    if not pairs:
        return math.nan
    return sum(abs(x - y) for x, y in pairs) / len(pairs)


def rmse(a, b):
    pairs = [(x, y) for x, y in zip(a, b) if not math.isnan(x) and not math.isnan(y)]
    if not pairs:
        return math.nan
    return math.sqrt(sum((x - y) ** 2 for x, y in pairs) / len(pairs))


def corr(a, b):
    pairs = [(x, y) for x, y in zip(a, b) if not math.isnan(x) and not math.isnan(y)]
    if len(pairs) < 2:
        return math.nan
    xs = [x for x, _ in pairs]
    ys = [y for _, y in pairs]
    mean_x = statistics.mean(xs)
    mean_y = statistics.mean(ys)
    num = sum((x - mean_x) * (y - mean_y) for x, y in pairs)
    den_x = math.sqrt(sum((x - mean_x) ** 2 for x in xs))
    den_y = math.sqrt(sum((y - mean_y) ** 2 for y in ys))
    if den_x <= 0.0 or den_y <= 0.0:
        return math.nan
    return num / (den_x * den_y)


def initial_offset(rel_times, values, window_sec, max_samples):
    pairs = [(t, v) for t, v in zip(rel_times, values) if not math.isnan(v)]
    if not pairs:
        return 0.0
    window_sec = max(0.0, float(window_sec))
    max_samples = max(1, int(max_samples))
    selected = [v for t, v in pairs if t <= window_sec]
    if len(selected) < 3:
        selected = [v for _, v in pairs[:max_samples]]
    else:
        selected = selected[:max_samples]
    if not selected:
        return 0.0
    return statistics.median(selected)


def subtract_offset(values, offset):
    return [math.nan if math.isnan(v) else (v - offset) for v in values]


def format_stat(value):
    if math.isnan(value):
        return "nan"
    return f"{value:.3f}"


def plot_comparison(
    out_png,
    rel_valid_t,
    valid_center_mm,
    valid_peak_mm,
    rel_report_t,
    report_center_mm,
    report_peak_mm,
    rel_slosh_t,
    slosh_mm,
    rel_pred_t,
    pred_mm,
    interp_slosh_mm,
    interp_pred_mm,
    zero_align_enabled,
    center_offset_mm,
    peak_offset_mm,
    height_offset_mm,
    pred_offset_mm,
    center_series_label,
):
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(13, 8), sharex=True)

    center_valid_label = f"RealSense valid {center_series_label} [main liquid level]"
    peak_valid_label = "RealSense valid peak_rel_mm_v2 [diagnostic]"
    center_report_label = f"RealSense reported {center_series_label} [main]"
    peak_report_label = "RealSense reported peak_rel_mm_v2 [diagnostic]"
    slosh_label = "MPC /slosh/height (mm)"
    pred_label = "MPC /slosh/height_pred_max (mm)"
    if zero_align_enabled:
        center_valid_label += " [zero-aligned]"
        peak_valid_label += " [zero-aligned]"
        center_report_label += " [zero-aligned]"
        peak_report_label += " [zero-aligned]"
        slosh_label += " [zero-aligned]"
        pred_label += " [zero-aligned]"

    ax1.plot(rel_valid_t, valid_center_mm, color="#9ecae1", linewidth=1.0, label=center_valid_label)
    ax1.plot(rel_valid_t, valid_peak_mm, color="#d4b9da", linewidth=1.0, label=peak_valid_label)
    ax1.scatter(rel_report_t, report_center_mm, s=14, color="#1f77b4", label=center_report_label, zorder=3)
    ax1.scatter(rel_report_t, report_peak_mm, s=14, color="#9467bd", label=peak_report_label, zorder=3)
    ax1.plot(rel_slosh_t, slosh_mm, color="#ff7f0e", linewidth=1.2, label=slosh_label)
    ax1.plot(rel_pred_t, pred_mm, color="#d62728", linewidth=1.2, linestyle="--", label=pred_label)
    ax1.axhline(0.0, color="#808080", linewidth=0.9, linestyle=":")
    ax1.set_ylabel("Relative height (mm)")
    ax1.set_title("RealSense v2 main-center level and diagnostic peak vs MPC")
    ax1.legend(loc="upper right")
    ax1.grid(True, alpha=0.25)

    err_center_height = [v - m for v, m in zip(report_center_mm, interp_slosh_mm)]
    err_peak_pred = [v - m for v, m in zip(report_peak_mm, interp_pred_mm)]
    err_center_pred = [v - m for v, m in zip(report_center_mm, interp_pred_mm)]
    err_peak_height = [v - m for v, m in zip(report_peak_mm, interp_slosh_mm)]

    ax2.plot(rel_report_t, err_center_height, color="#1f77b4", linewidth=1.1, label="center - /slosh/height")
    ax2.plot(rel_report_t, err_peak_pred, color="#9467bd", linewidth=1.1, label="peak - /slosh/height_pred_max")
    ax2.plot(rel_report_t, err_center_pred, color="#d62728", linewidth=1.0, linestyle="--", label="center - /slosh/height_pred_max")
    ax2.plot(rel_report_t, err_peak_height, color="#ff7f0e", linewidth=1.0, linestyle="--", label="peak - /slosh/height")
    ax2.axhline(0.0, color="#808080", linewidth=0.9, linestyle=":")
    ax2.set_xlabel("Relative time (s)")
    ax2.set_ylabel("Error (mm)")
    ax2.grid(True, alpha=0.25)
    ax2.legend(loc="upper right")

    text = "\n".join(
        ([f"reportable frames: {len(report_center_mm)}"]
         + (
             [
                 "initial zero alignment: "
                 f"center={format_stat(center_offset_mm)}mm "
                 f"peak={format_stat(peak_offset_mm)}mm "
                 f"height={format_stat(height_offset_mm)}mm "
                 f"pred={format_stat(pred_offset_mm)}mm"
             ]
             if zero_align_enabled
             else ["initial zero alignment: disabled"]
         )
         + [
             f"main {center_series_label} vs height   MAE={format_stat(mae(report_center_mm, interp_slosh_mm))}  RMSE={format_stat(rmse(report_center_mm, interp_slosh_mm))}  Corr={format_stat(corr(report_center_mm, interp_slosh_mm))}",
             f"diag peak  vs predMax  MAE={format_stat(mae(report_peak_mm, interp_pred_mm))}  RMSE={format_stat(rmse(report_peak_mm, interp_pred_mm))}  Corr={format_stat(corr(report_peak_mm, interp_pred_mm))}",
             f"diag: center vs predMax  MAE={format_stat(mae(report_center_mm, interp_pred_mm))}",
             f"diag: peak   vs height   MAE={format_stat(mae(report_peak_mm, interp_slosh_mm))}",
         ])
    )
    ax1.text(
        0.01,
        0.99,
        text,
        transform=ax1.transAxes,
        va="top",
        ha="left",
        fontsize=9,
        bbox=dict(boxstyle="round", facecolor="white", alpha=0.85, edgecolor="#cccccc"),
    )

    fig.tight_layout()
    fig.savefig(out_png, dpi=160)
    plt.close(fig)

    return err_center_height, err_peak_pred, err_center_pred, err_peak_height


def maybe_write_aligned_csv(
    path,
    rel_report_t,
    report_center_mm,
    report_peak_mm,
    interp_slosh_mm,
    interp_pred_mm,
):
    if not path:
        return
    ensure_parent(path)
    with open(path, "w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(
            [
                "relative_time_s",
                "realsense_center_main_rel_mm_v2_zero_aligned",
                "realsense_peak_rel_mm_v2_zero_aligned",
                "mpc_slosh_height_mm_zero_aligned",
                "mpc_slosh_height_pred_max_mm_zero_aligned",
                "error_center_vs_height_mm_zero_aligned",
                "error_peak_vs_pred_max_mm_zero_aligned",
                "error_center_vs_pred_max_mm_zero_aligned",
                "error_peak_vs_height_mm_zero_aligned",
            ]
        )
        for t, center_mm, peak_mm, height_mm, pred_mm in zip(
            rel_report_t, report_center_mm, report_peak_mm, interp_slosh_mm, interp_pred_mm
        ):
            writer.writerow(
                [
                    f"{t:.6f}",
                    f"{center_mm:.6f}" if not math.isnan(center_mm) else "nan",
                    f"{peak_mm:.6f}" if not math.isnan(peak_mm) else "nan",
                    f"{height_mm:.6f}" if not math.isnan(height_mm) else "nan",
                    f"{pred_mm:.6f}" if not math.isnan(pred_mm) else "nan",
                    f"{(center_mm - height_mm):.6f}" if not math.isnan(center_mm) and not math.isnan(height_mm) else "nan",
                    f"{(peak_mm - pred_mm):.6f}" if not math.isnan(peak_mm) and not math.isnan(pred_mm) else "nan",
                    f"{(center_mm - pred_mm):.6f}" if not math.isnan(center_mm) and not math.isnan(pred_mm) else "nan",
                    f"{(peak_mm - height_mm):.6f}" if not math.isnan(peak_mm) and not math.isnan(height_mm) else "nan",
                ]
            )


def main():
    args = parse_args()

    (
        _rows,
        valid_t,
        valid_peak_mm,
        valid_center_mm,
        report_t,
        report_peak_mm,
        report_center_mm,
        center_series_label,
    ) = load_liquid_csv(args.liquid_csv, args.center_bias_correction_mm)
    if not report_t:
        raise RuntimeError("no reportable visual frames in liquid csv")

    bag_start, slosh_t, slosh_mm, pred_t, pred_mm = load_mpc_series(args.bag)
    if not slosh_t or not pred_t:
        raise RuntimeError("bag is missing /slosh/height or /slosh/height_pred_max")

    rel_valid_t = [t - bag_start for t in valid_t]
    rel_report_t = [t - bag_start for t in report_t]
    rel_slosh_t = [t - bag_start for t in slosh_t]
    rel_pred_t = [t - bag_start for t in pred_t]

    zero_align_enabled = not args.no_initial_zero_align
    center_offset_mm = 0.0
    peak_offset_mm = 0.0
    height_offset_mm = 0.0
    pred_offset_mm = 0.0
    if zero_align_enabled:
        center_offset_mm = initial_offset(
            rel_report_t, report_center_mm, args.initial_align_window_sec, args.initial_align_max_samples
        )
        peak_offset_mm = initial_offset(
            rel_report_t, report_peak_mm, args.initial_align_window_sec, args.initial_align_max_samples
        )
        height_offset_mm = initial_offset(
            rel_slosh_t, slosh_mm, args.initial_align_window_sec, args.initial_align_max_samples
        )
        pred_offset_mm = initial_offset(
            rel_pred_t, pred_mm, args.initial_align_window_sec, args.initial_align_max_samples
        )
        valid_center_mm = subtract_offset(valid_center_mm, center_offset_mm)
        valid_peak_mm = subtract_offset(valid_peak_mm, peak_offset_mm)
        report_center_mm = subtract_offset(report_center_mm, center_offset_mm)
        report_peak_mm = subtract_offset(report_peak_mm, peak_offset_mm)
        slosh_mm = subtract_offset(slosh_mm, height_offset_mm)
        pred_mm = subtract_offset(pred_mm, pred_offset_mm)

    interp_slosh_mm = interpolate_series(report_t, slosh_t, slosh_mm)
    interp_pred_mm = interpolate_series(report_t, pred_t, pred_mm)

    ensure_parent(args.out_png)
    plot_comparison(
        args.out_png,
        rel_valid_t,
        valid_center_mm,
        valid_peak_mm,
        rel_report_t,
        report_center_mm,
        report_peak_mm,
        rel_slosh_t,
        slosh_mm,
        rel_pred_t,
        pred_mm,
        interp_slosh_mm,
        interp_pred_mm,
        zero_align_enabled,
        center_offset_mm,
        peak_offset_mm,
        height_offset_mm,
        pred_offset_mm,
        center_series_label,
    )

    maybe_write_aligned_csv(
        args.out_csv,
        rel_report_t,
        report_center_mm,
        report_peak_mm,
        interp_slosh_mm,
        interp_pred_mm,
    )

    stats_center = safe_stats(report_center_mm)
    stats_peak = safe_stats(report_peak_mm)
    stats_height = safe_stats(interp_slosh_mm)
    stats_pred = safe_stats(interp_pred_mm)

    print(f"[OK] comparison plot: {args.out_png}")
    if args.out_csv:
        print(f"[OK] aligned csv: {args.out_csv}")
    print(f"[INFO] reportable frames: {len(report_center_mm)}")
    print(
        "[INFO] RealSense center mm [main liquid level]: "
        f"median={format_stat(stats_center['median'])} "
        f"p90={format_stat(stats_center['p90'])} "
        f"max={format_stat(stats_center['max'])}"
    )
    print(
        "[INFO] RealSense peak mm [diagnostic]: "
        f"median={format_stat(stats_peak['median'])} "
        f"p90={format_stat(stats_peak['p90'])} "
        f"max={format_stat(stats_peak['max'])}"
    )
    if zero_align_enabled:
        print(
            "[INFO] Initial zero offsets (mm): "
            f"center={format_stat(center_offset_mm)} "
            f"peak={format_stat(peak_offset_mm)} "
            f"height={format_stat(height_offset_mm)} "
            f"pred={format_stat(pred_offset_mm)}"
        )
    if args.center_bias_correction_mm > 0.0:
        print(f"[INFO] center bias correction hint used for compare: {args.center_bias_correction_mm:.6f} mm")
    print(
        "[INFO] MPC /slosh/height mm (interpolated): "
        f"median={format_stat(stats_height['median'])} "
        f"p90={format_stat(stats_height['p90'])} "
        f"max={format_stat(stats_height['max'])}"
    )
    print(
        "[INFO] MPC /slosh/height_pred_max mm (interpolated): "
        f"median={format_stat(stats_pred['median'])} "
        f"p90={format_stat(stats_pred['p90'])} "
        f"max={format_stat(stats_pred['max'])}"
    )
    print(
        f"[INFO] main {center_series_label} vs /slosh/height: "
        f"MAE={format_stat(mae(report_center_mm, interp_slosh_mm))} "
        f"RMSE={format_stat(rmse(report_center_mm, interp_slosh_mm))} "
        f"Corr={format_stat(corr(report_center_mm, interp_slosh_mm))}"
    )
    print(
        "[INFO] diagnostic peak vs /slosh/height_pred_max: "
        f"MAE={format_stat(mae(report_peak_mm, interp_pred_mm))} "
        f"RMSE={format_stat(rmse(report_peak_mm, interp_pred_mm))} "
        f"Corr={format_stat(corr(report_peak_mm, interp_pred_mm))}"
    )
    print(
        f"[INFO] diagnostic {center_series_label} vs /slosh/height_pred_max: "
        f"MAE={format_stat(mae(report_center_mm, interp_pred_mm))} "
        f"RMSE={format_stat(rmse(report_center_mm, interp_pred_mm))} "
        f"Corr={format_stat(corr(report_center_mm, interp_pred_mm))}"
    )
    print(
        "[INFO] diagnostic peak vs /slosh/height: "
        f"MAE={format_stat(mae(report_peak_mm, interp_slosh_mm))} "
        f"RMSE={format_stat(rmse(report_peak_mm, interp_slosh_mm))} "
        f"Corr={format_stat(corr(report_peak_mm, interp_slosh_mm))}"
    )


if __name__ == "__main__":
    main()
