#!/usr/bin/env python3
"""Extract liquid-height time series from a rosbag using manual calibration."""

import argparse
import csv
import math
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import cv2
import numpy as np
import rosbag
import yaml
from cv_bridge import CvBridge, CvBridgeError

try:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
except Exception:  # pylint: disable=broad-except
    plt = None


@dataclass
class Calibration:
    roi_x: int
    roi_y: int
    roi_w: int
    roi_h: int
    x_left: int
    x_right: int
    still_level_px: float
    mm_per_pixel: Optional[float]
    mode: str
    left_wall_line: np.ndarray
    right_wall_line: np.ndarray
    still_level_line: np.ndarray
    tube_axis_line: np.ndarray
    rotation_deg: float = 0.0


@dataclass
class ProcessingConfig:
    blur_kernel: int = 5
    threshold_bias: int = -10
    use_clahe: bool = True
    use_adaptive_threshold: bool = True
    use_edge_fallback: bool = True
    use_temporal_gate: bool = True
    min_valid_columns: int = 20
    central_band_ratio: float = 0.6
    evaluation_x_ratio: float = 0.25
    max_frame_jump_px: float = 8.0
    max_fit_residual_px: float = 4.0
    max_slope_abs: float = 0.35
    morphology_open_kernel: int = 3
    morphology_close_kernel: int = 5
    adaptive_block_size: int = 31
    adaptive_c_offset: float = 7.0
    min_body_span_ratio: float = 0.32
    candidate_blend_tolerance_px: float = 2.5
    candidate_edge_agreement_px: float = 3.5
    peak_side_margin_ratio: float = 0.06
    peak_side_band_ratio: float = 0.22
    peak_side_top_fraction: float = 0.22
    peak_side_min_columns: int = 6
    peak_neighborhood_half_width: int = 12
    report_min_confidence: float = 0.73
    report_min_central_coverage: float = 0.40
    report_min_peak_distance_to_top_px: float = 12.0
    report_min_peak_body_span_ratio: float = 0.30
    report_max_fit_rms_px: float = 1.9
    report_max_temporal_jump_px: float = 4.5
    report_max_peak_local_rms_px: float = 1.6
    report_max_peak_edge_dominance: float = 0.55


@dataclass
class TemporalState:
    fit_coeff: np.ndarray
    left_y: float
    right_y: float
    peak_y: float


def parse_args():
    parser = argparse.ArgumentParser(
        description="Extract liquid-height time series from a rosbag using ROI calibration."
    )
    parser.add_argument("--bag", required=True, help="Path to the rosbag file.")
    parser.add_argument(
        "--calibration",
        required=True,
        help="Path to the *_calibration.yaml generated by annotate_liquid_roi.py.",
    )
    parser.add_argument(
        "--config",
        default="",
        help="Optional package config YAML. Used only for processing defaults.",
    )
    parser.add_argument(
        "--image-topic",
        default="",
        help="RGB image topic. Defaults to config topic_image or /camera/color/image_raw.",
    )
    parser.add_argument(
        "--out-dir",
        default="",
        help="Output directory. Defaults to <bag_stem>_liquid_measurement next to the bag.",
    )
    parser.add_argument(
        "--encoding",
        default="bgr8",
        help="Desired OpenCV encoding passed to cv_bridge.",
    )
    parser.add_argument(
        "--time-offset",
        type=float,
        default=0.0,
        help="Skip frames before bag_start + time_offset seconds.",
    )
    parser.add_argument(
        "--max-frames",
        type=int,
        default=0,
        help="Maximum number of frames to process after filtering. 0 means all frames.",
    )
    parser.add_argument(
        "--every",
        type=int,
        default=1,
        help="Process every N-th frame after time filtering.",
    )
    parser.add_argument(
        "--debug-fps",
        type=float,
        default=10.0,
        help="FPS for the debug video writer.",
    )
    parser.add_argument(
        "--skip-debug-video",
        action="store_true",
        help="Skip debug video generation and write CSV only.",
    )
    parser.add_argument(
        "--skip-plot",
        action="store_true",
        help="Skip summary plot generation and write CSV/debug video only.",
    )
    parser.add_argument(
        "--plot-confidence",
        action="store_true",
        help="Add a second subplot for meniscus_confidence under the peak-height curve.",
    )
    parser.add_argument(
        "--threshold-bias",
        type=int,
        default=None,
        help="Override threshold bias in intensity units.",
    )
    parser.add_argument(
        "--blur-kernel",
        type=int,
        default=None,
        help="Override Gaussian blur kernel size.",
    )
    parser.add_argument(
        "--no-clahe",
        action="store_true",
        help="Disable CLAHE even if config enables it.",
    )
    parser.add_argument(
        "--no-edge-fallback",
        action="store_true",
        help="Disable Sobel-Y fallback when threshold detection misses columns.",
    )
    parser.add_argument(
        "--auto-zero-baseline",
        action="store_true",
        help="Estimate a better still_level_px from the first valid static frames and report/write an adjusted calibration.",
    )
    parser.add_argument(
        "--baseline-frame-count",
        type=int,
        default=80,
        help="Number of valid frames used for static auto-zero baseline estimation.",
    )
    parser.add_argument(
        "--baseline-stat",
        choices=["median", "mean"],
        default="median",
        help="Statistic used for static auto-zero baseline estimation.",
    )
    parser.add_argument(
        "--baseline-target",
        choices=["peak", "center", "left", "right"],
        default="peak",
        help="Which reported quantity to drive to zero during auto-zero baseline estimation.",
    )
    parser.add_argument(
        "--write-adjusted-calibration",
        default="",
        help="Optional path for the auto-zero-adjusted calibration YAML. Defaults to <calibration_stem>_auto_zero.yaml next to the input calibration.",
    )
    return parser.parse_args()


def script_default_config() -> Path:
    return Path(__file__).resolve().parents[1] / "config" / "liquid_measurement.yaml"


def default_output_dir(bag_path: Path) -> Path:
    return bag_path.parent / f"{bag_path.stem}_liquid_measurement"


def default_adjusted_calibration_path(calibration_path: Path) -> Path:
    return calibration_path.parent / f"{calibration_path.stem}_auto_zero.yaml"


def load_yaml(path: Path) -> Dict:
    if not path.exists():
        raise FileNotFoundError(str(path))
    with path.open("r", encoding="utf-8") as stream:
        data = yaml.safe_load(stream)
    return data or {}


def load_processing_config(path: Optional[Path]) -> Tuple[Dict, ProcessingConfig]:
    defaults = ProcessingConfig()
    config_dict: Dict = {}
    if path and path.exists():
        config_dict = load_yaml(path)

    processing = config_dict.get("processing", {})
    config = ProcessingConfig(
        blur_kernel=int(processing.get("blur_kernel", defaults.blur_kernel)),
        threshold_bias=int(processing.get("threshold_bias", defaults.threshold_bias)),
        use_clahe=bool(processing.get("use_clahe", defaults.use_clahe)),
        use_adaptive_threshold=bool(processing.get("use_adaptive_threshold", defaults.use_adaptive_threshold)),
        use_edge_fallback=bool(processing.get("use_edge_fallback", defaults.use_edge_fallback)),
        use_temporal_gate=bool(processing.get("use_temporal_gate", defaults.use_temporal_gate)),
        min_valid_columns=int(processing.get("min_valid_columns", defaults.min_valid_columns)),
        central_band_ratio=float(processing.get("central_band_ratio", defaults.central_band_ratio)),
        evaluation_x_ratio=float(processing.get("evaluation_x_ratio", defaults.evaluation_x_ratio)),
        max_frame_jump_px=float(processing.get("max_frame_jump_px", defaults.max_frame_jump_px)),
        max_fit_residual_px=float(processing.get("max_fit_residual_px", defaults.max_fit_residual_px)),
        max_slope_abs=float(processing.get("max_slope_abs", defaults.max_slope_abs)),
        morphology_open_kernel=int(processing.get("morphology_open_kernel", defaults.morphology_open_kernel)),
        morphology_close_kernel=int(processing.get("morphology_close_kernel", defaults.morphology_close_kernel)),
        adaptive_block_size=int(processing.get("adaptive_block_size", defaults.adaptive_block_size)),
        adaptive_c_offset=float(processing.get("adaptive_c_offset", defaults.adaptive_c_offset)),
        min_body_span_ratio=float(processing.get("min_body_span_ratio", defaults.min_body_span_ratio)),
        candidate_blend_tolerance_px=float(
            processing.get("candidate_blend_tolerance_px", defaults.candidate_blend_tolerance_px)
        ),
        candidate_edge_agreement_px=float(
            processing.get("candidate_edge_agreement_px", defaults.candidate_edge_agreement_px)
        ),
        peak_side_margin_ratio=float(
            processing.get("peak_side_margin_ratio", defaults.peak_side_margin_ratio)
        ),
        peak_side_band_ratio=float(
            processing.get("peak_side_band_ratio", defaults.peak_side_band_ratio)
        ),
        peak_side_top_fraction=float(
            processing.get("peak_side_top_fraction", defaults.peak_side_top_fraction)
        ),
        peak_side_min_columns=int(
            processing.get("peak_side_min_columns", defaults.peak_side_min_columns)
        ),
        peak_neighborhood_half_width=int(
            processing.get("peak_neighborhood_half_width", defaults.peak_neighborhood_half_width)
        ),
        report_min_confidence=float(processing.get("report_min_confidence", defaults.report_min_confidence)),
        report_min_central_coverage=float(
            processing.get("report_min_central_coverage", defaults.report_min_central_coverage)
        ),
        report_min_peak_distance_to_top_px=float(
            processing.get("report_min_peak_distance_to_top_px", defaults.report_min_peak_distance_to_top_px)
        ),
        report_min_peak_body_span_ratio=float(
            processing.get("report_min_peak_body_span_ratio", defaults.report_min_peak_body_span_ratio)
        ),
        report_max_fit_rms_px=float(processing.get("report_max_fit_rms_px", defaults.report_max_fit_rms_px)),
        report_max_temporal_jump_px=float(
            processing.get("report_max_temporal_jump_px", defaults.report_max_temporal_jump_px)
        ),
        report_max_peak_local_rms_px=float(
            processing.get("report_max_peak_local_rms_px", defaults.report_max_peak_local_rms_px)
        ),
        report_max_peak_edge_dominance=float(
            processing.get("report_max_peak_edge_dominance", defaults.report_max_peak_edge_dominance)
        ),
    )
    return config_dict, config


def parse_line_points(raw_value, name: str) -> np.ndarray:
    array = np.asarray(raw_value, dtype=np.float32)
    if array.shape != (2, 2):
        raise ValueError(f"{name} must be a 2x2 point list.")
    return array


def make_vertical_line(x_value: float, height: int) -> np.ndarray:
    return np.asarray([[float(x_value), 0.0], [float(x_value), float(max(0, height - 1))]], dtype=np.float32)


def make_horizontal_line(y_value: float, width: int) -> np.ndarray:
    return np.asarray([[0.0, float(y_value)], [float(max(0, width - 1)), float(y_value)]], dtype=np.float32)


def line_mean_x(line: np.ndarray) -> float:
    return float(np.mean(line[:, 0]))


def line_mean_y(line: np.ndarray) -> float:
    return float(np.mean(line[:, 1]))


def evaluate_line_y_from_points(line: np.ndarray, x_value: float) -> float:
    x0, y0 = float(line[0, 0]), float(line[0, 1])
    x1, y1 = float(line[1, 0]), float(line[1, 1])
    if abs(x1 - x0) < 1e-6:
        return 0.5 * (y0 + y1)
    alpha = (float(x_value) - x0) / (x1 - x0)
    return float(y0 + alpha * (y1 - y0))


def transform_line(line: np.ndarray, matrix: np.ndarray) -> np.ndarray:
    return cv2.transform(line.reshape(1, -1, 2), matrix)[0]


def copy_calibration_with_geometry(
    base: Calibration,
    left_wall_line: np.ndarray,
    right_wall_line: np.ndarray,
    still_level_line: np.ndarray,
    tube_axis_line: np.ndarray,
    rotation_deg: float,
) -> Calibration:
    x_left = int(round(line_mean_x(left_wall_line)))
    x_right = int(round(line_mean_x(right_wall_line)))
    center_x = 0.5 * (x_left + x_right)
    still_level_px = evaluate_line_y_from_points(still_level_line, center_x)

    if x_left > x_right:
        left_wall_line, right_wall_line = right_wall_line, left_wall_line
        x_left, x_right = x_right, x_left

    x_left = int(np.clip(x_left, 0, max(0, base.roi_w - 2)))
    x_right = int(np.clip(x_right, x_left + 1, max(x_left + 1, base.roi_w - 1)))
    still_level_px = float(np.clip(still_level_px, 0.0, max(0.0, base.roi_h - 1.0)))

    return Calibration(
        roi_x=base.roi_x,
        roi_y=base.roi_y,
        roi_w=base.roi_w,
        roi_h=base.roi_h,
        x_left=x_left,
        x_right=x_right,
        still_level_px=still_level_px,
        mm_per_pixel=base.mm_per_pixel,
        mode=base.mode,
        left_wall_line=np.asarray(left_wall_line, dtype=np.float32),
        right_wall_line=np.asarray(right_wall_line, dtype=np.float32),
        still_level_line=np.asarray(still_level_line, dtype=np.float32),
        tube_axis_line=np.asarray(tube_axis_line, dtype=np.float32),
        rotation_deg=float(rotation_deg),
    )


def rectify_roi_and_calibration(roi_bgr: np.ndarray, calibration: Calibration) -> Tuple[np.ndarray, Calibration]:
    axis = calibration.tube_axis_line
    dx = float(axis[1, 0] - axis[0, 0])
    dy = float(axis[1, 1] - axis[0, 1])
    if abs(dx) < 1e-6 and abs(dy) < 1e-6:
        return roi_bgr, calibration

    theta_deg = math.degrees(math.atan2(dy, dx))
    rotate_deg = 90.0 - theta_deg
    if abs(rotate_deg) < 1e-4:
        return roi_bgr, calibration

    center = ((calibration.roi_w - 1) * 0.5, (calibration.roi_h - 1) * 0.5)
    matrix = cv2.getRotationMatrix2D(center, rotate_deg, 1.0)
    rotated = cv2.warpAffine(
        roi_bgr,
        matrix,
        (calibration.roi_w, calibration.roi_h),
        flags=cv2.INTER_LINEAR,
        borderMode=cv2.BORDER_CONSTANT,
        borderValue=(255, 255, 255),
    )

    rectified = copy_calibration_with_geometry(
        calibration,
        transform_line(calibration.left_wall_line, matrix),
        transform_line(calibration.right_wall_line, matrix),
        transform_line(calibration.still_level_line, matrix),
        transform_line(calibration.tube_axis_line, matrix),
        calibration.rotation_deg + rotate_deg,
    )
    return rotated, rectified


def load_calibration(path: Path) -> Calibration:
    data = load_yaml(path)
    roi = data.get("roi", {})
    tube_inner = data.get("tube_inner", {})
    calib = data.get("calibration", {})
    source = data.get("source", {})
    geometry_roi = data.get("geometry_roi", {})

    required = ["x", "y", "w", "h"]
    for key in required:
        if key not in roi:
            raise ValueError(f"missing roi.{key} in {path}")
    for key in ["x_left", "x_right"]:
        if key not in tube_inner:
            raise ValueError(f"missing tube_inner.{key} in {path}")
    if "still_level_px" not in calib:
        raise ValueError(f"missing calibration.still_level_px in {path}")

    mm_per_pixel = calib.get("mm_per_pixel", None)
    if mm_per_pixel is not None:
        mm_per_pixel = float(mm_per_pixel)

    roi_w = int(roi["w"])
    roi_h = int(roi["h"])
    x_left = int(tube_inner["x_left"])
    x_right = int(tube_inner["x_right"])
    still_level_px = float(calib["still_level_px"])

    left_wall_line = parse_line_points(
        geometry_roi.get("left_wall_line", make_vertical_line(x_left, roi_h)),
        "geometry_roi.left_wall_line",
    )
    right_wall_line = parse_line_points(
        geometry_roi.get("right_wall_line", make_vertical_line(x_right, roi_h)),
        "geometry_roi.right_wall_line",
    )
    still_level_line = parse_line_points(
        geometry_roi.get("still_level_line", make_horizontal_line(still_level_px, roi_w)),
        "geometry_roi.still_level_line",
    )
    default_axis_x = 0.5 * (x_left + x_right)
    tube_axis_line = parse_line_points(
        geometry_roi.get("tube_axis_line", make_vertical_line(default_axis_x, roi_h)),
        "geometry_roi.tube_axis_line",
    )

    calibration = Calibration(
        roi_x=int(roi["x"]),
        roi_y=int(roi["y"]),
        roi_w=roi_w,
        roi_h=roi_h,
        x_left=x_left,
        x_right=x_right,
        still_level_px=still_level_px,
        mm_per_pixel=mm_per_pixel,
        mode=str(source.get("mode", "unknown")),
        left_wall_line=left_wall_line,
        right_wall_line=right_wall_line,
        still_level_line=still_level_line,
        tube_axis_line=tube_axis_line,
    )

    calibration = copy_calibration_with_geometry(
        calibration,
        calibration.left_wall_line,
        calibration.right_wall_line,
        calibration.still_level_line,
        calibration.tube_axis_line,
        calibration.rotation_deg,
    )

    if calibration.roi_w <= 0 or calibration.roi_h <= 0:
        raise ValueError("ROI width/height must be positive.")
    if calibration.x_left < 0 or calibration.x_right >= calibration.roi_w or calibration.x_left >= calibration.x_right:
        raise ValueError("tube_inner x_left/x_right must be inside ROI and x_left < x_right.")

    return calibration


def image_topics_in_bag(bag: rosbag.Bag) -> List[str]:
    topics = []
    topic_info = bag.get_type_and_topic_info().topics
    for topic, info in sorted(topic_info.items()):
        if info.msg_type == "sensor_msgs/Image":
            topics.append(topic)
    return topics


def ensure_output_dir(path: Path):
    path.mkdir(parents=True, exist_ok=True)


def odd_kernel_size(size: int) -> int:
    size = max(1, int(size))
    if size % 2 == 0:
        size += 1
    return size


def apply_preprocess(roi_bgr: np.ndarray, config: ProcessingConfig) -> np.ndarray:
    gray = cv2.cvtColor(roi_bgr, cv2.COLOR_BGR2GRAY)
    if config.use_clahe:
        clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
        gray = clahe.apply(gray)
    blur_kernel = odd_kernel_size(config.blur_kernel)
    if blur_kernel > 1:
        gray = cv2.GaussianBlur(gray, (blur_kernel, blur_kernel), 0)
    return gray


def compute_threshold(gray_tube: np.ndarray, bias: int) -> Tuple[int, np.ndarray]:
    otsu_value, _ = cv2.threshold(gray_tube, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
    threshold_value = int(np.clip(round(otsu_value) + bias, 0, 255))
    _, mask = cv2.threshold(gray_tube, threshold_value, 255, cv2.THRESH_BINARY_INV)
    return threshold_value, mask


def compute_adaptive_threshold(gray_tube: np.ndarray, block_size: int, c_offset: float) -> np.ndarray:
    block_size = odd_kernel_size(block_size)
    block_size = max(3, block_size)
    return cv2.adaptiveThreshold(
        gray_tube,
        255,
        cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
        cv2.THRESH_BINARY_INV,
        block_size,
        float(c_offset),
    )


def cleanup_threshold_mask(mask: np.ndarray, config: ProcessingConfig) -> np.ndarray:
    cleaned = mask.copy()

    open_kernel = odd_kernel_size(config.morphology_open_kernel)
    close_kernel = odd_kernel_size(config.morphology_close_kernel)
    if open_kernel > 1:
        kernel = np.ones((open_kernel, open_kernel), dtype=np.uint8)
        cleaned = cv2.morphologyEx(cleaned, cv2.MORPH_OPEN, kernel)
    if close_kernel > 1:
        kernel = np.ones((close_kernel, close_kernel), dtype=np.uint8)
        cleaned = cv2.morphologyEx(cleaned, cv2.MORPH_CLOSE, kernel)

    return keep_bottom_connected_region(cleaned)


def keep_bottom_connected_region(mask: np.ndarray) -> np.ndarray:
    if mask.size == 0 or np.count_nonzero(mask) == 0:
        return mask

    num_labels, labels, stats, _ = cv2.connectedComponentsWithStats(mask, connectivity=8)
    if num_labels <= 1:
        return mask

    keep_labels = set()
    bottom_slice = labels[max(0, labels.shape[0] - 3) :, :]
    for label_id in np.unique(bottom_slice):
        if label_id != 0:
            keep_labels.add(int(label_id))

    if not keep_labels:
        areas = stats[1:, cv2.CC_STAT_AREA]
        if areas.size == 0:
            return mask
        keep_labels.add(int(1 + np.argmax(areas)))

    kept = np.zeros_like(mask)
    for label_id in keep_labels:
        kept[labels == label_id] = 255
    return kept


def combine_dark_masks(global_mask: np.ndarray, adaptive_mask: Optional[np.ndarray], config: ProcessingConfig) -> np.ndarray:
    combined = global_mask.copy()
    if adaptive_mask is not None:
        combined = cv2.bitwise_or(combined, adaptive_mask)
    return cleanup_threshold_mask(combined, config)


def row_body_span_ratio(mask: np.ndarray) -> np.ndarray:
    if mask.size == 0:
        return np.zeros(0, dtype=np.float32)
    width = float(mask.shape[1])
    if width <= 0.0:
        return np.zeros(mask.shape[0], dtype=np.float32)
    return np.count_nonzero(mask > 0, axis=1).astype(np.float32) / width


def body_span_ratio_at_y(
    profile: np.ndarray,
    y_value: float,
    band_half_height: int = 2,
    look_below: bool = False,
) -> float:
    if profile.size == 0 or not np.isfinite(y_value):
        return 0.0
    center = int(round(float(y_value)))
    band_half_height = max(0, int(band_half_height))
    if look_below:
        y0 = max(0, center + 1)
        y1 = min(profile.shape[0], center + 1 + max(1, 2 * band_half_height + 1))
    else:
        y0 = max(0, center - band_half_height)
        y1 = min(profile.shape[0], center + band_half_height + 1)
    if y1 <= y0:
        return 0.0
    return float(np.max(profile[y0:y1]))


def enforce_body_span_on_candidates(
    values: np.ndarray,
    span_profile: np.ndarray,
    min_span_ratio: float,
    band_half_height: int = 2,
    look_below: bool = False,
) -> Tuple[np.ndarray, int]:
    filtered = values.copy()
    rejected = 0
    min_span_ratio = max(0.0, float(min_span_ratio))
    for idx in range(filtered.shape[0]):
        if not np.isfinite(filtered[idx]):
            continue
        if body_span_ratio_at_y(
            span_profile,
            filtered[idx],
            band_half_height=band_half_height,
            look_below=look_below,
        ) < min_span_ratio:
            filtered[idx] = np.nan
            rejected += 1
    return filtered, rejected


def sustained_dark_start(column_mask: np.ndarray, min_run: int, min_fraction: float = 0.65) -> Optional[int]:
    column = (column_mask > 0).astype(np.uint8)
    if column.size < min_run:
        return None

    window = np.convolve(column, np.ones(min_run, dtype=np.int32), mode="valid")
    needed = int(math.ceil(min_fraction * min_run))
    hits = np.flatnonzero(window >= needed)
    if hits.size == 0:
        return None
    return int(hits[0])


def edge_candidates(
    gray_tube: np.ndarray, anchor_profile: np.ndarray, search_half_band: int
) -> Tuple[np.ndarray, float, np.ndarray]:
    gradient = -cv2.Sobel(gray_tube, cv2.CV_32F, 0, 1, ksize=3)
    candidates = np.full(gray_tube.shape[1], np.nan, dtype=np.float32)
    scores = np.full(gray_tube.shape[1], np.nan, dtype=np.float32)
    search_half_band = max(3, int(search_half_band))

    for idx in range(gray_tube.shape[1]):
        anchor_y = float(anchor_profile[idx])
        y0 = max(0, int(round(anchor_y)) - search_half_band)
        y1 = min(gray_tube.shape[0], int(round(anchor_y)) + search_half_band + 1)
        if y1 <= y0:
            continue
        column = gradient[y0:y1, idx]
        best = int(np.argmax(column))
        score = float(column[best])
        scores[idx] = score

    valid_scores = scores[np.isfinite(scores)]
    if valid_scores.size == 0:
        return candidates, np.inf, scores

    score_threshold = float(np.mean(valid_scores) + 1.0 * np.std(valid_scores))
    for idx in range(gray_tube.shape[1]):
        if not np.isfinite(scores[idx]) or scores[idx] < score_threshold:
            continue
        anchor_y = float(anchor_profile[idx])
        y0 = max(0, int(round(anchor_y)) - search_half_band)
        candidates[idx] = float(y0 + int(np.argmax(gradient[y0 : min(gray_tube.shape[0], int(round(anchor_y)) + search_half_band + 1), idx])))
    return candidates, score_threshold, scores


def normalize_edge_scores(scores: np.ndarray, score_threshold: float) -> np.ndarray:
    normalized = np.full(scores.shape, np.nan, dtype=np.float32)
    valid = scores[np.isfinite(scores)]
    if valid.size == 0:
        return normalized
    p50 = float(np.percentile(valid, 50))
    p90 = float(np.percentile(valid, 90))
    scale = max(1e-6, p90 - p50)
    finite_mask = np.isfinite(scores)
    normalized[finite_mask] = np.clip((scores[finite_mask] - score_threshold) / scale, 0.0, 1.0)
    return normalized


def candidate_quality_score(
    y_value: float,
    expected_y: float,
    span_profile: np.ndarray,
    reference_edge_y: Optional[float],
    normalized_edge_strength: float,
    config: ProcessingConfig,
) -> float:
    span = body_span_ratio_at_y(span_profile, y_value, band_half_height=3, look_below=True)
    proximity = max(
        0.0,
        1.0 - abs(float(y_value) - float(expected_y)) / max(config.max_frame_jump_px * 1.5, 6.0),
    )
    if reference_edge_y is None or not np.isfinite(reference_edge_y):
        edge_agreement = 0.0
    else:
        edge_agreement = max(
            0.0,
            1.0 - abs(float(y_value) - float(reference_edge_y)) / max(config.candidate_edge_agreement_px, 1e-6),
        )
    return float(0.48 * span + 0.24 * proximity + 0.18 * edge_agreement + 0.10 * normalized_edge_strength)


def fuse_column_candidates(
    primary: np.ndarray,
    fallback: np.ndarray,
    expected_profile: np.ndarray,
    span_profile: np.ndarray,
    edge_score_norm: np.ndarray,
    config: ProcessingConfig,
) -> Tuple[np.ndarray, Dict[str, int], np.ndarray]:
    fused = np.full(primary.shape, np.nan, dtype=np.float32)
    source_labels = np.zeros(primary.shape, dtype=np.uint8)
    stats = {
        "primary_selected_columns": 0,
        "edge_selected_columns": 0,
        "blended_columns": 0,
    }

    for idx in range(primary.shape[0]):
        primary_y = primary[idx]
        fallback_y = fallback[idx]
        expected_y = expected_profile[idx]
        edge_strength = 0.0 if not np.isfinite(edge_score_norm[idx]) else float(edge_score_norm[idx])

        primary_valid = np.isfinite(primary_y)
        fallback_valid = np.isfinite(fallback_y)

        if primary_valid and fallback_valid:
            if abs(float(primary_y) - float(fallback_y)) <= config.candidate_blend_tolerance_px:
                primary_score = candidate_quality_score(
                    float(primary_y), float(expected_y), span_profile, float(fallback_y), edge_strength, config
                )
                fallback_score = candidate_quality_score(
                    float(fallback_y), float(expected_y), span_profile, float(fallback_y), edge_strength, config
                )
                primary_weight = max(0.2, primary_score + 0.05)
                fallback_weight = max(0.2, fallback_score + 0.05)
                fused[idx] = float(
                    (primary_weight * float(primary_y) + fallback_weight * float(fallback_y))
                    / (primary_weight + fallback_weight)
                )
                source_labels[idx] = 3
                stats["blended_columns"] += 1
            else:
                primary_score = candidate_quality_score(
                    float(primary_y), float(expected_y), span_profile, float(fallback_y), edge_strength, config
                )
                fallback_score = candidate_quality_score(
                    float(fallback_y), float(expected_y), span_profile, float(fallback_y), edge_strength, config
                )
                if fallback_score > primary_score + 0.05:
                    fused[idx] = float(fallback_y)
                    source_labels[idx] = 2
                    stats["edge_selected_columns"] += 1
                else:
                    fused[idx] = float(primary_y)
                    source_labels[idx] = 1
                    stats["primary_selected_columns"] += 1
        elif primary_valid:
            fused[idx] = float(primary_y)
            source_labels[idx] = 1
            stats["primary_selected_columns"] += 1
        elif fallback_valid:
            fused[idx] = float(fallback_y)
            source_labels[idx] = 2
            stats["edge_selected_columns"] += 1

    return fused, stats, source_labels


def peak_neighborhood_metrics(
    profile_y: np.ndarray,
    source_labels: np.ndarray,
    fit_coeff: Optional[np.ndarray],
    peak_eval_x: Optional[float],
    half_width: int,
) -> Dict[str, Optional[float]]:
    if fit_coeff is None or peak_eval_x is None or profile_y.size == 0:
        return {
            "peak_local_support_ratio": None,
            "peak_local_rms_px": None,
            "peak_edge_dominance": None,
        }

    half_width = max(2, int(half_width))
    center_idx = int(round(float(peak_eval_x)))
    x0 = max(0, center_idx - half_width)
    x1 = min(profile_y.shape[0], center_idx + half_width + 1)
    if x1 <= x0:
        return {
            "peak_local_support_ratio": None,
            "peak_local_rms_px": None,
            "peak_edge_dominance": None,
        }

    local_values = profile_y[x0:x1]
    local_labels = source_labels[x0:x1]
    valid_mask = np.isfinite(local_values)
    support_ratio = float(np.count_nonzero(valid_mask)) / float(x1 - x0)
    if np.count_nonzero(valid_mask) == 0:
        return {
            "peak_local_support_ratio": support_ratio,
            "peak_local_rms_px": None,
            "peak_edge_dominance": None,
        }

    xs = np.arange(x0, x1, dtype=np.float32)[valid_mask]
    ys = local_values[valid_mask].astype(np.float32)
    predicted = fit_coeff[0] * xs + fit_coeff[1]
    local_rms = float(np.sqrt(np.mean(np.square(ys - predicted))))

    labels_valid = local_labels[valid_mask]
    edge_ratio = float(np.count_nonzero(labels_valid == 2)) / float(labels_valid.size)
    blend_ratio = float(np.count_nonzero(labels_valid == 3)) / float(labels_valid.size)
    edge_dominance = float(min(1.0, edge_ratio + 0.5 * blend_ratio))

    return {
        "peak_local_support_ratio": support_ratio,
        "peak_local_rms_px": local_rms,
        "peak_edge_dominance": edge_dominance,
    }


def reject_outliers(values: np.ndarray, roi_h: int) -> np.ndarray:
    valid = np.isfinite(values)
    if np.count_nonzero(valid) < 5:
        return values

    median = float(np.nanmedian(values))
    deviation = np.abs(values - median)
    mad = float(np.nanmedian(deviation[valid]))
    margin = max(8.0, roi_h * 0.18)
    if mad > 1e-6:
        margin = max(margin, 3.5 * 1.4826 * mad)

    result = values.copy()
    result[deviation > margin] = np.nan
    return result


def central_band_bounds(width: int, ratio: float) -> Tuple[int, int]:
    ratio = float(np.clip(ratio, 0.1, 1.0))
    band_width = max(6, int(round(width * ratio)))
    center = 0.5 * (width - 1)
    start = max(0, int(round(center - 0.5 * band_width)))
    end = min(width, start + band_width)
    start = max(0, end - band_width)
    return start, end


def side_band_bounds(width: int, margin_ratio: float, band_ratio: float) -> Tuple[Tuple[int, int], Tuple[int, int]]:
    width = max(1, int(width))
    margin = int(round(width * float(np.clip(margin_ratio, 0.0, 0.35))))
    band_width = max(6, int(round(width * float(np.clip(band_ratio, 0.08, 0.45)))))

    left_start = min(width - 1, margin)
    left_end = min(width, left_start + band_width)
    if left_end - left_start < 2:
        left_start = 0
        left_end = min(width, max(2, band_width))

    right_end = max(1, width - margin)
    right_start = max(0, right_end - band_width)
    if right_end - right_start < 2:
        right_end = width
        right_start = max(0, width - max(2, band_width))

    if left_end > right_start:
        center = width // 2
        left_end = min(left_end, center)
        right_start = max(right_start, center)
        if left_end - left_start < 2:
            left_start = 0
            left_end = max(2, center)
        if right_end - right_start < 2:
            right_start = min(width - 2, center)
            right_end = width

    return (left_start, left_end), (right_start, right_end)


def robust_band_peak(
    profile_y: np.ndarray,
    x_start: int,
    x_end: int,
    min_columns: int,
    top_fraction: float,
) -> Dict[str, Optional[float]]:
    x_start = max(0, int(x_start))
    x_end = min(profile_y.shape[0], int(x_end))
    band_width = max(0, x_end - x_start)
    if band_width <= 0:
        return {
            "y": None,
            "x": None,
            "support_ratio": 0.0,
            "valid_columns": 0,
        }

    band_values = profile_y[x_start:x_end]
    valid_mask = np.isfinite(band_values)
    valid_columns = int(np.count_nonzero(valid_mask))
    support_ratio = valid_columns / float(band_width)
    if valid_columns < max(2, int(min_columns)):
        return {
            "y": None,
            "x": None,
            "support_ratio": support_ratio,
            "valid_columns": valid_columns,
        }

    xs = np.arange(x_start, x_end, dtype=np.float32)[valid_mask]
    ys = band_values[valid_mask].astype(np.float32)
    keep_count = min(
        ys.size,
        max(int(min_columns), int(math.ceil(ys.size * float(np.clip(top_fraction, 0.05, 0.5))))),
    )
    order = np.argsort(ys)[:keep_count]
    top_xs = xs[order]
    top_ys = ys[order]

    return {
        "y": float(np.median(top_ys)),
        "x": float(np.median(top_xs)),
        "support_ratio": support_ratio,
        "valid_columns": valid_columns,
    }


def robust_line_fit(xs: np.ndarray, ys: np.ndarray, max_residual_px: float) -> Optional[Dict]:
    valid = np.isfinite(xs) & np.isfinite(ys)
    xs = xs[valid].astype(np.float32)
    ys = ys[valid].astype(np.float32)
    if xs.size < 2:
        return None

    inlier_mask = np.ones(xs.shape[0], dtype=bool)
    coeff = None
    residual = None
    for _ in range(4):
        if np.count_nonzero(inlier_mask) < 2:
            return None
        coeff = np.polyfit(xs[inlier_mask], ys[inlier_mask], 1)
        predicted = coeff[0] * xs + coeff[1]
        residual = np.abs(ys - predicted)
        adaptive_limit = max(float(max_residual_px), 2.5 * float(np.median(residual[inlier_mask])))
        new_mask = residual <= adaptive_limit
        if np.array_equal(new_mask, inlier_mask):
            break
        inlier_mask = new_mask

    if coeff is None or residual is None or np.count_nonzero(inlier_mask) < 2:
        return None

    coeff = np.polyfit(xs[inlier_mask], ys[inlier_mask], 1)
    predicted = coeff[0] * xs + coeff[1]
    residual = np.abs(ys - predicted)
    rms = float(np.sqrt(np.mean(np.square(residual[inlier_mask]))))

    return {
        "coeff": coeff,
        "xs": xs,
        "ys": ys,
        "inlier_mask": inlier_mask,
        "rms": rms,
        "count": int(np.count_nonzero(inlier_mask)),
    }


def evaluate_line(coeff: np.ndarray, x_value: float) -> float:
    return float(coeff[0] * x_value + coeff[1])


def expected_profile_from_state(width: int, previous_state: Optional[TemporalState], still_level_px: float) -> np.ndarray:
    xs = np.arange(width, dtype=np.float32)
    if previous_state is None:
        return np.full(width, float(still_level_px), dtype=np.float32)
    return previous_state.fit_coeff[0] * xs + previous_state.fit_coeff[1]


def apply_temporal_profile_gate(
    values: np.ndarray,
    fallback: np.ndarray,
    expected_profile: np.ndarray,
    max_frame_jump_px: float,
) -> Tuple[np.ndarray, int, int]:
    gated = values.copy()
    max_frame_jump_px = max(1.0, float(max_frame_jump_px))
    rejected = np.isfinite(gated) & (np.abs(gated - expected_profile) > max_frame_jump_px)
    gated[rejected] = np.nan

    recovered = ~np.isfinite(gated) & np.isfinite(fallback) & (np.abs(fallback - expected_profile) <= max_frame_jump_px)
    gated[recovered] = fallback[recovered]
    return gated, int(np.count_nonzero(rejected)), int(np.count_nonzero(recovered))


def build_temporal_state(detection: Dict) -> Optional[TemporalState]:
    if not detection["valid"] or detection["fit_coeff"] is None:
        return None
    if detection["left_y"] is None or detection["right_y"] is None or detection["peak_y"] is None:
        return None
    return TemporalState(
        fit_coeff=np.asarray(detection["fit_coeff"], dtype=np.float32),
        left_y=float(detection["left_y"]),
        right_y=float(detection["right_y"]),
        peak_y=float(detection["peak_y"]),
    )


def detect_liquid_profile(
    roi_bgr: np.ndarray,
    calibration: Calibration,
    config: ProcessingConfig,
    previous_state: Optional[TemporalState] = None,
) -> Dict:
    gray = apply_preprocess(roi_bgr, config)
    tube_gray = gray[:, calibration.x_left : calibration.x_right + 1]
    expected_profile = expected_profile_from_state(tube_gray.shape[1], previous_state, calibration.still_level_px)

    threshold_value, threshold_mask_raw = compute_threshold(tube_gray, config.threshold_bias)
    threshold_mask_global = cleanup_threshold_mask(threshold_mask_raw, config)
    adaptive_mask_raw = None
    threshold_mask_adaptive = None
    if config.use_adaptive_threshold:
        adaptive_mask_raw = compute_adaptive_threshold(
            tube_gray,
            config.adaptive_block_size,
            config.adaptive_c_offset,
        )
        threshold_mask_adaptive = cleanup_threshold_mask(adaptive_mask_raw, config)
    threshold_mask = combine_dark_masks(threshold_mask_global, threshold_mask_adaptive, config)
    span_profile = row_body_span_ratio(threshold_mask)

    min_run = max(5, int(round(calibration.roi_h * 0.06)))
    primary = np.full(tube_gray.shape[1], np.nan, dtype=np.float32)
    for idx in range(tube_gray.shape[1]):
        y = sustained_dark_start(threshold_mask[:, idx], min_run=min_run)
        if y is not None:
            primary[idx] = float(y)
    primary, body_span_rejected_primary = enforce_body_span_on_candidates(
        primary,
        span_profile,
        config.min_body_span_ratio,
        band_half_height=3,
        look_below=True,
    )

    fallback = np.full_like(primary, np.nan)
    edge_threshold = None
    edge_scores = np.full_like(primary, np.nan)
    if config.use_edge_fallback:
        search_half_band = (
            max(10, int(round(config.max_frame_jump_px * 1.5)))
            if previous_state is not None
            else max(18, tube_gray.shape[0] // 5)
        )
        fallback, edge_threshold, edge_scores = edge_candidates(tube_gray, expected_profile, search_half_band)
        fallback, _ = enforce_body_span_on_candidates(
            fallback,
            span_profile,
            max(0.18, 0.7 * config.min_body_span_ratio),
            band_half_height=3,
            look_below=True,
        )
    edge_score_norm = normalize_edge_scores(edge_scores, edge_threshold)
    combined, fusion_stats, source_labels = fuse_column_candidates(
        primary,
        fallback,
        expected_profile,
        span_profile,
        edge_score_norm,
        config,
    )
    temporal_rejected_columns = 0
    temporal_recovered_columns = 0
    if config.use_temporal_gate and previous_state is not None:
        combined, temporal_rejected_columns, temporal_recovered_columns = apply_temporal_profile_gate(
            combined,
            fallback,
            expected_profile,
            config.max_frame_jump_px,
        )
    combined = reject_outliers(combined, calibration.roi_h)

    width = combined.shape[0]
    valid_columns = int(np.count_nonzero(np.isfinite(combined)))
    central_start, central_end = central_band_bounds(width, config.central_band_ratio)
    central_values = combined[central_start:central_end]
    central_valid_columns = int(np.count_nonzero(np.isfinite(central_values)))
    central_xs = np.arange(central_start, central_end, dtype=np.float32)
    fit_result = robust_line_fit(central_xs, central_values, config.max_fit_residual_px)

    evaluation_x_ratio = float(np.clip(config.evaluation_x_ratio, 0.05, 0.45))
    left_eval_x = int(round((width - 1) * evaluation_x_ratio))
    right_eval_x = int(round((width - 1) * (1.0 - evaluation_x_ratio)))
    if right_eval_x <= left_eval_x:
        right_eval_x = min(width - 1, left_eval_x + 1)
    center_eval_x = 0.5 * (left_eval_x + right_eval_x)
    (left_band_start, left_band_end), (right_band_start, right_band_end) = side_band_bounds(
        width,
        config.peak_side_margin_ratio,
        config.peak_side_band_ratio,
    )

    left_y = None
    right_y = None
    center_y = None
    peak_y = None
    left_rel_px_signed = None
    right_rel_px_signed = None
    center_rel_px_signed = None
    peak_rel_px_signed = None
    left_rel_px = None
    right_rel_px = None
    center_rel_px = None
    peak_rel_px = None
    fit_coeff = None
    fit_rms_px = None
    fit_points = 0
    fit_slope = None
    temporal_jump_px = None
    temporal_gate_passed = previous_state is None
    peak_distance_to_top_px = None
    peak_eval_x = None
    left_peak_x = None
    right_peak_x = None
    left_peak_source = "missing"
    right_peak_source = "missing"
    peak_source = "missing"
    left_band_support_ratio = 0.0
    right_band_support_ratio = 0.0
    left_band_valid_columns = 0
    right_band_valid_columns = 0
    peak_local_support_ratio = None
    peak_local_rms_px = None
    peak_edge_dominance = None

    fit_valid = False
    if fit_result is not None:
        fit_coeff = fit_result["coeff"]
        fit_rms_px = fit_result["rms"]
        fit_points = fit_result["count"]
        fit_slope = float(fit_coeff[0])

        left_fit_y = evaluate_line(fit_coeff, left_eval_x)
        right_fit_y = evaluate_line(fit_coeff, right_eval_x)
        center_fit_y = evaluate_line(fit_coeff, center_eval_x)
        peak_fit_y = min(left_fit_y, right_fit_y)

        left_band_peak = robust_band_peak(
            combined,
            left_band_start,
            left_band_end,
            config.peak_side_min_columns,
            config.peak_side_top_fraction,
        )
        right_band_peak = robust_band_peak(
            combined,
            right_band_start,
            right_band_end,
            config.peak_side_min_columns,
            config.peak_side_top_fraction,
        )
        left_band_support_ratio = float(left_band_peak["support_ratio"])
        right_band_support_ratio = float(right_band_peak["support_ratio"])
        left_band_valid_columns = int(left_band_peak["valid_columns"])
        right_band_valid_columns = int(right_band_peak["valid_columns"])

        if left_band_peak["y"] is not None:
            left_y = float(left_band_peak["y"])
            left_peak_x = float(left_band_peak["x"])
            left_peak_source = "band"
        else:
            left_y = left_fit_y
            left_peak_x = float(left_eval_x)
            left_peak_source = "fit"
        if right_band_peak["y"] is not None:
            right_y = float(right_band_peak["y"])
            right_peak_x = float(right_band_peak["x"])
            right_peak_source = "band"
        else:
            right_y = right_fit_y
            right_peak_x = float(right_eval_x)
            right_peak_source = "fit"

        center_y = center_fit_y
        left_rel_px_signed = calibration.still_level_px - left_y
        right_rel_px_signed = calibration.still_level_px - right_y
        center_rel_px_signed = calibration.still_level_px - center_y
        left_rel_px = max(0.0, left_rel_px_signed)
        right_rel_px = max(0.0, right_rel_px_signed)
        center_rel_px = max(0.0, center_rel_px_signed)

        if left_rel_px_signed >= right_rel_px_signed:
            peak_y = left_y
            peak_eval_x = float(left_band_peak["x"]) if left_band_peak["x"] is not None else float(left_eval_x)
            peak_source = f"left_{left_peak_source}"
        else:
            peak_y = right_y
            peak_eval_x = float(right_band_peak["x"]) if right_band_peak["x"] is not None else float(right_eval_x)
            peak_source = f"right_{right_peak_source}"

        peak_rel_px_signed = max(left_rel_px_signed, right_rel_px_signed)
        peak_rel_px = max(0.0, peak_rel_px_signed)
        peak_distance_to_top_px = max(0.0, float(peak_y))
        local_metrics = peak_neighborhood_metrics(
            combined,
            source_labels,
            fit_coeff,
            peak_eval_x,
            config.peak_neighborhood_half_width,
        )
        peak_local_support_ratio = local_metrics["peak_local_support_ratio"]
        peak_local_rms_px = local_metrics["peak_local_rms_px"]
        peak_edge_dominance = local_metrics["peak_edge_dominance"]

        if previous_state is not None:
            temporal_jump_px = max(
                abs(left_y - previous_state.left_y),
                abs(right_y - previous_state.right_y),
                abs(peak_y - previous_state.peak_y),
            )
            temporal_gate_passed = temporal_jump_px <= config.max_frame_jump_px

        fit_valid = (
            fit_points >= max(8, config.min_valid_columns // 2)
            and fit_rms_px <= config.max_fit_residual_px
            and abs(fit_slope) <= config.max_slope_abs
            and -0.5 <= left_y <= calibration.roi_h - 0.5
            and -0.5 <= right_y <= calibration.roi_h - 0.5
            and temporal_gate_passed
        )

    coverage = 0.0 if central_end <= central_start else central_valid_columns / float(central_end - central_start)
    rms_score = 0.0 if fit_rms_px is None else max(0.0, 1.0 - fit_rms_px / max(config.max_fit_residual_px, 1e-6))
    slope_score = 0.0 if fit_slope is None else max(0.0, 1.0 - abs(fit_slope) / max(config.max_slope_abs, 1e-6))
    if previous_state is None or temporal_jump_px is None:
        jump_score = 1.0
    else:
        jump_score = max(0.0, 1.0 - temporal_jump_px / max(config.max_frame_jump_px, 1e-6))
    if peak_distance_to_top_px is None:
        top_boundary_score = 0.0
    else:
        top_boundary_score = min(
            1.0,
            peak_distance_to_top_px / max(config.report_min_peak_distance_to_top_px, 1e-6),
        )
    peak_body_span_ratio = (
        0.0
        if peak_y is None
        else body_span_ratio_at_y(span_profile, peak_y, band_half_height=3, look_below=True)
    )
    local_support_score = (
        0.0
        if peak_local_support_ratio is None
        else min(1.0, peak_local_support_ratio / 0.55)
    )
    local_rms_score = (
        0.0
        if peak_local_rms_px is None
        else max(0.0, 1.0 - peak_local_rms_px / max(config.report_max_peak_local_rms_px, 1e-6))
    )
    edge_dominance_score = (
        0.0
        if peak_edge_dominance is None
        else max(0.0, 1.0 - peak_edge_dominance / max(config.report_max_peak_edge_dominance, 1e-6))
    )
    body_span_score = min(
        1.0,
        peak_body_span_ratio / max(config.report_min_peak_body_span_ratio, 1e-6),
    )
    confidence = float(
        np.clip(
            0.21 * coverage
            + 0.18 * rms_score
            + 0.08 * slope_score
            + 0.14 * jump_score
            + 0.11 * top_boundary_score
            + 0.14 * body_span_score
            + 0.06 * local_support_score
            + 0.05 * local_rms_score
            + 0.03 * edge_dominance_score,
            0.0,
            1.0,
        )
    )

    valid = (
        valid_columns >= config.min_valid_columns
        and central_valid_columns >= max(6, int(round(0.35 * max(1, central_end - central_start))))
        and fit_valid
    )
    accept_for_peak_report = (
        valid
        and confidence >= config.report_min_confidence
        and coverage >= config.report_min_central_coverage
        and fit_rms_px is not None
        and fit_rms_px <= config.report_max_fit_rms_px
        and peak_distance_to_top_px is not None
        and peak_distance_to_top_px >= config.report_min_peak_distance_to_top_px
        and peak_body_span_ratio >= config.report_min_peak_body_span_ratio
        and (temporal_jump_px is None or temporal_jump_px <= config.report_max_temporal_jump_px)
        and peak_local_rms_px is not None
        and peak_local_rms_px <= config.report_max_peak_local_rms_px
    )

    return {
        "gray": gray,
        "threshold_mask": threshold_mask,
        "threshold_mask_raw": threshold_mask_raw,
        "threshold_mask_global": threshold_mask_global,
        "threshold_mask_adaptive": threshold_mask_adaptive,
        "threshold_value": threshold_value,
        "edge_threshold": edge_threshold,
        "edge_score_norm": edge_score_norm,
        "profile_y": combined,
        "central_start": central_start,
        "central_end": central_end,
        "left_eval_x": left_eval_x,
        "right_eval_x": right_eval_x,
        "center_eval_x": center_eval_x,
        "left_y": left_y,
        "right_y": right_y,
        "center_y": center_y,
        "peak_y": peak_y,
        "left_rel_px_signed": left_rel_px_signed,
        "right_rel_px_signed": right_rel_px_signed,
        "center_rel_px_signed": center_rel_px_signed,
        "peak_rel_px_signed": peak_rel_px_signed,
        "left_rel_px": left_rel_px,
        "right_rel_px": right_rel_px,
        "center_rel_px": center_rel_px,
        "peak_rel_px": peak_rel_px,
        "left_peak_source": left_peak_source,
        "right_peak_source": right_peak_source,
        "peak_source": peak_source,
        "left_peak_x": left_peak_x,
        "right_peak_x": right_peak_x,
        "left_band_start": left_band_start,
        "left_band_end": left_band_end,
        "right_band_start": right_band_start,
        "right_band_end": right_band_end,
        "left_band_support_ratio": left_band_support_ratio,
        "right_band_support_ratio": right_band_support_ratio,
        "left_band_valid_columns": left_band_valid_columns,
        "right_band_valid_columns": right_band_valid_columns,
        "valid": bool(valid),
        "confidence": confidence,
        "valid_columns": valid_columns,
        "central_valid_columns": central_valid_columns,
        "central_coverage": coverage,
        "temporal_rejected_columns": temporal_rejected_columns,
        "temporal_recovered_columns": temporal_recovered_columns,
        "temporal_jump_px": temporal_jump_px,
        "temporal_gate_passed": temporal_gate_passed,
        "peak_distance_to_top_px": peak_distance_to_top_px,
        "peak_body_span_ratio": peak_body_span_ratio,
        "peak_local_support_ratio": peak_local_support_ratio,
        "peak_local_rms_px": peak_local_rms_px,
        "peak_edge_dominance": peak_edge_dominance,
        "accept_for_peak_report": bool(accept_for_peak_report),
        "threshold_columns": int(np.count_nonzero(np.isfinite(primary))),
        "edge_columns": int(np.count_nonzero(np.isfinite(fallback))),
        "body_span_rejected_columns": body_span_rejected_primary,
        "primary_selected_columns": fusion_stats["primary_selected_columns"],
        "edge_selected_columns": fusion_stats["edge_selected_columns"],
        "blended_columns": fusion_stats["blended_columns"],
        "fit_coeff": fit_coeff,
        "fit_rms_px": fit_rms_px,
        "fit_points": fit_points,
        "fit_slope": fit_slope,
        "expected_profile": expected_profile,
        "fit_inlier_xs": None if fit_result is None else fit_result["xs"][fit_result["inlier_mask"]],
        "fit_inlier_ys": None if fit_result is None else fit_result["ys"][fit_result["inlier_mask"]],
    }


def maybe_mm(value_px: Optional[float], mm_per_pixel: Optional[float]) -> Optional[float]:
    if value_px is None or mm_per_pixel is None:
        return None
    return float(value_px) * float(mm_per_pixel)


def make_debug_frame(
    roi_bgr: np.ndarray,
    calibration: Calibration,
    frame_index: int,
    stamp_sec: float,
    detection: Dict,
) -> np.ndarray:
    canvas = roi_bgr.copy()
    h, w = canvas.shape[:2]

    cv2.rectangle(canvas, (0, 0), (w - 1, h - 1), (0, 255, 255), 1)
    cv2.line(
        canvas,
        tuple(np.round(calibration.left_wall_line[0]).astype(int)),
        tuple(np.round(calibration.left_wall_line[1]).astype(int)),
        (255, 0, 0),
        1,
    )
    cv2.line(
        canvas,
        tuple(np.round(calibration.right_wall_line[0]).astype(int)),
        tuple(np.round(calibration.right_wall_line[1]).astype(int)),
        (0, 128, 255),
        1,
    )
    cv2.line(
        canvas,
        tuple(np.round(calibration.still_level_line[0]).astype(int)),
        tuple(np.round(calibration.still_level_line[1]).astype(int)),
        (0, 255, 0),
        1,
    )
    cv2.line(
        canvas,
        tuple(np.round(calibration.tube_axis_line[0]).astype(int)),
        tuple(np.round(calibration.tube_axis_line[1]).astype(int)),
        (255, 0, 255),
        1,
    )

    central_start = int(detection["central_start"])
    central_end = int(detection["central_end"])
    cv2.line(canvas, (calibration.x_left + central_start, 0), (calibration.x_left + central_start, h - 1), (180, 180, 0), 1)
    cv2.line(canvas, (calibration.x_left + central_end - 1, 0), (calibration.x_left + central_end - 1, h - 1), (180, 180, 0), 1)
    cv2.line(
        canvas,
        (calibration.x_left + int(detection["left_band_start"]), 0),
        (calibration.x_left + int(detection["left_band_start"]), h - 1),
        (80, 170, 255),
        1,
    )
    cv2.line(
        canvas,
        (calibration.x_left + int(detection["left_band_end"] - 1), 0),
        (calibration.x_left + int(detection["left_band_end"] - 1), h - 1),
        (80, 170, 255),
        1,
    )
    cv2.line(
        canvas,
        (calibration.x_left + int(detection["right_band_start"]), 0),
        (calibration.x_left + int(detection["right_band_start"]), h - 1),
        (80, 170, 255),
        1,
    )
    cv2.line(
        canvas,
        (calibration.x_left + int(detection["right_band_end"] - 1), 0),
        (calibration.x_left + int(detection["right_band_end"] - 1), h - 1),
        (80, 170, 255),
        1,
    )

    profile_y = detection["profile_y"]
    xs = np.flatnonzero(np.isfinite(profile_y))
    for x_idx in xs[::2]:
        y_idx = int(round(float(profile_y[x_idx])))
        cv2.circle(canvas, (calibration.x_left + int(x_idx), y_idx), 1, (0, 255, 255), -1)

    expected_profile = detection["expected_profile"]
    if expected_profile is not None:
        for x_idx in range(0, expected_profile.shape[0], 6):
            y_idx = int(round(float(expected_profile[x_idx])))
            if 0 <= y_idx < h:
                cv2.circle(canvas, (calibration.x_left + int(x_idx), y_idx), 1, (255, 0, 255), -1)

    fit_inlier_xs = detection["fit_inlier_xs"]
    fit_inlier_ys = detection["fit_inlier_ys"]
    if fit_inlier_xs is not None and fit_inlier_ys is not None:
        for x_value, y_value in zip(fit_inlier_xs[::2], fit_inlier_ys[::2]):
            cv2.circle(
                canvas,
                (calibration.x_left + int(round(float(x_value))), int(round(float(y_value)))),
                2,
                (255, 255, 0),
                -1,
            )

    if detection["fit_coeff"] is not None:
        slope, intercept = detection["fit_coeff"]
        y0 = int(round(float(intercept)))
        y1 = int(round(float(slope * (profile_y.shape[0] - 1) + intercept)))
        cv2.line(
            canvas,
            (calibration.x_left, y0),
            (calibration.x_right, y1),
            (255, 255, 0),
            1,
        )

    left_eval_x = calibration.x_left + int(detection["left_eval_x"])
    right_eval_x = calibration.x_left + int(detection["right_eval_x"])
    cv2.line(canvas, (left_eval_x, 0), (left_eval_x, h - 1), (255, 120, 120), 1)
    cv2.line(canvas, (right_eval_x, 0), (right_eval_x, h - 1), (120, 120, 255), 1)

    if detection["left_y"] is not None:
        left_peak_x = calibration.x_left + int(round(float(detection["left_peak_x"])))
        cv2.circle(canvas, (left_peak_x, int(round(detection["left_y"]))), 4, (255, 0, 0), -1)
    if detection["right_y"] is not None:
        right_peak_x = calibration.x_left + int(round(float(detection["right_peak_x"])))
        cv2.circle(canvas, (right_peak_x, int(round(detection["right_y"]))), 4, (0, 128, 255), -1)

    status_text = "VALID" if detection["valid"] else "INVALID"
    status_color = (0, 200, 0) if detection["valid"] else (0, 0, 255)
    text_lines = [
        f"frame={frame_index} t={stamp_sec:.3f}s {status_text} report={'Y' if detection['accept_for_peak_report'] else 'N'}",
        "thr={} cols={} fit_pts={} conf={:.2f}".format(
            detection["threshold_value"],
            detection["valid_columns"],
            detection["fit_points"],
            detection["confidence"],
        ),
    ]
    if detection["peak_rel_px"] is not None:
        text_lines.append(
            "left_rel_px={:.1f} right_rel_px={:.1f} peak_rel_px={:.1f}".format(
                detection["left_rel_px"],
                detection["right_rel_px"],
                detection["peak_rel_px"],
            )
        )
    if detection["peak_rel_px_signed"] is not None:
        text_lines.append(
            "signed left={:.1f} right={:.1f} peak={:.1f} src={}".format(
                detection["left_rel_px_signed"],
                detection["right_rel_px_signed"],
                detection["peak_rel_px_signed"],
                detection["peak_source"],
            )
        )
    if detection["fit_rms_px"] is not None and detection["fit_slope"] is not None:
        text_lines.append(
            "fit_rms_px={:.2f} slope={:.3f} cov={:.2f} span={:.2f}".format(
                detection["fit_rms_px"],
                detection["fit_slope"],
                detection["central_coverage"],
                detection["peak_body_span_ratio"],
            )
        )
    if detection["temporal_jump_px"] is not None:
        text_lines.append(
            "jump_px={:.2f} gate={} body_rej={} blend={}".format(
                detection["temporal_jump_px"],
                "ok" if detection["temporal_gate_passed"] else "reject",
                detection["body_span_rejected_columns"],
                detection["blended_columns"],
            )
        )
    else:
        text_lines.append(
            "body_rej={} prim={} edge={} blend={}".format(
                detection["body_span_rejected_columns"],
                detection["primary_selected_columns"],
                detection["edge_selected_columns"],
                detection["blended_columns"],
            )
        )
    if detection["peak_distance_to_top_px"] is not None:
        text_lines.append(
            "peak_top_margin={:.1f}px rot={:.2f}deg".format(
                detection["peak_distance_to_top_px"],
                calibration.rotation_deg,
            )
        )
    if (
        detection["peak_local_support_ratio"] is not None
        or detection["peak_local_rms_px"] is not None
        or detection["peak_edge_dominance"] is not None
    ):
        text_lines.append(
            "peak_local support={:.2f} rms={:.2f} edge_dom={:.2f}".format(
                0.0 if detection["peak_local_support_ratio"] is None else detection["peak_local_support_ratio"],
                0.0 if detection["peak_local_rms_px"] is None else detection["peak_local_rms_px"],
                0.0 if detection["peak_edge_dominance"] is None else detection["peak_edge_dominance"],
            )
        )
    text_lines.append(
        "band_support L={:.2f}({}) R={:.2f}({})".format(
            detection["left_band_support_ratio"],
            detection["left_band_valid_columns"],
            detection["right_band_support_ratio"],
            detection["right_band_valid_columns"],
        )
    )

    y_text = 18
    for idx, line in enumerate(text_lines):
        color = status_color if idx == 0 else (255, 255, 255)
        cv2.putText(canvas, line, (6, y_text), cv2.FONT_HERSHEY_SIMPLEX, 0.45, color, 1, cv2.LINE_AA)
        y_text += 18

    return canvas


def open_video_writer(path: Path, frame_size: Tuple[int, int], fps: float) -> Optional[cv2.VideoWriter]:
    fourcc_candidates = ["mp4v", "avc1", "MJPG"]
    for fourcc_name in fourcc_candidates:
        writer = cv2.VideoWriter(str(path), cv2.VideoWriter_fourcc(*fourcc_name), fps, frame_size)
        if writer.isOpened():
            return writer
        writer.release()
    return None


def csv_value(value: Optional[float], digits: int = 6):
    if value is None:
        return ""
    if isinstance(value, (int, np.integer)):
        return int(value)
    if isinstance(value, (float, np.floating)):
        return f"{float(value):.{digits}f}"
    return value


def summarize_values(values: List[float], stat: str) -> Optional[float]:
    if not values:
        return None
    data = np.asarray(values, dtype=np.float32)
    if stat == "mean":
        return float(np.mean(data))
    return float(np.median(data))


def baseline_measurement_from_detection(detection: Dict, target: str) -> Tuple[Optional[float], Optional[float]]:
    mapping = {
        "peak": ("peak_y", "peak_rel_px_signed"),
        "center": ("center_y", "center_rel_px_signed"),
        "left": ("left_y", "left_rel_px_signed"),
        "right": ("right_y", "right_rel_px_signed"),
    }
    y_key, rel_key = mapping[target]
    return detection.get(y_key), detection.get(rel_key)


def write_adjusted_calibration_yaml(
    input_calibration_path: Path,
    output_path: Path,
    suggested_still_level_px: float,
    baseline_target: str,
    baseline_target_rel_px: float,
    baseline_frame_count: int,
    baseline_stat: str,
):
    data = load_yaml(input_calibration_path)
    calibration = data.setdefault("calibration", {})
    previous_still = float(calibration.get("still_level_px", suggested_still_level_px))
    calibration["still_level_px"] = float(suggested_still_level_px)

    geometry_roi = data.get("geometry_roi", {})
    still_line = geometry_roi.get("still_level_line")
    if isinstance(still_line, list) and len(still_line) == 2:
        delta = float(suggested_still_level_px) - previous_still
        geometry_roi["still_level_line"] = [
            [float(still_line[0][0]), float(still_line[0][1]) + delta],
            [float(still_line[1][0]), float(still_line[1][1]) + delta],
        ]
        data["geometry_roi"] = geometry_roi

    auto_zero = data.setdefault("auto_zero_baseline", {})
    auto_zero["applied"] = True
    auto_zero["source_calibration"] = str(input_calibration_path)
    auto_zero["baseline_target"] = baseline_target
    auto_zero["baseline_stat"] = baseline_stat
    auto_zero["baseline_frame_count"] = int(baseline_frame_count)
    auto_zero["baseline_target_rel_px"] = float(baseline_target_rel_px)
    auto_zero["suggested_still_level_px"] = float(suggested_still_level_px)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as stream:
        yaml.safe_dump(data, stream, sort_keys=False, allow_unicode=False)


def generate_peak_curve_plot(
    output_path: Path,
    frame_indices: List[int],
    stamp_seconds: List[float],
    peak_rel_px_values: List[Optional[float]],
    confidence_values: List[Optional[float]],
    detection_valid_flags: List[bool],
    reportable_flags: List[bool],
    peak_rel_mm_values: List[Optional[float]],
    include_confidence: bool,
) -> bool:
    if plt is None:
        return False
    if not frame_indices:
        return False

    frames = np.asarray(frame_indices, dtype=np.int32)
    times = np.asarray(stamp_seconds, dtype=np.float64)
    if times.size > 0:
        times = times - times[0]

    peak_rel_px = np.asarray([np.nan if value is None else float(value) for value in peak_rel_px_values], dtype=np.float32)
    confidence = np.asarray([np.nan if value is None else float(value) for value in confidence_values], dtype=np.float32)
    detection_valid = np.asarray(detection_valid_flags, dtype=bool)
    reportable = np.asarray(reportable_flags, dtype=bool)
    peak_rel_mm = np.asarray([np.nan if value is None else float(value) for value in peak_rel_mm_values], dtype=np.float32)

    if include_confidence:
        fig, axes = plt.subplots(2, 1, figsize=(12, 7), sharex=True)
        ax_curve, ax_conf = axes
    else:
        fig, ax_curve = plt.subplots(1, 1, figsize=(12, 4.8))
        ax_conf = None

    valid_plot_mask = detection_valid & np.isfinite(peak_rel_px)
    reportable_plot_mask = reportable & np.isfinite(peak_rel_px)
    withheld_plot_mask = valid_plot_mask & ~reportable_plot_mask

    if np.any(valid_plot_mask):
        ax_curve.plot(
            frames[valid_plot_mask],
            peak_rel_px[valid_plot_mask],
            color="#b0bec5",
            linewidth=1.0,
            alpha=0.8,
            label="valid peak_rel_px",
        )
    if np.any(reportable_plot_mask):
        ax_curve.plot(
            frames[reportable_plot_mask],
            peak_rel_px[reportable_plot_mask],
            color="#90caf9",
            linewidth=1.2,
            alpha=0.90,
            label="reported peak_rel_px",
        )

    scatter = None
    if np.any(reportable_plot_mask):
        scatter = ax_curve.scatter(
            frames[reportable_plot_mask],
            peak_rel_px[reportable_plot_mask],
            c=confidence[reportable_plot_mask],
            cmap="viridis",
            vmin=0.0,
            vmax=1.0,
            s=16,
            linewidths=0.0,
            label="reported point (colored by confidence)",
        )
    if np.any(withheld_plot_mask):
        ax_curve.scatter(
            frames[withheld_plot_mask],
            peak_rel_px[withheld_plot_mask],
            color="#9e9e9e",
            s=10,
            marker="x",
            alpha=0.6,
            label="valid but not reportable",
        )

    if np.any(np.isfinite(peak_rel_mm)):
        ax_curve_mm = ax_curve.twinx()
        ax_curve_mm.plot(
            frames[reportable & np.isfinite(peak_rel_mm)],
            peak_rel_mm[reportable & np.isfinite(peak_rel_mm)],
            color="#2e7d32",
            linewidth=1.0,
            alpha=0.55,
            label="reported peak_rel_mm",
        )
        ax_curve_mm.set_ylabel("peak_rel_mm")

    ax_curve.axhline(0.0, color="#616161", linewidth=1.0, linestyle="--")
    ax_curve.set_title("Highest Liquid Height Per Frame")
    ax_curve.set_ylabel("peak_rel_px")
    ax_curve.grid(True, linestyle="--", alpha=0.25)
    ax_curve.legend(loc="upper right")

    if scatter is not None:
        cbar = fig.colorbar(scatter, ax=ax_curve, pad=0.02)
        cbar.set_label("meniscus_confidence")

        max_idx = np.nanargmax(np.where(reportable_plot_mask, peak_rel_px, np.nan))
        peak_x = frames[max_idx]
        peak_y = peak_rel_px[max_idx]
        peak_conf = confidence[max_idx]
        ax_curve.annotate(
            f"peak={peak_y:.2f}px\nconf={peak_conf:.2f}",
            xy=(peak_x, peak_y),
            xytext=(10, 10),
            textcoords="offset points",
            fontsize=8,
            color="#263238",
            bbox=dict(boxstyle="round,pad=0.2", fc="white", ec="#90a4ae", alpha=0.9),
            arrowprops=dict(arrowstyle="->", color="#607d8b", lw=0.8),
        )

    if ax_conf is not None:
        ax_conf.plot(frames, confidence, color="#6a1b9a", linewidth=1.2, label="meniscus_confidence")
        ax_conf.set_xlabel("frame_index")
        ax_conf.set_ylabel("confidence")
        ax_conf.set_ylim(-0.05, 1.05)
        ax_conf.grid(True, linestyle="--", alpha=0.25)
        ax_conf.legend(loc="upper right")
    else:
        ax_curve.set_xlabel("frame_index")

    if times.size == frames.size and frames.size > 1:
        tick_indices = np.linspace(0, frames.size - 1, num=min(6, frames.size), dtype=int)
        tick_frames = frames[tick_indices]
        tick_labels = [f"{times[idx]:.1f}s" for idx in tick_indices]
        ax_top = ax_curve.twiny()
        ax_top.set_xlim(ax_curve.get_xlim())
        ax_top.set_xticks(tick_frames)
        ax_top.set_xticklabels(tick_labels)
        ax_top.set_xlabel("relative time")

    fig.tight_layout()
    fig.savefig(str(output_path), dpi=160)
    plt.close(fig)
    return True


def main():
    args = parse_args()
    bag_path = Path(args.bag).expanduser().resolve()
    calibration_path = Path(args.calibration).expanduser().resolve()
    config_path = Path(args.config).expanduser().resolve() if args.config else script_default_config()

    if not bag_path.exists():
        print(f"[ERROR] bag not found: {bag_path}", file=sys.stderr)
        return 1
    if not calibration_path.exists():
        print(f"[ERROR] calibration yaml not found: {calibration_path}", file=sys.stderr)
        return 2

    try:
        calibration = load_calibration(calibration_path)
    except Exception as exc:  # pylint: disable=broad-except
        print(f"[ERROR] failed to load calibration: {exc}", file=sys.stderr)
        return 3

    _, processing = load_processing_config(config_path if config_path.exists() else None)
    if args.threshold_bias is not None:
        processing.threshold_bias = int(args.threshold_bias)
    if args.blur_kernel is not None:
        processing.blur_kernel = int(args.blur_kernel)
    if args.no_clahe:
        processing.use_clahe = False
    if args.no_edge_fallback:
        processing.use_edge_fallback = False

    output_dir = Path(args.out_dir).expanduser().resolve() if args.out_dir else default_output_dir(bag_path)
    ensure_output_dir(output_dir)

    bridge = CvBridge()
    image_topic = args.image_topic
    csv_path = output_dir / "liquid_height.csv"
    debug_video_path = output_dir / "liquid_debug.mp4"
    plot_path = output_dir / "liquid_height_peak_curve.png"

    processed_frames = 0
    valid_frames = 0
    reportable_frames = 0
    max_peak_rel_px = None
    max_reported_peak_rel_px = None
    writer = None
    previous_state: Optional[TemporalState] = None
    baseline_target_y_samples: List[float] = []
    baseline_target_rel_px_samples: List[float] = []
    plot_frame_indices: List[int] = []
    plot_stamp_seconds: List[float] = []
    plot_peak_rel_px_values: List[Optional[float]] = []
    plot_peak_rel_mm_values: List[Optional[float]] = []
    plot_confidence_values: List[Optional[float]] = []
    plot_detection_valid_flags: List[bool] = []
    plot_reportable_flags: List[bool] = []

    with rosbag.Bag(str(bag_path), "r") as bag:
        image_topics = image_topics_in_bag(bag)
        if not image_topic:
            try:
                config_dict = load_yaml(config_path) if config_path.exists() else {}
            except Exception:  # pylint: disable=broad-except
                config_dict = {}
            image_topic = str(config_dict.get("topic_image", "/camera/color/image_raw"))

        if image_topic not in image_topics:
            print(f"[ERROR] topic not found in bag: {image_topic}", file=sys.stderr)
            print("[INFO] available image topics:", file=sys.stderr)
            for topic in image_topics:
                print(f"  - {topic}", file=sys.stderr)
            return 4

        bag_start = bag.get_start_time()
        min_stamp = bag_start + max(args.time_offset, 0.0)

        with csv_path.open("w", newline="", encoding="utf-8") as csv_file:
            writer_csv = csv.writer(csv_file)
            writer_csv.writerow(
                [
                    "frame_index",
                    "stamp",
                    "valid",
                    "meniscus_confidence",
                    "threshold_value",
                    "valid_columns",
                    "central_valid_columns",
                    "central_coverage",
                    "fit_points",
                    "fit_rms_px",
                    "fit_slope",
                    "temporal_jump_px",
                    "temporal_gate_passed",
                    "temporal_rejected_columns",
                    "temporal_recovered_columns",
                    "body_span_rejected_columns",
                    "primary_selected_columns",
                    "edge_selected_columns",
                    "blended_columns",
                    "peak_distance_to_top_px",
                    "peak_body_span_ratio",
                    "peak_local_support_ratio",
                    "peak_local_rms_px",
                    "peak_edge_dominance",
                    "accept_for_peak_report",
                    "left_peak_source",
                    "right_peak_source",
                    "peak_source",
                    "left_band_support_ratio",
                    "right_band_support_ratio",
                    "left_band_valid_columns",
                    "right_band_valid_columns",
                    "height_left_px",
                    "height_right_px",
                    "height_peak_px",
                    "height_left_rel_px_signed",
                    "height_right_rel_px_signed",
                    "height_peak_rel_px_signed",
                    "height_left_rel_px",
                    "height_right_rel_px",
                    "height_peak_rel_px",
                    "height_left_rel_mm_signed",
                    "height_right_rel_mm_signed",
                    "height_peak_rel_mm_signed",
                    "height_left_rel_mm",
                    "height_right_rel_mm",
                    "height_peak_rel_mm",
                ]
            )

            image_counter = 0
            for _, msg, stamp in bag.read_messages(topics=[image_topic]):
                stamp_sec = stamp.to_sec()
                if stamp_sec < min_stamp:
                    continue
                if image_counter % max(args.every, 1) != 0:
                    image_counter += 1
                    continue
                if args.max_frames > 0 and processed_frames >= args.max_frames:
                    break

                try:
                    image = bridge.imgmsg_to_cv2(msg, desired_encoding=args.encoding)
                except CvBridgeError as exc:
                    print(f"[WARN] skip frame {image_counter}: {exc}", file=sys.stderr)
                    image_counter += 1
                    continue

                y0 = calibration.roi_y
                y1 = calibration.roi_y + calibration.roi_h
                x0 = calibration.roi_x
                x1 = calibration.roi_x + calibration.roi_w
                if y0 < 0 or x0 < 0 or y1 > image.shape[0] or x1 > image.shape[1]:
                    print(
                        f"[ERROR] calibration ROI exceeds frame bounds at frame {image_counter}.",
                        file=sys.stderr,
                    )
                    return 5

                roi_bgr = image[y0:y1, x0:x1].copy()
                rectified_roi_bgr, rectified_calibration = rectify_roi_and_calibration(roi_bgr, calibration)
                detection = detect_liquid_profile(
                    rectified_roi_bgr,
                    rectified_calibration,
                    processing,
                    previous_state=previous_state,
                )

                if detection["valid"]:
                    valid_frames += 1
                    if max_peak_rel_px is None or detection["peak_rel_px"] > max_peak_rel_px:
                        max_peak_rel_px = detection["peak_rel_px"]
                    if (
                        args.auto_zero_baseline
                        and len(baseline_target_y_samples) < max(1, args.baseline_frame_count)
                    ):
                        target_y, target_rel_px = baseline_measurement_from_detection(detection, args.baseline_target)
                        if target_y is not None and target_rel_px is not None:
                            baseline_target_y_samples.append(float(target_y))
                            baseline_target_rel_px_samples.append(float(target_rel_px))
                    new_state = build_temporal_state(detection)
                    if new_state is not None:
                        previous_state = new_state
                if detection["accept_for_peak_report"]:
                    reportable_frames += 1
                    if max_reported_peak_rel_px is None or detection["peak_rel_px"] > max_reported_peak_rel_px:
                        max_reported_peak_rel_px = detection["peak_rel_px"]

                left_rel_mm_signed = maybe_mm(detection["left_rel_px_signed"], calibration.mm_per_pixel)
                right_rel_mm_signed = maybe_mm(detection["right_rel_px_signed"], calibration.mm_per_pixel)
                peak_rel_mm_signed = maybe_mm(detection["peak_rel_px_signed"], calibration.mm_per_pixel)
                left_rel_mm = maybe_mm(detection["left_rel_px"], calibration.mm_per_pixel)
                right_rel_mm = maybe_mm(detection["right_rel_px"], calibration.mm_per_pixel)
                peak_rel_mm = maybe_mm(detection["peak_rel_px"], calibration.mm_per_pixel)

                writer_csv.writerow(
                    [
                        image_counter,
                        f"{stamp_sec:.9f}",
                        int(detection["valid"]),
                        csv_value(detection["confidence"]),
                        detection["threshold_value"],
                        detection["valid_columns"],
                        detection["central_valid_columns"],
                        csv_value(detection["central_coverage"]),
                        detection["fit_points"],
                        csv_value(detection["fit_rms_px"]),
                        csv_value(detection["fit_slope"]),
                        csv_value(detection["temporal_jump_px"]),
                        int(detection["temporal_gate_passed"]),
                        detection["temporal_rejected_columns"],
                        detection["temporal_recovered_columns"],
                        detection["body_span_rejected_columns"],
                        detection["primary_selected_columns"],
                        detection["edge_selected_columns"],
                        detection["blended_columns"],
                        csv_value(detection["peak_distance_to_top_px"]),
                        csv_value(detection["peak_body_span_ratio"]),
                        csv_value(detection["peak_local_support_ratio"]),
                        csv_value(detection["peak_local_rms_px"]),
                        csv_value(detection["peak_edge_dominance"]),
                        int(detection["accept_for_peak_report"]),
                        detection["left_peak_source"],
                        detection["right_peak_source"],
                        detection["peak_source"],
                        csv_value(detection["left_band_support_ratio"]),
                        csv_value(detection["right_band_support_ratio"]),
                        detection["left_band_valid_columns"],
                        detection["right_band_valid_columns"],
                        csv_value(detection["left_y"]),
                        csv_value(detection["right_y"]),
                        csv_value(detection["peak_y"]),
                        csv_value(detection["left_rel_px_signed"]),
                        csv_value(detection["right_rel_px_signed"]),
                        csv_value(detection["peak_rel_px_signed"]),
                        csv_value(detection["left_rel_px"]),
                        csv_value(detection["right_rel_px"]),
                        csv_value(detection["peak_rel_px"]),
                        csv_value(left_rel_mm_signed),
                        csv_value(right_rel_mm_signed),
                        csv_value(peak_rel_mm_signed),
                        csv_value(left_rel_mm),
                        csv_value(right_rel_mm),
                        csv_value(peak_rel_mm),
                    ]
                )

                plot_frame_indices.append(int(image_counter))
                plot_stamp_seconds.append(float(stamp_sec))
                plot_peak_rel_px_values.append(None if detection["peak_rel_px"] is None else float(detection["peak_rel_px"]))
                plot_peak_rel_mm_values.append(None if peak_rel_mm is None else float(peak_rel_mm))
                plot_confidence_values.append(float(detection["confidence"]))
                plot_detection_valid_flags.append(bool(detection["valid"]))
                plot_reportable_flags.append(bool(detection["accept_for_peak_report"]))

                if not args.skip_debug_video:
                    debug_frame = make_debug_frame(rectified_roi_bgr, rectified_calibration, image_counter, stamp_sec, detection)
                    if writer is None:
                        writer = open_video_writer(
                            debug_video_path,
                            (debug_frame.shape[1], debug_frame.shape[0]),
                            max(1.0, float(args.debug_fps)),
                        )
                        if writer is None:
                            print(
                                f"[WARN] failed to open debug video writer: {debug_video_path}. "
                                "Continuing without debug video.",
                                file=sys.stderr,
                            )
                            args.skip_debug_video = True
                    if writer is not None:
                        writer.write(debug_frame)

                processed_frames += 1
                image_counter += 1

    if writer is not None:
        writer.release()

    if processed_frames == 0:
        print("[WARN] no frames processed. Check topic/time-offset/every/max-frames.", file=sys.stderr)
        return 6

    valid_ratio = valid_frames / float(processed_frames)
    print(f"[OK] processed frames: {processed_frames}")
    print(f"[OK] valid frames: {valid_frames} ({valid_ratio:.1%})")
    print(f"[OK] reportable peak frames: {reportable_frames}")
    if max_peak_rel_px is not None:
        print(f"[OK] max height_peak_rel_px: {max_peak_rel_px:.3f}")
    else:
        print("[WARN] no valid peak height detected.")
    if max_reported_peak_rel_px is not None:
        print(f"[OK] max reported height_peak_rel_px: {max_reported_peak_rel_px:.3f}")
    print(f"[OK] csv: {csv_path}")
    if not args.skip_debug_video and debug_video_path.exists():
        print(f"[OK] debug video: {debug_video_path}")
    if not args.skip_plot:
        if generate_peak_curve_plot(
            plot_path,
            plot_frame_indices,
            plot_stamp_seconds,
            plot_peak_rel_px_values,
            plot_confidence_values,
            plot_detection_valid_flags,
            plot_reportable_flags,
            plot_peak_rel_mm_values,
            args.plot_confidence,
        ):
            print(f"[OK] peak curve plot: {plot_path}")
        else:
            print("[WARN] failed to generate peak curve plot.")
    if calibration.mm_per_pixel is None:
        print("[INFO] calibration.mm_per_pixel is null, so *_rel_mm columns are left empty.")

    if args.auto_zero_baseline:
        baseline_target_y = summarize_values(baseline_target_y_samples, args.baseline_stat)
        baseline_target_rel_px = summarize_values(baseline_target_rel_px_samples, args.baseline_stat)
        if baseline_target_y is None or baseline_target_rel_px is None:
            print("[WARN] auto-zero baseline requested, but no valid baseline samples were collected.")
        else:
            suggested_still_level_px = baseline_target_y
            adjusted_path = (
                Path(args.write_adjusted_calibration).expanduser().resolve()
                if args.write_adjusted_calibration
                else default_adjusted_calibration_path(calibration_path)
            )
            write_adjusted_calibration_yaml(
                calibration_path,
                adjusted_path,
                suggested_still_level_px=suggested_still_level_px,
                baseline_target=args.baseline_target,
                baseline_target_rel_px=baseline_target_rel_px,
                baseline_frame_count=len(baseline_target_y_samples),
                baseline_stat=args.baseline_stat,
            )
            print(
                "[OK] auto-zero baseline: used {} valid frame(s), {}_rel_px={} ({})".format(
                    len(baseline_target_y_samples),
                    args.baseline_target,
                    f"{baseline_target_rel_px:.6f}",
                    args.baseline_stat,
                )
            )
            print(f"[OK] suggested calibration.still_level_px: {suggested_still_level_px:.6f}")
            print(f"[OK] adjusted calibration yaml: {adjusted_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
