#!/usr/bin/env python3
"""Extract v2 liquid-height time series using piecewise-linear multiscale calibration."""

import argparse
import csv
import math
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import cv2
import numpy as np
import rosbag
from cv_bridge import CvBridge, CvBridgeError

try:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
except Exception:  # pylint: disable=broad-except
    plt = None

from extract_liquid_height_from_bag import (
    Calibration as LegacyCalibration,
    ProcessingConfig,
    TemporalState,
    build_temporal_state,
    copy_calibration_with_geometry,
    csv_value,
    detect_liquid_profile,
    ensure_output_dir,
    evaluate_line_y_from_points,
    image_topics_in_bag,
    load_processing_config,
    load_yaml,
    make_debug_frame,
    make_horizontal_line,
    make_vertical_line,
    open_video_writer,
    parse_line_points,
    rectify_roi_and_calibration,
)


@dataclass
class ReferencePoint:
    x_px: float
    y_px: float
    h_mm: float


@dataclass
class HeightMappingResult:
    h_mm: Optional[float]
    segment_id: Optional[int]
    extrapolated: bool


@dataclass
class V2Calibration:
    legacy: LegacyCalibration
    reference_points: List[ReferencePoint]
    mapping_mode: str
    mapping_coordinate_frame: str
    height_zero_definition: str
    x_usage: str
    ruler_click_semantics: str
    physical_ruler_zero_mm: float
    zero_y_rect: float


@dataclass
class V2GateDecision:
    valid: bool
    accept_for_peak_report: bool
    legacy_valid: bool
    legacy_accept_for_peak_report: bool


def parse_args():
    parser = argparse.ArgumentParser(
        description="Extract v2 liquid-height time series from a rosbag using multiscale ruler calibration."
    )
    parser.add_argument("--bag", required=True, help="Path to the rosbag file.")
    parser.add_argument(
        "--calibration",
        required=True,
        help="Path to the frame_XXXXXX_multiscale_raw.yaml generated by annotate_height_ruler_v2.py.",
    )
    parser.add_argument(
        "--config",
        default="",
        help="Optional package config YAML. Used only for processing defaults.",
    )
    parser.add_argument(
        "--image-topic",
        default="",
        help="RGB image topic. Defaults to config topic_image or /camera/color/image_raw.",
    )
    parser.add_argument(
        "--out-dir",
        default="",
        help="Output directory. Defaults to <bag_stem>_liquid_measurement_v2 next to the bag.",
    )
    parser.add_argument(
        "--encoding",
        default="bgr8",
        help="Desired OpenCV encoding passed to cv_bridge.",
    )
    parser.add_argument(
        "--time-offset",
        type=float,
        default=0.0,
        help="Skip frames before bag_start + time_offset seconds.",
    )
    parser.add_argument(
        "--max-frames",
        type=int,
        default=0,
        help="Maximum number of frames to process after filtering. 0 means all frames.",
    )
    parser.add_argument(
        "--every",
        type=int,
        default=1,
        help="Process every N-th frame after time filtering.",
    )
    parser.add_argument(
        "--debug-fps",
        type=float,
        default=10.0,
        help="FPS for the debug video writer.",
    )
    parser.add_argument(
        "--skip-debug-video",
        action="store_true",
        help="Skip debug video generation and write CSV only.",
    )
    parser.add_argument(
        "--skip-plot",
        action="store_true",
        help="Skip summary plot generation and write CSV/debug video only.",
    )
    parser.add_argument(
        "--plot-confidence",
        action="store_true",
        help="Add a second subplot for meniscus_confidence under the peak-height curve.",
    )
    parser.add_argument(
        "--threshold-bias",
        type=int,
        default=None,
        help="Override threshold bias in intensity units.",
    )
    parser.add_argument(
        "--blur-kernel",
        type=int,
        default=None,
        help="Override Gaussian blur kernel size.",
    )
    parser.add_argument(
        "--no-clahe",
        action="store_true",
        help="Disable CLAHE even if config enables it.",
    )
    parser.add_argument(
        "--no-edge-fallback",
        action="store_true",
        help="Disable Sobel-Y fallback when threshold detection misses columns.",
    )
    parser.add_argument(
        "--center-bias-correction-mm",
        type=float,
        default=None,
        help="Optional constant bias correction for center height in mm. Defaults to config postprocess.center_bias_correction_mm.",
    )
    return parser.parse_args()


def default_output_dir(bag_path: Path) -> Path:
    return bag_path.parent / f"{bag_path.stem}_liquid_measurement_v2"


def v2_default_config() -> Path:
    return Path(__file__).resolve().parents[1] / "config" / "liquid_measurement_v2.yaml"


def csv_optional_int(value: Optional[int]) -> str:
    if value is None:
        return ""
    return str(int(value))


def parse_reference_point(raw_value: Dict, index: int) -> ReferencePoint:
    for key in ("x_px", "y_px", "h_mm"):
        if key not in raw_value:
            raise ValueError(f"missing height_mapping.reference_points[{index}].{key}")
    return ReferencePoint(
        x_px=float(raw_value["x_px"]),
        y_px=float(raw_value["y_px"]),
        h_mm=float(raw_value["h_mm"]),
    )


def validate_reference_points(reference_points: Sequence[ReferencePoint]):
    if len(reference_points) < 2:
        raise ValueError("height_mapping.reference_points must contain at least two points")

    for index, point in enumerate(reference_points):
        if not np.isfinite(point.x_px) or not np.isfinite(point.y_px) or not np.isfinite(point.h_mm):
            raise ValueError(f"height_mapping.reference_points[{index}] contains a non-finite value")

    for index in range(len(reference_points) - 1):
        current_point = reference_points[index]
        next_point = reference_points[index + 1]
        if next_point.h_mm <= current_point.h_mm:
            raise ValueError("height_mapping.reference_points[*].h_mm must be strictly increasing")
        if next_point.y_px >= current_point.y_px:
            raise ValueError(
                "height_mapping.reference_points[*].y_px must strictly decrease as h_mm increases"
            )


def evaluate_y_at_height(reference_points: Sequence[ReferencePoint], target_h_mm: float) -> float:
    if len(reference_points) < 2:
        raise ValueError("need at least two reference points to evaluate y at a target height")

    if target_h_mm <= reference_points[0].h_mm:
        first = reference_points[0]
        second = reference_points[1]
        return interpolate_y_from_h(first, second, target_h_mm)
    if target_h_mm >= reference_points[-1].h_mm:
        first = reference_points[-2]
        second = reference_points[-1]
        return interpolate_y_from_h(first, second, target_h_mm)

    for index in range(len(reference_points) - 1):
        first = reference_points[index]
        second = reference_points[index + 1]
        if first.h_mm <= target_h_mm <= second.h_mm:
            return interpolate_y_from_h(first, second, target_h_mm)

    raise RuntimeError("failed to locate target height inside reference point range")


def interpolate_y_from_h(first: ReferencePoint, second: ReferencePoint, target_h_mm: float) -> float:
    if abs(second.h_mm - first.h_mm) < 1e-9:
        raise ValueError("reference point heights must not repeat")
    alpha = (float(target_h_mm) - float(first.h_mm)) / float(second.h_mm - first.h_mm)
    return float(first.y_px + alpha * (second.y_px - first.y_px))


def evaluate_height_mapping(reference_points: Sequence[ReferencePoint], y_px: Optional[float]) -> HeightMappingResult:
    if y_px is None or not np.isfinite(y_px):
        return HeightMappingResult(h_mm=None, segment_id=None, extrapolated=False)
    if len(reference_points) < 2:
        raise ValueError("need at least two reference points to evaluate piecewise-linear mapping")

    y_value = float(y_px)
    if y_value >= reference_points[0].y_px:
        segment_id = 0
        first = reference_points[0]
        second = reference_points[1]
        return HeightMappingResult(
            h_mm=interpolate_h_from_y(first, second, y_value),
            segment_id=segment_id,
            extrapolated=True,
        )
    if y_value <= reference_points[-1].y_px:
        segment_id = len(reference_points) - 2
        first = reference_points[-2]
        second = reference_points[-1]
        return HeightMappingResult(
            h_mm=interpolate_h_from_y(first, second, y_value),
            segment_id=segment_id,
            extrapolated=True,
        )

    for segment_id in range(len(reference_points) - 1):
        first = reference_points[segment_id]
        second = reference_points[segment_id + 1]
        if first.y_px >= y_value >= second.y_px:
            return HeightMappingResult(
                h_mm=interpolate_h_from_y(first, second, y_value),
                segment_id=segment_id,
                extrapolated=False,
            )

    raise RuntimeError("failed to locate y inside reference point range")


def interpolate_h_from_y(first: ReferencePoint, second: ReferencePoint, y_px: float) -> float:
    if abs(second.y_px - first.y_px) < 1e-9:
        raise ValueError("reference point y_px must not repeat")
    alpha = (float(y_px) - float(first.y_px)) / float(second.y_px - first.y_px)
    return float(first.h_mm + alpha * (second.h_mm - first.h_mm))


def load_v2_calibration(path: Path) -> V2Calibration:
    data = load_yaml(path)
    roi = data.get("roi", {})
    tube_inner = data.get("tube_inner", {})
    geometry_roi = data.get("geometry_roi", {})
    source = data.get("source", {})
    height_mapping = data.get("height_mapping", {})

    for key in ("x", "y", "w", "h"):
        if key not in roi:
            raise ValueError(f"missing roi.{key} in {path}")
    for key in ("x_left", "x_right"):
        if key not in tube_inner:
            raise ValueError(f"missing tube_inner.{key} in {path}")
    for key in ("mode", "height_zero_definition", "mapping_coordinate_frame", "reference_points"):
        if key not in height_mapping:
            raise ValueError(f"missing height_mapping.{key} in {path}")

    mapping_mode = str(height_mapping["mode"])
    if mapping_mode != "piecewise_linear":
        raise ValueError(f"unsupported height_mapping.mode: {mapping_mode}")

    height_zero_definition = str(height_mapping["height_zero_definition"])
    if height_zero_definition != "still_level_reference":
        raise ValueError(
            "height_mapping.height_zero_definition must be still_level_reference for v2 mainline"
        )

    mapping_coordinate_frame = str(height_mapping["mapping_coordinate_frame"])
    if mapping_coordinate_frame != "rectified_roi":
        raise ValueError(
            "height_mapping.mapping_coordinate_frame must be rectified_roi for v2 mainline"
        )

    x_usage = str(height_mapping.get("x_usage", "record_only"))
    if x_usage != "record_only":
        raise ValueError("height_mapping.x_usage must be record_only in v1")

    ruler_click_semantics = str(height_mapping.get("ruler_click_semantics", "line_center"))
    if ruler_click_semantics != "line_center":
        raise ValueError("height_mapping.ruler_click_semantics must be line_center in v1")

    roi_w = int(roi["w"])
    roi_h = int(roi["h"])
    x_left = int(tube_inner["x_left"])
    x_right = int(tube_inner["x_right"])

    left_wall_line = parse_line_points(
        geometry_roi.get("left_wall_line", make_vertical_line(x_left, roi_h)),
        "geometry_roi.left_wall_line",
    )
    right_wall_line = parse_line_points(
        geometry_roi.get("right_wall_line", make_vertical_line(x_right, roi_h)),
        "geometry_roi.right_wall_line",
    )
    default_still_level_y = 0.5 * float(roi_h - 1)
    still_level_line = parse_line_points(
        geometry_roi.get("still_level_line", make_horizontal_line(default_still_level_y, roi_w)),
        "geometry_roi.still_level_line",
    )
    default_axis_x = 0.5 * (x_left + x_right)
    tube_axis_line = parse_line_points(
        geometry_roi.get("tube_axis_line", make_vertical_line(default_axis_x, roi_h)),
        "geometry_roi.tube_axis_line",
    )
    center_x = 0.5 * (x_left + x_right)
    still_level_px = evaluate_line_y_from_points(still_level_line, center_x)

    legacy = LegacyCalibration(
        roi_x=int(roi["x"]),
        roi_y=int(roi["y"]),
        roi_w=roi_w,
        roi_h=roi_h,
        x_left=x_left,
        x_right=x_right,
        still_level_px=float(still_level_px),
        mm_per_pixel=None,
        mode=str(source.get("mode", "multiscale_ruler")),
        left_wall_line=np.asarray(left_wall_line, dtype=np.float32),
        right_wall_line=np.asarray(right_wall_line, dtype=np.float32),
        still_level_line=np.asarray(still_level_line, dtype=np.float32),
        tube_axis_line=np.asarray(tube_axis_line, dtype=np.float32),
    )
    legacy = copy_calibration_with_geometry(
        legacy,
        legacy.left_wall_line,
        legacy.right_wall_line,
        legacy.still_level_line,
        legacy.tube_axis_line,
        legacy.rotation_deg,
    )

    reference_points_raw = height_mapping.get("reference_points", [])
    if not isinstance(reference_points_raw, list):
        raise ValueError("height_mapping.reference_points must be a list")
    reference_points = [parse_reference_point(point, index) for index, point in enumerate(reference_points_raw)]
    validate_reference_points(reference_points)

    zero_y_rect = evaluate_y_at_height(reference_points, 0.0)

    return V2Calibration(
        legacy=legacy,
        reference_points=reference_points,
        mapping_mode=mapping_mode,
        mapping_coordinate_frame=mapping_coordinate_frame,
        height_zero_definition=height_zero_definition,
        x_usage=x_usage,
        ruler_click_semantics=ruler_click_semantics,
        physical_ruler_zero_mm=float(height_mapping.get("physical_ruler_zero_mm", 0.0)),
        zero_y_rect=float(zero_y_rect),
    )


def compute_rectification_matrix(calibration: LegacyCalibration) -> Tuple[np.ndarray, float]:
    axis = calibration.tube_axis_line
    dx = float(axis[1, 0] - axis[0, 0])
    dy = float(axis[1, 1] - axis[0, 1])
    if abs(dx) < 1e-6 and abs(dy) < 1e-6:
        return np.asarray([[1.0, 0.0, 0.0], [0.0, 1.0, 0.0]], dtype=np.float32), 0.0

    theta_deg = math.degrees(math.atan2(dy, dx))
    rotate_deg = 90.0 - theta_deg
    if abs(rotate_deg) < 1e-4:
        return np.asarray([[1.0, 0.0, 0.0], [0.0, 1.0, 0.0]], dtype=np.float32), 0.0

    center = ((calibration.roi_w - 1) * 0.5, (calibration.roi_h - 1) * 0.5)
    matrix = cv2.getRotationMatrix2D(center, rotate_deg, 1.0)
    return np.asarray(matrix, dtype=np.float32), float(rotate_deg)


def inverse_transform_y(matrix: np.ndarray, x_px: Optional[float], y_px: Optional[float]) -> Optional[float]:
    if x_px is None or y_px is None:
        return None
    if not np.isfinite(x_px) or not np.isfinite(y_px):
        return None

    inverse_matrix = cv2.invertAffineTransform(matrix)
    point = np.asarray([[[float(x_px), float(y_px)]]], dtype=np.float32)
    transformed = cv2.transform(point, inverse_matrix)[0][0]
    return float(transformed[1])


def peak_x_from_detection(detection: Dict) -> Optional[float]:
    peak_source = detection.get("peak_source")
    if not peak_source:
        return None
    if str(peak_source).startswith("left_"):
        value = detection.get("left_peak_x")
    elif str(peak_source).startswith("right_"):
        value = detection.get("right_peak_x")
    else:
        value = None
    if value is None or not np.isfinite(value):
        return None
    return float(value)


def zero_based_rel_px(zero_y_rect: float, target_y_rect: Optional[float]) -> Optional[float]:
    if target_y_rect is None or not np.isfinite(target_y_rect):
        return None
    return float(zero_y_rect - float(target_y_rect))


def positive_only(value: Optional[float]) -> Optional[float]:
    if value is None:
        return None
    return max(0.0, float(value))


def mapping_mm_value(mapping: HeightMappingResult) -> Optional[float]:
    if mapping.h_mm is None:
        return None
    return float(mapping.h_mm)


def finite_float(value) -> Optional[float]:
    if value is None:
        return None
    try:
        parsed = float(value)
    except (TypeError, ValueError):
        return None
    if not np.isfinite(parsed):
        return None
    return parsed


def rectified_y_in_bounds(y_px: Optional[float], roi_h: int) -> bool:
    value = finite_float(y_px)
    if value is None:
        return False
    return -0.5 <= value <= float(roi_h) - 0.5


def evaluate_v2_gates(detection: Dict, processing: ProcessingConfig, roi_h: int) -> V2GateDecision:
    legacy_valid = bool(detection.get("valid"))
    legacy_accept_for_peak_report = bool(detection.get("accept_for_peak_report"))

    fit_points = int(detection.get("fit_points", 0) or 0)
    valid_columns = int(detection.get("valid_columns", 0) or 0)
    fit_rms_px = finite_float(detection.get("fit_rms_px"))
    fit_slope = finite_float(detection.get("fit_slope"))
    confidence = finite_float(detection.get("confidence"))
    coverage = finite_float(detection.get("central_coverage"))
    temporal_jump_px = finite_float(detection.get("temporal_jump_px"))
    peak_distance_to_top_px = finite_float(detection.get("peak_distance_to_top_px"))
    peak_body_span_ratio = finite_float(detection.get("peak_body_span_ratio"))
    peak_local_rms_px = finite_float(detection.get("peak_local_rms_px"))
    temporal_gate_passed = bool(detection.get("temporal_gate_passed"))

    min_fit_points = max(8, int(processing.min_valid_columns) // 2)
    fit_core_valid = (
        valid_columns >= int(processing.min_valid_columns)
        and fit_points >= min_fit_points
        and fit_rms_px is not None
        and fit_rms_px <= float(processing.max_fit_residual_px)
        and fit_slope is not None
        and abs(fit_slope) <= float(processing.max_slope_abs)
        and rectified_y_in_bounds(detection.get("left_y"), roi_h)
        and rectified_y_in_bounds(detection.get("right_y"), roi_h)
        and rectified_y_in_bounds(detection.get("peak_y"), roi_h)
        and temporal_gate_passed
    )

    accept_for_peak_report = (
        fit_core_valid
        and confidence is not None
        and confidence >= float(processing.report_min_confidence)
        and coverage is not None
        and coverage >= float(processing.report_min_central_coverage)
        and fit_rms_px is not None
        and fit_rms_px <= float(processing.report_max_fit_rms_px)
        and peak_distance_to_top_px is not None
        and peak_distance_to_top_px >= float(processing.report_min_peak_distance_to_top_px)
        and peak_body_span_ratio is not None
        and peak_body_span_ratio >= float(processing.report_min_peak_body_span_ratio)
        and (temporal_jump_px is None or temporal_jump_px <= float(processing.report_max_temporal_jump_px))
        and peak_local_rms_px is not None
        and peak_local_rms_px <= float(processing.report_max_peak_local_rms_px)
    )

    return V2GateDecision(
        valid=fit_core_valid,
        accept_for_peak_report=accept_for_peak_report,
        legacy_valid=legacy_valid,
        legacy_accept_for_peak_report=legacy_accept_for_peak_report,
    )


def make_debug_frame_v2(
    roi_bgr: np.ndarray,
    calibration: LegacyCalibration,
    frame_index: int,
    stamp_sec: float,
    detection: Dict,
    gate_decision: V2GateDecision,
    peak_mapping: HeightMappingResult,
    peak_rel_mm: Optional[float],
    center_rel_mm: Optional[float],
) -> np.ndarray:
    debug_detection = dict(detection)
    debug_detection["valid"] = gate_decision.valid
    debug_detection["accept_for_peak_report"] = gate_decision.accept_for_peak_report
    canvas = make_debug_frame(roi_bgr, calibration, frame_index, stamp_sec, debug_detection)

    h, _w = canvas.shape[:2]
    lines = [
        "v2 valid={} legacy={} report={} legacy_report={}".format(
            "Y" if gate_decision.valid else "N",
            "Y" if gate_decision.legacy_valid else "N",
            "Y" if gate_decision.accept_for_peak_report else "N",
            "Y" if gate_decision.legacy_accept_for_peak_report else "N",
        ),
        f"v2 peak_y_rect={csv_value(detection.get('peak_y'))}",
        f"v2 peak_rel_mm={csv_value(peak_rel_mm)} seg={csv_optional_int(peak_mapping.segment_id)} "
        f"extra={'Y' if peak_mapping.extrapolated else 'N'}",
        f"v2 center_rel_mm={csv_value(center_rel_mm)}",
    ]
    for index, line in enumerate(lines):
        cv2.putText(
            canvas,
            line,
            (18, h - 50 + 18 * index),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.5,
            (255, 255, 255),
            1,
        )
    return canvas


def apply_processing_overrides(args, processing):
    if args.threshold_bias is not None:
        processing.threshold_bias = int(args.threshold_bias)
    if args.blur_kernel is not None:
        processing.blur_kernel = int(args.blur_kernel)
    if args.no_clahe:
        processing.use_clahe = False
    if args.no_edge_fallback:
        processing.use_edge_fallback = False


def resolve_center_bias_correction_mm(args, config_path: Path) -> float:
    if args.center_bias_correction_mm is not None:
        return max(0.0, float(args.center_bias_correction_mm))
    if not config_path.exists():
        return 0.0
    try:
        config_dict = load_yaml(config_path)
    except Exception:  # pylint: disable=broad-except
        return 0.0
    if not isinstance(config_dict, dict):
        return 0.0
    postprocess = config_dict.get("postprocess", {})
    if not isinstance(postprocess, dict):
        return 0.0
    raw_value = postprocess.get("center_bias_correction_mm", 0.0)
    try:
        return max(0.0, float(raw_value))
    except (TypeError, ValueError):
        return 0.0


def generate_v2_height_curve_plot(
    path: Path,
    frame_indices: Sequence[int],
    stamp_seconds: Sequence[float],
    center_rel_mm_values: Sequence[Optional[float]],
    peak_rel_mm_values: Sequence[Optional[float]],
    confidence_values: Sequence[Optional[float]],
    detection_valid_flags: Sequence[bool],
    reportable_flags: Sequence[bool],
    include_confidence: bool,
    center_series_label: str,
) -> bool:
    if plt is None or not frame_indices:
        return False

    frames = np.asarray(frame_indices, dtype=np.int32)
    times = np.asarray(stamp_seconds, dtype=np.float64)
    if times.size > 0:
        times = times - times[0]

    x_values = times if times.size == frames.size else frames.astype(np.float64)
    center_rel_mm = np.asarray(
        [np.nan if value is None else float(value) for value in center_rel_mm_values],
        dtype=np.float32,
    )
    peak_rel_mm = np.asarray(
        [np.nan if value is None else float(value) for value in peak_rel_mm_values],
        dtype=np.float32,
    )
    confidence = np.asarray(
        [np.nan if value is None else float(value) for value in confidence_values],
        dtype=np.float32,
    )
    detection_valid = np.asarray(detection_valid_flags, dtype=bool)
    reportable = np.asarray(reportable_flags, dtype=bool)

    center_valid_mask = detection_valid & np.isfinite(center_rel_mm)
    center_report_mask = reportable & np.isfinite(center_rel_mm)
    center_withheld_mask = center_valid_mask & ~center_report_mask
    peak_valid_mask = detection_valid & np.isfinite(peak_rel_mm)
    peak_report_mask = reportable & np.isfinite(peak_rel_mm)

    if include_confidence:
        fig, axes = plt.subplots(2, 1, figsize=(12, 7), sharex=True)
        ax_curve, ax_conf = axes
    else:
        fig, ax_curve = plt.subplots(1, 1, figsize=(12, 4.8))
        ax_conf = None

    if np.any(center_valid_mask):
        ax_curve.plot(
            x_values[center_valid_mask],
            center_rel_mm[center_valid_mask],
            color="#9ecae1",
            linewidth=1.0,
            alpha=0.9,
            label=f"valid {center_series_label} [main liquid level]",
        )
    if np.any(peak_valid_mask):
        ax_curve.plot(
            x_values[peak_valid_mask],
            peak_rel_mm[peak_valid_mask],
            color="#d4b9da",
            linewidth=1.0,
            alpha=0.65,
            linestyle="--",
            label="valid peak_rel_mm_v2 [diagnostic]",
        )

    scatter = None
    if np.any(center_report_mask):
        ax_curve.plot(
            x_values[center_report_mask],
            center_rel_mm[center_report_mask],
            color="#1f77b4",
            linewidth=1.6,
            alpha=0.95,
            label=f"reported {center_series_label} [main]",
        )
        scatter = ax_curve.scatter(
            x_values[center_report_mask],
            center_rel_mm[center_report_mask],
            c=confidence[center_report_mask],
            cmap="viridis",
            vmin=0.0,
            vmax=1.0,
            s=18,
            linewidths=0.0,
            label="reported center points (colored by confidence)",
            zorder=3,
        )
    if np.any(peak_report_mask):
        ax_curve.plot(
            x_values[peak_report_mask],
            peak_rel_mm[peak_report_mask],
            color="#9467bd",
            linewidth=1.2,
            alpha=0.9,
            linestyle="--",
            label="reported peak_rel_mm_v2 [diagnostic]",
        )
    if np.any(center_withheld_mask):
        ax_curve.scatter(
            x_values[center_withheld_mask],
            center_rel_mm[center_withheld_mask],
            color="#9e9e9e",
            s=10,
            marker="x",
            alpha=0.6,
            label="valid but not reportable",
        )

    ax_curve.axhline(0.0, color="#616161", linewidth=1.0, linestyle="--")
    ax_curve.set_title("v2 Height Summary: Main Center Level and Diagnostic Peak")
    ax_curve.set_ylabel("relative height (mm)")
    ax_curve.grid(True, linestyle="--", alpha=0.25)
    ax_curve.legend(loc="upper right")

    if scatter is not None:
        cbar = fig.colorbar(scatter, ax=ax_curve, pad=0.02)
        cbar.set_label("meniscus_confidence_v2")

    if ax_conf is not None:
        valid_conf_mask = detection_valid & np.isfinite(confidence)
        report_conf_mask = reportable & np.isfinite(confidence)
        if np.any(valid_conf_mask):
            ax_conf.plot(
                x_values[valid_conf_mask],
                confidence[valid_conf_mask],
                color="#b0bec5",
                linewidth=1.0,
                label="valid confidence",
            )
        if np.any(report_conf_mask):
            ax_conf.scatter(
                x_values[report_conf_mask],
                confidence[report_conf_mask],
                color="#2e7d32",
                s=16,
                label="reportable confidence",
                zorder=3,
            )
        ax_conf.set_ylabel("confidence")
        ax_conf.set_xlabel("relative time (s)" if times.size == frames.size else "frame index")
        ax_conf.grid(True, linestyle="--", alpha=0.25)
        ax_conf.legend(loc="upper right")
    else:
        ax_curve.set_xlabel("relative time (s)" if times.size == frames.size else "frame index")

    fig.tight_layout()
    fig.savefig(path, dpi=160)
    plt.close(fig)
    return True


def main():
    args = parse_args()
    bag_path = Path(args.bag).expanduser().resolve()
    calibration_path = Path(args.calibration).expanduser().resolve()
    config_path = Path(args.config).expanduser().resolve() if args.config else v2_default_config()

    if not bag_path.exists():
        print(f"[ERROR] bag not found: {bag_path}", file=sys.stderr)
        return 1
    if not calibration_path.exists():
        print(f"[ERROR] calibration yaml not found: {calibration_path}", file=sys.stderr)
        return 2

    try:
        calibration_v2 = load_v2_calibration(calibration_path)
    except Exception as exc:  # pylint: disable=broad-except
        print(f"[ERROR] failed to load v2 calibration: {exc}", file=sys.stderr)
        return 3

    _, processing = load_processing_config(config_path if config_path.exists() else None)
    apply_processing_overrides(args, processing)
    center_bias_correction_mm = resolve_center_bias_correction_mm(args, config_path)
    center_series_label = (
        "center_rel_mm_bias_corrected_v2" if center_bias_correction_mm > 0.0 else "center_rel_mm_v2"
    )

    output_dir = Path(args.out_dir).expanduser().resolve() if args.out_dir else default_output_dir(bag_path)
    ensure_output_dir(output_dir)

    bridge = CvBridge()
    image_topic = args.image_topic
    csv_path = output_dir / "liquid_height_v2.csv"
    debug_video_path = output_dir / "liquid_debug_v2.mp4"
    plot_path = output_dir / "liquid_height_peak_curve_v2.png"

    processed_frames = 0
    valid_frames = 0
    reportable_frames = 0
    legacy_valid_frames = 0
    legacy_reportable_frames = 0
    max_peak_rel_px_v2 = None
    max_peak_rel_mm_v2 = None
    max_center_rel_mm_v2 = None
    max_center_rel_mm_bias_corrected_v2 = None
    writer = None
    previous_state: Optional[TemporalState] = None
    plot_frame_indices: List[int] = []
    plot_stamp_seconds: List[float] = []
    plot_peak_rel_mm_values: List[Optional[float]] = []
    plot_center_rel_mm_values: List[Optional[float]] = []
    plot_confidence_values: List[Optional[float]] = []
    plot_detection_valid_flags: List[bool] = []
    plot_reportable_flags: List[bool] = []
    rectification_matrix, _ = compute_rectification_matrix(calibration_v2.legacy)

    with rosbag.Bag(str(bag_path), "r") as bag:
        image_topics = image_topics_in_bag(bag)
        if not image_topic:
            try:
                config_dict = load_yaml(config_path) if config_path.exists() else {}
            except Exception:  # pylint: disable=broad-except
                config_dict = {}
            image_topic = str(config_dict.get("topic_image", "/camera/color/image_raw"))

        if image_topic not in image_topics:
            print(f"[ERROR] topic not found in bag: {image_topic}", file=sys.stderr)
            print("[INFO] available image topics:", file=sys.stderr)
            for topic in image_topics:
                print(f"  - {topic}", file=sys.stderr)
            return 4

        bag_start = bag.get_start_time()
        min_stamp = bag_start + max(args.time_offset, 0.0)

        with csv_path.open("w", newline="", encoding="utf-8") as csv_file:
            writer_csv = csv.writer(csv_file)
            writer_csv.writerow(
                [
                    "frame_index",
                    "stamp",
                    "relative_time_s",
                    "valid_v2",
                    "accept_for_peak_report_v2",
                    "legacy_valid_gate_v2",
                    "legacy_accept_for_peak_report_gate_v2",
                    "meniscus_confidence_v2",
                    "y_peak_raw_v2",
                    "y_peak_raw_rect_v2",
                    "y_center_raw_rect_v2",
                    "peak_candidate_source_v2",
                    "height_mapping_mode_v2",
                    "height_mapping_segment_id_v2",
                    "height_mapping_extrapolated_v2",
                    "height_peak_rel_px_signed_v2",
                    "height_center_rel_px_signed_v2",
                    "height_left_rel_px_signed_v2",
                    "height_right_rel_px_signed_v2",
                    "height_peak_rel_px_v2",
                    "height_center_rel_px_v2",
                    "height_left_rel_px_v2",
                    "height_right_rel_px_v2",
                    "height_peak_rel_mm_signed_v2",
                    "height_center_rel_mm_signed_v2",
                    "center_bias_correction_mm_v2",
                    "height_center_rel_mm_signed_bias_corrected_v2",
                    "height_left_rel_mm_signed_v2",
                    "height_right_rel_mm_signed_v2",
                    "height_peak_rel_mm_v2",
                    "height_center_rel_mm_v2",
                    "height_center_rel_mm_bias_corrected_v2",
                    "height_left_rel_mm_v2",
                    "height_right_rel_mm_v2",
                    "threshold_value_v2",
                    "valid_columns_v2",
                    "central_valid_columns_v2",
                    "central_coverage_v2",
                    "fit_points_v2",
                    "fit_rms_px_v2",
                    "fit_slope_v2",
                    "temporal_jump_px_v2",
                    "temporal_gate_passed_v2",
                    "peak_distance_to_top_px_v2",
                    "peak_body_span_ratio_v2",
                    "peak_local_support_ratio_v2",
                    "peak_local_rms_px_v2",
                    "peak_edge_dominance_v2",
                ]
            )

            image_counter = 0
            for _, msg, stamp in bag.read_messages(topics=[image_topic]):
                stamp_sec = stamp.to_sec()
                if stamp_sec < min_stamp:
                    continue
                if image_counter % max(args.every, 1) != 0:
                    image_counter += 1
                    continue
                if args.max_frames > 0 and processed_frames >= args.max_frames:
                    break

                try:
                    image = bridge.imgmsg_to_cv2(msg, desired_encoding=args.encoding)
                except CvBridgeError as exc:
                    print(f"[WARN] skip frame {image_counter}: {exc}", file=sys.stderr)
                    image_counter += 1
                    continue

                y0 = calibration_v2.legacy.roi_y
                y1 = calibration_v2.legacy.roi_y + calibration_v2.legacy.roi_h
                x0 = calibration_v2.legacy.roi_x
                x1 = calibration_v2.legacy.roi_x + calibration_v2.legacy.roi_w
                if y0 < 0 or x0 < 0 or y1 > image.shape[0] or x1 > image.shape[1]:
                    print(
                        f"[ERROR] calibration ROI exceeds frame bounds at frame {image_counter}.",
                        file=sys.stderr,
                    )
                    return 5

                roi_bgr = image[y0:y1, x0:x1].copy()
                rectified_roi_bgr, rectified_calibration = rectify_roi_and_calibration(roi_bgr, calibration_v2.legacy)
                detection = detect_liquid_profile(
                    rectified_roi_bgr,
                    rectified_calibration,
                    processing,
                    previous_state=previous_state,
                )

                peak_y_raw_rect_v2 = None if detection["peak_y"] is None else float(detection["peak_y"])
                center_y_raw_rect_v2 = None if detection["center_y"] is None else float(detection["center_y"])
                peak_x_raw_rect_v2 = peak_x_from_detection(detection)
                peak_y_raw_v2 = inverse_transform_y(rectification_matrix, peak_x_raw_rect_v2, peak_y_raw_rect_v2)

                left_mapping = evaluate_height_mapping(calibration_v2.reference_points, detection["left_y"])
                right_mapping = evaluate_height_mapping(calibration_v2.reference_points, detection["right_y"])
                center_mapping = evaluate_height_mapping(calibration_v2.reference_points, detection["center_y"])
                peak_mapping = evaluate_height_mapping(calibration_v2.reference_points, detection["peak_y"])

                left_rel_px_signed_v2 = zero_based_rel_px(calibration_v2.zero_y_rect, detection["left_y"])
                right_rel_px_signed_v2 = zero_based_rel_px(calibration_v2.zero_y_rect, detection["right_y"])
                center_rel_px_signed_v2 = zero_based_rel_px(calibration_v2.zero_y_rect, detection["center_y"])
                peak_rel_px_signed_v2 = zero_based_rel_px(calibration_v2.zero_y_rect, detection["peak_y"])
                left_rel_px_v2 = positive_only(left_rel_px_signed_v2)
                right_rel_px_v2 = positive_only(right_rel_px_signed_v2)
                center_rel_px_v2 = positive_only(center_rel_px_signed_v2)
                peak_rel_px_v2 = positive_only(peak_rel_px_signed_v2)

                left_rel_mm_signed_v2 = mapping_mm_value(left_mapping)
                right_rel_mm_signed_v2 = mapping_mm_value(right_mapping)
                center_rel_mm_signed_v2 = mapping_mm_value(center_mapping)
                peak_rel_mm_signed_v2 = mapping_mm_value(peak_mapping)
                left_rel_mm_v2 = positive_only(left_rel_mm_signed_v2)
                right_rel_mm_v2 = positive_only(right_rel_mm_signed_v2)
                center_rel_mm_v2 = positive_only(center_rel_mm_signed_v2)
                peak_rel_mm_v2 = positive_only(peak_rel_mm_signed_v2)
                center_rel_mm_signed_bias_corrected_v2 = (
                    None if center_rel_mm_signed_v2 is None else float(center_rel_mm_signed_v2) - center_bias_correction_mm
                )
                center_rel_mm_bias_corrected_v2 = positive_only(center_rel_mm_signed_bias_corrected_v2)

                gate_decision = evaluate_v2_gates(detection, processing, rectified_calibration.roi_h)

                if gate_decision.legacy_valid:
                    legacy_valid_frames += 1
                    new_state = build_temporal_state(detection)
                    if new_state is not None:
                        previous_state = new_state
                if gate_decision.legacy_accept_for_peak_report:
                    legacy_reportable_frames += 1

                if gate_decision.valid:
                    valid_frames += 1
                    if peak_rel_px_v2 is not None and (max_peak_rel_px_v2 is None or peak_rel_px_v2 > max_peak_rel_px_v2):
                        max_peak_rel_px_v2 = peak_rel_px_v2
                if gate_decision.accept_for_peak_report:
                    reportable_frames += 1
                    if peak_rel_mm_v2 is not None and (max_peak_rel_mm_v2 is None or peak_rel_mm_v2 > max_peak_rel_mm_v2):
                        max_peak_rel_mm_v2 = peak_rel_mm_v2
                    if center_rel_mm_v2 is not None and (
                        max_center_rel_mm_v2 is None or center_rel_mm_v2 > max_center_rel_mm_v2
                    ):
                        max_center_rel_mm_v2 = center_rel_mm_v2
                    if center_rel_mm_bias_corrected_v2 is not None and (
                        max_center_rel_mm_bias_corrected_v2 is None
                        or center_rel_mm_bias_corrected_v2 > max_center_rel_mm_bias_corrected_v2
                    ):
                        max_center_rel_mm_bias_corrected_v2 = center_rel_mm_bias_corrected_v2

                writer_csv.writerow(
                    [
                        image_counter,
                        f"{stamp_sec:.9f}",
                        f"{(stamp_sec - bag_start):.9f}",
                        int(gate_decision.valid),
                        int(gate_decision.accept_for_peak_report),
                        int(gate_decision.legacy_valid),
                        int(gate_decision.legacy_accept_for_peak_report),
                        csv_value(detection["confidence"]),
                        csv_value(peak_y_raw_v2),
                        csv_value(peak_y_raw_rect_v2),
                        csv_value(center_y_raw_rect_v2),
                        detection["peak_source"],
                        calibration_v2.mapping_mode,
                        csv_optional_int(peak_mapping.segment_id),
                        int(peak_mapping.extrapolated),
                        csv_value(peak_rel_px_signed_v2),
                        csv_value(center_rel_px_signed_v2),
                        csv_value(left_rel_px_signed_v2),
                        csv_value(right_rel_px_signed_v2),
                        csv_value(peak_rel_px_v2),
                        csv_value(center_rel_px_v2),
                        csv_value(left_rel_px_v2),
                        csv_value(right_rel_px_v2),
                        csv_value(peak_rel_mm_signed_v2),
                        csv_value(center_rel_mm_signed_v2),
                        f"{center_bias_correction_mm:.6f}",
                        csv_value(center_rel_mm_signed_bias_corrected_v2),
                        csv_value(left_rel_mm_signed_v2),
                        csv_value(right_rel_mm_signed_v2),
                        csv_value(peak_rel_mm_v2),
                        csv_value(center_rel_mm_v2),
                        csv_value(center_rel_mm_bias_corrected_v2),
                        csv_value(left_rel_mm_v2),
                        csv_value(right_rel_mm_v2),
                        detection["threshold_value"],
                        detection["valid_columns"],
                        detection["central_valid_columns"],
                        csv_value(detection["central_coverage"]),
                        detection["fit_points"],
                        csv_value(detection["fit_rms_px"]),
                        csv_value(detection["fit_slope"]),
                        csv_value(detection["temporal_jump_px"]),
                        int(detection["temporal_gate_passed"]),
                        csv_value(detection["peak_distance_to_top_px"]),
                        csv_value(detection["peak_body_span_ratio"]),
                        csv_value(detection["peak_local_support_ratio"]),
                        csv_value(detection["peak_local_rms_px"]),
                        csv_value(detection["peak_edge_dominance"]),
                    ]
                )

                plot_frame_indices.append(int(image_counter))
                plot_stamp_seconds.append(float(stamp_sec))
                plot_peak_rel_mm_values.append(None if peak_rel_mm_v2 is None else float(peak_rel_mm_v2))
                plot_center_rel_mm_values.append(
                    None
                    if (
                        center_rel_mm_bias_corrected_v2 if center_bias_correction_mm > 0.0 else center_rel_mm_v2
                    ) is None
                    else float(center_rel_mm_bias_corrected_v2 if center_bias_correction_mm > 0.0 else center_rel_mm_v2)
                )
                plot_confidence_values.append(float(detection["confidence"]))
                plot_detection_valid_flags.append(gate_decision.valid)
                plot_reportable_flags.append(gate_decision.accept_for_peak_report)

                if not args.skip_debug_video:
                    debug_frame = make_debug_frame_v2(
                        rectified_roi_bgr,
                        rectified_calibration,
                        image_counter,
                        stamp_sec,
                        detection,
                        gate_decision,
                        peak_mapping,
                        peak_rel_mm_v2,
                        center_rel_mm_bias_corrected_v2 if center_bias_correction_mm > 0.0 else center_rel_mm_v2,
                    )
                    if writer is None:
                        writer = open_video_writer(
                            debug_video_path,
                            (debug_frame.shape[1], debug_frame.shape[0]),
                            max(1.0, float(args.debug_fps)),
                        )
                        if writer is None:
                            print(
                                f"[WARN] failed to open debug video writer: {debug_video_path}. "
                                "Continuing without debug video.",
                                file=sys.stderr,
                            )
                            args.skip_debug_video = True
                    if writer is not None:
                        writer.write(debug_frame)

                processed_frames += 1
                image_counter += 1

    if writer is not None:
        writer.release()

    if processed_frames == 0:
        print("[WARN] no frames processed. Check topic/time-offset/every/max-frames.", file=sys.stderr)
        return 6

    valid_ratio = valid_frames / float(processed_frames)
    legacy_valid_ratio = legacy_valid_frames / float(processed_frames)
    print(f"[OK] processed frames: {processed_frames}")
    print(f"[OK] valid frames: {valid_frames} ({valid_ratio:.1%})")
    print(f"[OK] legacy valid gate frames: {legacy_valid_frames} ({legacy_valid_ratio:.1%})")
    print(f"[OK] reportable peak frames: {reportable_frames}")
    print(f"[OK] legacy reportable peak frames: {legacy_reportable_frames}")
    print(f"[OK] height_mapping.zero_y_rect = {calibration_v2.zero_y_rect:.6f}")
    if max_peak_rel_px_v2 is not None:
        print(f"[OK] max height_peak_rel_px_v2: {max_peak_rel_px_v2:.3f}")
    else:
        print("[WARN] no valid v2 peak pixel height detected.")
    if max_peak_rel_mm_v2 is not None:
        print(f"[OK] max height_peak_rel_mm_v2: {max_peak_rel_mm_v2:.3f}")
    else:
        print("[WARN] no reportable v2 peak mm height detected.")
    if max_center_rel_mm_v2 is not None:
        print(f"[OK] max height_center_rel_mm_v2: {max_center_rel_mm_v2:.3f}")
    else:
        print("[WARN] no reportable v2 center mm height detected.")
    if max_center_rel_mm_bias_corrected_v2 is not None:
        print(f"[OK] max height_center_rel_mm_bias_corrected_v2: {max_center_rel_mm_bias_corrected_v2:.3f}")
    if center_bias_correction_mm > 0.0:
        print(f"[OK] center bias correction applied: {center_bias_correction_mm:.6f} mm")
    print(f"[OK] csv: {csv_path}")
    if not args.skip_debug_video and debug_video_path.exists():
        print(f"[OK] debug video: {debug_video_path}")
    if not args.skip_plot:
        if generate_v2_height_curve_plot(
            plot_path,
            plot_frame_indices,
            plot_stamp_seconds,
            plot_center_rel_mm_values,
            plot_peak_rel_mm_values,
            plot_confidence_values,
            plot_detection_valid_flags,
            plot_reportable_flags,
            args.plot_confidence,
            center_series_label,
        ):
            print(f"[OK] height curve plot: {plot_path}")
        else:
            print("[WARN] failed to generate v2 height curve plot.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
