#!/usr/bin/env python3
"""
Infer red-liquid top boundary from a rosbag image stream.

Three-ruler mode (recommended)
-------------------------------
Pass a YAML generated by red_liquid_calibrate.py (contains a `rulers` section).
The script divides the tube interior into three column bands (left / center / right),
detects the red top boundary in each band, converts y_px → h_mm via the per-ruler
piecewise-linear calibration, and outputs the median as h_mm_final.

Legacy / no-calibration mode
-----------------------------
If the YAML has no `rulers` section (or no YAML is given), the script falls back to
detecting the red top across the full tube width. Only y_top_roi is output; h_mm
columns will be empty.
"""

import argparse
import csv
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import cv2
import numpy as np
import yaml

try:
    import rosbag
    from cv_bridge import CvBridge, CvBridgeError
    _HAS_ROS = True
except ImportError:
    _HAS_ROS = False

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt  # noqa: E402
    _HAS_MPL = True
except ImportError:
    plt = None  # type: ignore[assignment]
    _HAS_MPL = False


RULER_NAMES: Tuple[str, str, str] = ("left", "center", "right")
RULER_COLORS: List[Tuple[int, int, int]] = [
    (0, 165, 255),   # orange – left
    (0, 210,   0),   # green  – center
    (200, 80, 255),  # purple – right
]


# ── CLI ───────────────────────────────────────────────────────────────────────

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Detect red liquid top boundary from a rosbag RGB stream."
    )
    p.add_argument("--bag",          required=True, help="Path to rosbag.")
    p.add_argument("--calibration",  default="",
                   help="Calibration YAML (from red_liquid_calibrate.py). Provides ROI/tube/rulers.")
    p.add_argument("--topic",        default="/camera/color/image_raw",
                   help="RGB image topic. Default: /camera/color/image_raw")
    p.add_argument("--out-dir",      default="",
                   help="Output directory. Default: <bag_stem>_red_results next to bag.")
    p.add_argument("--time-offset",  type=float, default=0.0, help="Skip first N seconds.")
    p.add_argument("--max-frames",   type=int,   default=0,   help="Process at most N frames (0=all).")
    p.add_argument("--every",        type=int,   default=1,   help="Process every N-th frame.")
    p.add_argument("--debug-every",  type=int,   default=0,
                   help="Save debug image every N processed frames (0=off).")
    p.add_argument("--encoding",     default="bgr8",
                   help="cv_bridge encoding. Default: bgr8")
    p.add_argument("--list-topics",  action="store_true",
                   help="List image topics in the bag and exit.")

    # Manual geometry fallback when no YAML is provided.
    p.add_argument("--roi-x",        type=int,   default=None)
    p.add_argument("--roi-y",        type=int,   default=None)
    p.add_argument("--roi-w",        type=int,   default=None)
    p.add_argument("--roi-h",        type=int,   default=None)
    p.add_argument("--tube-left",    type=int,   default=None, help="Tube inner left x in ROI coords.")
    p.add_argument("--tube-right",   type=int,   default=None, help="Tube inner right x in ROI coords.")
    p.add_argument("--rotation-deg", type=float, default=None, help="Optional ROI rotation correction.")

    # Red segmentation parameters.
    p.add_argument("--hue1-low",     type=int,   default=0)
    p.add_argument("--hue1-high",    type=int,   default=12)
    p.add_argument("--hue2-low",     type=int,   default=168)
    p.add_argument("--hue2-high",    type=int,   default=179)
    p.add_argument("--sat-min",      type=int,   default=70)
    p.add_argument("--val-min",      type=int,   default=35)
    p.add_argument("--morph-kernel", type=int,   default=5)
    p.add_argument(
        "--top-boundary-quantile", type=float, default=0.2,
        help="Quantile of per-column top pixels for robust top boundary. Default: 0.2",
    )
    p.add_argument(
        "--min-valid-column-fraction", type=float, default=0.15,
        help="Minimum fraction of valid red columns. Default: 0.15",
    )
    # center-col-fraction: used only in legacy single-detection mode
    p.add_argument("--center-col-fraction", type=float, default=0.6)

    # Connected-component bottom-body filter (Step 1).
    p.add_argument(
        "--min-component-area", type=int, default=30,
        help="Min pixel area for a red connected component to be kept. Default: 30",
    )
    p.add_argument(
        "--bottom-touch-rows", type=int, default=15,
        help="A component must touch the bottom N rows of the ROI to be considered "
             "the main liquid body. Default: 15",
    )

    # Static zero-point correction (Step 2).
    p.add_argument(
        "--zero-correction-frames", type=int, default=0,
        help="Use the first N processed frames to estimate a static h0 offset. "
             "h_mm_corr = h_mm_final - h0 is added to CSV/plot. 0 = disabled. Default: 0",
    )

    # Temporal boundary smoothing (Step 3).
    p.add_argument(
        "--smooth-frames", type=int, default=1,
        help="Rolling-median window (frames) applied to h_mm_final and h_mm_corr. "
             "1 = off. Default: 1",
    )
    return p.parse_args()


# ── Geometry / calibration loading ───────────────────────────────────────────

def load_calibration(calib_path: Path) -> Dict:
    with calib_path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def resolve_geometry(
    args: argparse.Namespace,
    calib: Optional[Dict],
) -> Tuple[Dict, Optional[Dict]]:
    """Return (geom, rulers).

    geom contains ROI/tube coordinates.
    rulers is the parsed `rulers` section from the YAML, or None if absent.
    """
    if calib is not None:
        geom: Dict = {
            "roi_x":       int(calib["roi"]["x"]),
            "roi_y":       int(calib["roi"]["y"]),
            "roi_w":       int(calib["roi"]["w"]),
            "roi_h":       int(calib["roi"]["h"]),
            "tube_left":   int(calib["tube_inner"]["x_left"]),
            "tube_right":  int(calib["tube_inner"]["x_right"]),
            "rotation_deg": float(calib.get("rotation_deg", 0.0)),
        }
        rulers = calib.get("rulers")   # None if old YAML without rulers section
        return geom, rulers

    required = [args.roi_x, args.roi_y, args.roi_w, args.roi_h,
                args.tube_left, args.tube_right]
    if any(v is None for v in required):
        raise ValueError("Need --calibration or all of --roi-x/y/w/h --tube-left --tube-right.")
    geom = {
        "roi_x":       int(args.roi_x),
        "roi_y":       int(args.roi_y),
        "roi_w":       int(args.roi_w),
        "roi_h":       int(args.roi_h),
        "tube_left":   int(args.tube_left),
        "tube_right":  int(args.tube_right),
        "rotation_deg": float(args.rotation_deg or 0.0),
    }
    return geom, None


# ── Detection helpers ─────────────────────────────────────────────────────────

def _prepare_mask(
    image_bgr: np.ndarray,
    geom: Dict,
    args: argparse.Namespace,
) -> Tuple[np.ndarray, np.ndarray]:
    """Crop ROI, apply rotation, run HSV red segmentation + morphology.

    Returns (roi_img, red_mask).
    """
    ox, oy = geom["roi_x"], geom["roi_y"]
    rw, rh = geom["roi_w"], geom["roi_h"]
    roi = image_bgr[oy:oy + rh, ox:ox + rw].copy()
    if roi.size == 0:
        return roi, np.zeros((rh, rw), dtype=np.uint8)

    rotation_deg = float(geom.get("rotation_deg", 0.0))
    if abs(rotation_deg) > 0.1:
        h_img, w_img = roi.shape[:2]
        cx, cy = (w_img - 1) * 0.5, (h_img - 1) * 0.5
        M = cv2.getRotationMatrix2D((cx, cy), -rotation_deg, 1.0)
        roi = cv2.warpAffine(roi, M, (w_img, h_img),
                             flags=cv2.INTER_LINEAR,
                             borderMode=cv2.BORDER_REPLICATE)

    hsv = cv2.cvtColor(roi, cv2.COLOR_BGR2HSV)
    lower1 = np.array([args.hue1_low,  args.sat_min, args.val_min], dtype=np.uint8)
    upper1 = np.array([args.hue1_high, 255,          255          ], dtype=np.uint8)
    lower2 = np.array([args.hue2_low,  args.sat_min, args.val_min], dtype=np.uint8)
    upper2 = np.array([args.hue2_high, 255,          255          ], dtype=np.uint8)
    mask = cv2.inRange(hsv, lower1, upper1) | cv2.inRange(hsv, lower2, upper2)

    k = max(1, int(args.morph_kernel))
    if k % 2 == 0:
        k += 1
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (k, k))
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN,  kernel)
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel)
    return roi, mask


def _top_in_band(
    mask: np.ndarray,
    x1: int,
    x2: int,
    quantile: float,
    min_valid_frac: float,
) -> Tuple[Optional[float], float]:
    """Find the red-top y in columns [x1, x2) of mask.

    Returns (y_top_roi, valid_col_frac).
    """
    h, w = mask.shape
    x1 = max(0, x1)
    x2 = min(w, x2)
    if x2 - x1 < 2:
        return None, 0.0

    col_tops: List[float] = []
    for col in range(x1, x2):
        ys = np.flatnonzero(mask[:, col] > 0)
        if len(ys) > 0:
            col_tops.append(float(ys[0]))

    used = x2 - x1
    valid_frac = len(col_tops) / float(used)
    if valid_frac < min_valid_frac:
        return None, valid_frac

    q = max(0.0, min(1.0, quantile))
    y_top = float(np.quantile(np.asarray(col_tops, dtype=np.float32), q))
    return y_top, valid_frac


def _top_in_band_cc(
    mask: np.ndarray,
    x1: int,
    x2: int,
    quantile: float,
    min_valid_frac: float,
    bottom_touch_rows: int,
    min_component_area: int,
) -> Tuple[Optional[float], float]:
    """Like _top_in_band but only considers connected components that touch the ROI bottom.

    Rationale: the real liquid body is always contiguous with the tube bottom.
    Isolated reflections, stray marks, and splash droplets above the surface
    are disconnected from the bottom and are filtered out.

    Falls back to _top_in_band if no bottom-connected component is found
    (e.g. HSV range too narrow, ROI mis-aligned).
    """
    h, w = mask.shape
    x1 = max(0, x1)
    x2 = min(w, x2)
    if x2 - x1 < 2:
        return None, 0.0

    band = mask[:, x1:x2]
    num_labels, labels, stats, _ = cv2.connectedComponentsWithStats(band, connectivity=8)

    if num_labels <= 1:
        return None, 0.0

    bottom_row = max(0, h - bottom_touch_rows)
    filtered = np.zeros((h, x2 - x1), dtype=np.uint8)

    for lbl in range(1, num_labels):
        if stats[lbl, cv2.CC_STAT_AREA] < min_component_area:
            continue
        comp = labels == lbl
        if np.any(comp[bottom_row:, :]):
            filtered[comp] = 255

    if not np.any(filtered):
        # Fall back: no qualifying bottom-connected component found
        return _top_in_band(mask, x1, x2, quantile, min_valid_frac)

    col_tops: List[float] = []
    for col in range(x2 - x1):
        ys = np.flatnonzero(filtered[:, col] > 0)
        if len(ys) > 0:
            col_tops.append(float(ys[0]))

    used = x2 - x1
    valid_frac = len(col_tops) / float(used)
    if valid_frac < min_valid_frac:
        return None, valid_frac

    q = max(0.0, min(1.0, quantile))
    return float(np.quantile(np.asarray(col_tops, dtype=np.float32), q)), valid_frac


def _px_to_mm(y_px: float, ref_pts: List[Dict]) -> Tuple[Optional[float], bool]:
    """Piecewise-linear y_px_roi → (h_mm, clipped).

    clipped=True means y_px was outside the calibrated range and the returned
    value is the nearest endpoint — the true value may be higher/lower.

    ref_pts: list of {y_px_roi, h_mm}, larger y = lower h_mm (bottom of tube).
    """
    if not ref_pts:
        return None, False
    pts = sorted(ref_pts, key=lambda p: p["y_px_roi"], reverse=True)
    ys = [p["y_px_roi"] for p in pts]
    hs = [p["h_mm"]     for p in pts]

    if y_px >= ys[0]:
        return hs[0], True   # below 0 mm end of range
    if y_px <= ys[-1]:
        return hs[-1], True  # above top end of range
    for i in range(len(ys) - 1):
        if ys[i] >= y_px >= ys[i + 1]:
            alpha = (ys[i] - y_px) / max(1e-9, ys[i] - ys[i + 1])
            return hs[i] + alpha * (hs[i + 1] - hs[i]), False
    return None, False


def detect_red_liquid(
    image_bgr: np.ndarray,
    geom: Dict,
    rulers: Optional[Dict],
    args: argparse.Namespace,
) -> Tuple[List[Optional[float]], List[Optional[float]], List[float], List[bool], np.ndarray]:
    """Detect red top boundary.

    Three-ruler mode (rulers is not None):
      Divides tube into left/center/right bands at midpoints between ruler x positions.
      Returns per-band y_top, h_mm, confidence, and clipped flag.

    Legacy mode (rulers is None):
      Single detection across center_col_fraction of tube.
      y_tops[0] = y_top, h_mms / clipped = [None/False, None/False, None/False].

    Returns (y_tops[3], h_mms[3], confs[3], clipped[3], mask).
    clipped[i]=True means h_mms[i] was clamped to the calibration range boundary.
    """
    _roi_img, mask = _prepare_mask(image_bgr, geom, args)

    if rulers is None:
        # Legacy: single detection using center_col_fraction
        x_left  = int(geom["tube_left"])
        x_right = int(geom["tube_right"])
        tube_w  = x_right - x_left
        frac    = max(0.1, min(1.0, float(args.center_col_fraction)))
        excl    = (1.0 - frac) / 2.0
        x1 = max(0, x_left  + int(round(excl * tube_w)))
        x2 = min(mask.shape[1], x_right - int(round(excl * tube_w)))
        if x2 - x1 < 4:
            x1, x2 = x_left, x_right
        y_top, conf = _top_in_band(mask, x1, x2,
                                   args.top_boundary_quantile,
                                   args.min_valid_column_fraction)
        return [y_top, None, None], [None, None, None], [conf, 0.0, 0.0], [False, False, False], mask

    # Three-ruler mode
    ruler_xs = [float(rulers[n]["x_roi"]) for n in RULER_NAMES]
    x_left   = int(geom["tube_left"])
    x_right  = int(geom["tube_right"])
    mid01    = (ruler_xs[0] + ruler_xs[1]) / 2.0
    mid12    = (ruler_xs[1] + ruler_xs[2]) / 2.0
    bands    = [
        (x_left,       int(mid01)),
        (int(mid01),   int(mid12)),
        (int(mid12),   x_right),
    ]

    y_tops:   List[Optional[float]] = []
    h_mms:    List[Optional[float]] = []
    confs:    List[float]           = []
    clipped:  List[bool]            = []

    for ridx, rname in enumerate(RULER_NAMES):
        x1, x2 = bands[ridx]
        y_top, conf = _top_in_band_cc(
            mask, x1, x2,
            args.top_boundary_quantile,
            args.min_valid_column_fraction,
            bottom_touch_rows=args.bottom_touch_rows,
            min_component_area=args.min_component_area,
        )
        y_tops.append(y_top)
        confs.append(conf)

        h_mm: Optional[float] = None
        clip = False
        if y_top is not None:
            h_mm, clip = _px_to_mm(y_top, rulers[rname]["reference_points"])
        h_mms.append(h_mm)
        clipped.append(clip)

    return y_tops, h_mms, confs, clipped, mask


def h_mm_final(h_mms: List[Optional[float]]) -> Optional[float]:
    """Median of valid h_mm values across the three rulers."""
    valid = [h for h in h_mms if h is not None]
    if not valid:
        return None
    return float(np.median(valid))


# ── Debug rendering ───────────────────────────────────────────────────────────

def render_debug(
    image_bgr: np.ndarray,
    geom: Dict,
    rulers: Optional[Dict],
    y_tops: List[Optional[float]],
    h_mms: List[Optional[float]],
    confs: List[float],
    clipped: List[bool],
    mask: np.ndarray,
    args: argparse.Namespace,
) -> np.ndarray:
    canvas = image_bgr.copy()
    rx, ry = geom["roi_x"], geom["roi_y"]
    rw, rh = geom["roi_w"], geom["roi_h"]

    # ROI and tube-wall rectangles
    cv2.rectangle(canvas, (rx, ry), (rx + rw, ry + rh), (0, 255, 255), 2)
    cv2.rectangle(canvas,
                  (rx + int(geom["tube_left"]),  ry),
                  (rx + int(geom["tube_right"]), ry + rh),
                  (0, 200, 200), 1)

    if rulers is None:
        # Legacy: single line
        y_top = y_tops[0]
        conf  = confs[0]
        if y_top is not None:
            y_img = ry + int(round(y_top))
            cv2.line(canvas,
                     (rx + int(geom["tube_left"]),  y_img),
                     (rx + int(geom["tube_right"]), y_img),
                     (0, 255, 0), 2)
        cv2.putText(canvas, f"conf={conf:.2f}",
                    (max(0, rx), max(18, ry - 6)),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.55, (255, 255, 255), 1)
    else:
        # Three rulers: draw per-band lines + ruler x positions
        ruler_xs = [float(rulers[n]["x_roi"]) for n in RULER_NAMES]
        mid01  = (ruler_xs[0] + ruler_xs[1]) / 2.0
        mid12  = (ruler_xs[1] + ruler_xs[2]) / 2.0
        band_lefts  = [int(geom["tube_left"]), int(mid01), int(mid12)]
        band_rights = [int(mid01), int(mid12), int(geom["tube_right"])]

        for ridx, (rname, rcol) in enumerate(zip(RULER_NAMES, RULER_COLORS)):
            # Ruler column marker
            rx_pos = int(round(ruler_xs[ridx]))
            cv2.line(canvas,
                     (rx + rx_pos, ry), (rx + rx_pos, ry + rh),
                     rcol, 1)

            y_top = y_tops[ridx]
            h_mm  = h_mms[ridx]
            if y_top is not None:
                y_img    = ry + int(round(y_top))
                x_line_l = rx + band_lefts[ridx]
                x_line_r = rx + band_rights[ridx]
                clip_flag = clipped[ridx] if ridx < len(clipped) else False
                line_col  = (0, 0, 255) if clip_flag else rcol  # red when clipped
                cv2.line(canvas, (x_line_l, y_img), (x_line_r, y_img), line_col, 2)
                if h_mm is not None:
                    clip_tag = "[CLIP]" if clip_flag else ""
                    label = f"{rname[0].upper()}:{h_mm:.1f}mm{clip_tag}"
                else:
                    label = f"{rname[0].upper()}:?mm"
                cv2.putText(canvas, label,
                            (x_line_l, max(ry + 4, y_img - 4)),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.38, line_col, 1)

        h_final = h_mm_final(h_mms)
        mean_conf = float(np.mean([c for c in confs if c > 0])) if any(c > 0 for c in confs) else 0.0
        summary = (f"final={h_final:.2f}mm" if h_final is not None else "final=?")
        cv2.putText(canvas, f"{summary}  conf={mean_conf:.2f}",
                    (max(0, rx), max(18, ry - 6)),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.55, (255, 255, 255), 1)

    # Mask overlay (semi-transparent)
    small_mask = cv2.cvtColor(mask, cv2.COLOR_GRAY2BGR)
    small_mask = cv2.resize(small_mask, (rw, rh), interpolation=cv2.INTER_NEAREST)
    roi_view = canvas[ry:ry + rh, rx:rx + rw]
    if roi_view.shape == small_mask.shape:
        canvas[ry:ry + rh, rx:rx + rw] = cv2.addWeighted(roi_view, 1.0, small_mask, 0.25, 0.0)

    return canvas


def render_debug_clear(
    image_bgr: np.ndarray,
    geom: Dict,
    rulers: Optional[Dict],
    y_tops: List[Optional[float]],
) -> np.ndarray:
    """Render a clean debug view: raw image + only detection lines.

    Purpose:
      - avoid mask/text occlusion over the liquid region
      - make visual judgement of line placement easier
    """
    canvas = image_bgr.copy()
    rx, ry = geom["roi_x"], geom["roi_y"]

    if rulers is None:
        y_top = y_tops[0]
        if y_top is not None:
            y_img = ry + int(round(y_top))
            cv2.line(
                canvas,
                (rx + int(geom["tube_left"]), y_img),
                (rx + int(geom["tube_right"]), y_img),
                (0, 255, 0),
                2,
            )
        return canvas

    ruler_xs = [float(rulers[n]["x_roi"]) for n in RULER_NAMES]
    mid01 = (ruler_xs[0] + ruler_xs[1]) / 2.0
    mid12 = (ruler_xs[1] + ruler_xs[2]) / 2.0
    band_lefts = [int(geom["tube_left"]), int(mid01), int(mid12)]
    band_rights = [int(mid01), int(mid12), int(geom["tube_right"])]

    for ridx, rcol in enumerate(RULER_COLORS):
        y_top = y_tops[ridx]
        if y_top is None:
            continue
        y_img = ry + int(round(y_top))
        x_line_l = rx + band_lefts[ridx]
        x_line_r = rx + band_rights[ridx]
        cv2.line(canvas, (x_line_l, y_img), (x_line_r, y_img), rcol, 2)

    return canvas


# ── CSV / plot output ─────────────────────────────────────────────────────────

def save_csv(
    out_path: Path,
    frame_indices:  List[int],
    stamps:         List[float],
    y_tops_all:     List[List[Optional[float]]],
    h_mms_all:      List[List[Optional[float]]],
    confs_all:      List[List[float]],
    clipped_all:    List[List[bool]],
    h_corr_all:     List[Optional[float]],
    h_smooth_final: List[Optional[float]],
    h_smooth_corr:  List[Optional[float]],
    has_rulers: bool,
) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", newline="") as f:
        writer = csv.writer(f)
        if has_rulers:
            writer.writerow([
                "frame_index", "stamp_sec",
                "y_top_left",    "h_mm_left",   "clipped_left",
                "y_top_center",  "h_mm_center", "clipped_center",
                "y_top_right",   "h_mm_right",  "clipped_right",
                "h_mm_final",    "conf_mean",   "any_clipped",
                "h_mm_corr",     # zero-corrected; empty if correction disabled
                "h_mm_smooth",   # rolling-median of h_mm_final (=h_mm_final if smooth=1)
                "h_mm_smooth_corr",  # rolling-median of h_mm_corr
            ])
            for fi, st, ytops, hms, cnfs, clips, h_corr, h_sf, h_sc in zip(
                    frame_indices, stamps, y_tops_all, h_mms_all,
                    confs_all, clipped_all, h_corr_all, h_smooth_final, h_smooth_corr):
                def _f(v: Optional[float]) -> str:
                    return f"{v:.3f}" if v is not None else ""
                h_fin = h_mm_final(hms)
                valid_cnfs = [c for c in cnfs if c > 0]
                mean_conf  = float(np.mean(valid_cnfs)) if valid_cnfs else 0.0
                writer.writerow([
                    fi, f"{st:.9f}",
                    _f(ytops[0]), _f(hms[0]), int(clips[0]),
                    _f(ytops[1]), _f(hms[1]), int(clips[1]),
                    _f(ytops[2]), _f(hms[2]), int(clips[2]),
                    _f(h_fin), f"{mean_conf:.4f}", int(any(clips)),
                    _f(h_corr), _f(h_sf), _f(h_sc),
                ])
        else:
            writer.writerow(["frame_index", "stamp_sec", "y_top_roi", "confidence"])
            for fi, st, ytops, _, cnfs, __, ___, ____, _____ in zip(
                    frame_indices, stamps, y_tops_all, h_mms_all,
                    confs_all, clipped_all, h_corr_all, h_smooth_final, h_smooth_corr):
                yt = ytops[0]
                writer.writerow([
                    fi, f"{st:.9f}",
                    f"{yt:.2f}" if yt is not None else "",
                    f"{cnfs[0]:.4f}",
                ])
    print(f"[OK] saved CSV: {out_path}")


def save_plot(
    out_path: Path,
    stamps: List[float],
    h_mms_all: List[List[Optional[float]]],
    y_tops_all: List[List[Optional[float]]],
    h_corr_all: List[Optional[float]],
    h_smooth_corr: List[Optional[float]],
    has_rulers: bool,
) -> None:
    if not _HAS_MPL:
        return
    t0 = stamps[0] if stamps else 0.0

    plt.figure(figsize=(12, 5))

    if has_rulers:
        # Per-frame max of the three ruler estimates
        xs_max, ys_max = [], []
        for st, hms in zip(stamps, h_mms_all):
            valid = [h for h in hms if h is not None]
            if valid:
                xs_max.append(st - t0)
                ys_max.append(float(max(valid)))
        if xs_max:
            plt.plot(xs_max, ys_max, linewidth=1.8, color="#FF8C00",
                     alpha=0.9, label="max(L,C,R)")

        # Smoothed zero-corrected curve
        xs_sc, ys_sc = [], []
        for st, hsc in zip(stamps, h_smooth_corr):
            if hsc is not None:
                xs_sc.append(st - t0)
                ys_sc.append(hsc)
        if xs_sc:
            plt.plot(xs_sc, ys_sc, linewidth=2.2, color="cyan",
                     label="corr+smooth")

        plt.ylabel("Liquid height h_mm")
        plt.legend(loc="upper right", fontsize=8)
    else:
        xs, ys = [], []
        for st, ytops in zip(stamps, y_tops_all):
            yt = ytops[0]
            if yt is not None:
                xs.append(st - t0)
                ys.append(yt)
        if xs:
            plt.plot(xs, ys, linewidth=1.5)
        plt.ylabel("Red top y (px, ROI)")

    plt.xlabel("Time (s)")
    plt.title("Red liquid top boundary")
    plt.grid(True, alpha=0.25)
    plt.tight_layout()
    plt.savefig(out_path, dpi=300, facecolor="#1a1a1a")
    plt.close()
    print(f"[OK] saved curve plot: {out_path}")


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> int:
    args = parse_args()
    if not _HAS_ROS:
        print("[ERROR] rosbag / cv_bridge not available. Run inside a ROS environment.",
              file=sys.stderr)
        return 1

    bag_path = Path(args.bag).expanduser().resolve()
    if not bag_path.exists():
        print(f"[ERROR] bag not found: {bag_path}", file=sys.stderr)
        return 2

    calib: Optional[Dict] = None
    if args.calibration:
        calib_path = Path(args.calibration).expanduser().resolve()
        if not calib_path.exists():
            print(f"[ERROR] calibration not found: {calib_path}", file=sys.stderr)
            return 3
        calib = load_calibration(calib_path)

    try:
        geom, rulers = resolve_geometry(args, calib)
    except ValueError as exc:
        print(f"[ERROR] {exc}", file=sys.stderr)
        return 4

    has_rulers = rulers is not None
    mode_str = "three-ruler" if has_rulers else "legacy-single"
    print(f"[INFO] detection mode: {mode_str}")

    out_dir = (
        Path(args.out_dir).expanduser().resolve()
        if args.out_dir
        else bag_path.parent / f"{bag_path.stem}_red_results"
    )
    out_dir.mkdir(parents=True, exist_ok=True)

    bridge = CvBridge()  # type: ignore[possibly-undefined]

    frame_indices: List[int]               = []
    stamps:        List[float]             = []
    y_tops_all:    List[List[Optional[float]]] = []
    h_mms_all:     List[List[Optional[float]]] = []
    confs_all:     List[List[float]]       = []
    clipped_all:   List[List[bool]]        = []

    debug_dir = out_dir / "debug_frames" if args.debug_every > 0 else None
    debug_clear_dir = out_dir / "debug_frames_clear" if args.debug_every > 0 else None
    if debug_dir:
        debug_dir.mkdir(parents=True, exist_ok=True)
    if debug_clear_dir:
        debug_clear_dir.mkdir(parents=True, exist_ok=True)

    with rosbag.Bag(str(bag_path), "r") as bag:  # type: ignore[possibly-undefined]
        topic_info = bag.get_type_and_topic_info().topics

        if args.list_topics:
            print("Image topics in bag:")
            for t, info in sorted(topic_info.items()):
                if info.msg_type == "sensor_msgs/Image":
                    print(f"  {t} ({info.message_count} msgs)")
            return 0

        if args.topic not in topic_info:
            print(f"[ERROR] topic not found: {args.topic}", file=sys.stderr)
            return 5

        bag_start  = bag.get_start_time()
        min_stamp  = bag_start + max(args.time_offset, 0.0)
        processed  = 0
        valid_cnt  = 0
        filtered_index = 0

        for _, msg, stamp in bag.read_messages(topics=[args.topic]):
            stamp_sec = stamp.to_sec()
            if stamp_sec < min_stamp:
                continue
            if filtered_index % max(args.every, 1) != 0:
                filtered_index += 1
                continue
            if args.max_frames > 0 and processed >= args.max_frames:
                break

            try:
                image = bridge.imgmsg_to_cv2(msg, desired_encoding=args.encoding)
            except CvBridgeError as exc:  # type: ignore[possibly-undefined]
                print(f"[WARN] skip frame {filtered_index}: {exc}", file=sys.stderr)
                filtered_index += 1
                continue

            y_tops, h_mms, confs, clipped, mask = detect_red_liquid(image, geom, rulers, args)
            h_fin = h_mm_final(h_mms)
            if h_fin is not None or (not has_rulers and y_tops[0] is not None):
                valid_cnt += 1

            frame_indices.append(filtered_index)
            stamps.append(stamp_sec)
            y_tops_all.append(y_tops)
            h_mms_all.append(h_mms)
            confs_all.append(confs)
            clipped_all.append(clipped)

            if processed % 50 == 0:
                if has_rulers:
                    h_str = f"{h_fin:.2f}mm" if h_fin is not None else "None"
                    h_parts = " ".join(
                        f"{n[0]}={h:.2f}" if h is not None else f"{n[0]}=?"
                        for n, h in zip(RULER_NAMES, h_mms)
                    )
                    print(f"[INFO] frame {filtered_index:5d}  t={stamp_sec-bag_start:.2f}s"
                          f"  {h_parts}  final={h_str}")
                else:
                    yt  = y_tops[0]
                    cnf = confs[0]
                    print(f"[INFO] frame {filtered_index:5d}  t={stamp_sec-bag_start:.2f}s"
                          f"  y_top={yt:.2f}px  conf={cnf:.2f}" if yt is not None
                          else f"[INFO] frame {filtered_index:5d}  y_top=None")

            if debug_dir and (processed % max(args.debug_every, 1) == 0):
                dbg = render_debug(image, geom, rulers, y_tops, h_mms, confs, clipped, mask, args)
                cv2.imwrite(str(debug_dir / f"debug_{filtered_index:06d}.png"), dbg)
            if debug_clear_dir and (processed % max(args.debug_every, 1) == 0):
                dbg_clear = render_debug_clear(image, geom, rulers, y_tops)
                cv2.imwrite(str(debug_clear_dir / f"debug_{filtered_index:06d}.png"), dbg_clear)

            processed      += 1
            filtered_index += 1

    # ---- Zero-point correction (Step 2) ------------------------------------
    h_corr_all: List[Optional[float]] = [None] * len(h_mms_all)
    if args.zero_correction_frames > 0 and has_rulers:
        h_finals_all = [h_mm_final(hms) for hms in h_mms_all]
        zero_pool = [h for h in h_finals_all[:args.zero_correction_frames] if h is not None]
        if zero_pool:
            h0 = float(np.median(zero_pool))
            h_corr_all = [
                (h - h0) if h is not None else None
                for h in h_finals_all
            ]
            print(f"[INFO] zero correction: h0={h0:.3f}mm "
                  f"(median of first {len(zero_pool)} valid frames)")
        else:
            print("[WARN] zero correction: no valid h_mm_final in first "
                  f"{args.zero_correction_frames} frames; correction skipped.",
                  file=sys.stderr)

    # ---- Temporal smoothing (Step 3) ----------------------------------------
    def _rolling_median(series: List[Optional[float]], window: int) -> List[Optional[float]]:
        if window <= 1:
            return series
        half = window // 2
        out: List[Optional[float]] = []
        for i in range(len(series)):
            seg = [v for v in series[max(0, i - half):i + half + 1] if v is not None]
            out.append(float(np.median(seg)) if seg else None)
        return out

    if args.smooth_frames > 1 and has_rulers:
        h_finals_raw = [h_mm_final(hms) for hms in h_mms_all]
        h_smooth_final = _rolling_median(h_finals_raw, args.smooth_frames)
        h_smooth_corr  = _rolling_median(h_corr_all,   args.smooth_frames)
        print(f"[INFO] temporal smoothing: window={args.smooth_frames} frames")
    else:
        h_smooth_final = [h_mm_final(hms) for hms in h_mms_all]
        h_smooth_corr  = list(h_corr_all)

    csv_path  = out_dir / f"{bag_path.stem}_red_top.csv"
    plot_path = out_dir / f"{bag_path.stem}_red_top_curve.png"
    save_csv(csv_path, frame_indices, stamps, y_tops_all, h_mms_all,
             confs_all, clipped_all, h_corr_all, h_smooth_final, h_smooth_corr, has_rulers)
    save_plot(plot_path, stamps, h_mms_all, y_tops_all, h_corr_all, h_smooth_corr, has_rulers)

    valid_ratio = (valid_cnt / processed) if processed > 0 else 0.0
    print(f"[OK] processed {processed} frames, {valid_cnt} valid ({100.0 * valid_ratio:.1f}%)")
    if has_rulers:
        all_finals = [h_mm_final(hms) for hms in h_mms_all]
        valid_finals = [v for v in all_finals if v is not None]
        if valid_finals:
            print(f"[OK] h_mm_final range: {min(valid_finals):.2f}mm ~ {max(valid_finals):.2f}mm")
    else:
        valid_ys = [yt[0] for yt in y_tops_all if yt[0] is not None]
        if valid_ys:
            print(f"[OK] y_top range: {min(valid_ys):.2f}px ~ {max(valid_ys):.2f}px")
    return 0


if __name__ == "__main__":
    sys.exit(main())
