#!/usr/bin/env python3
"""Generate the candidate delay-augmented Phase-Rejoin DISCRETE OCP.

The generated capsule is intentionally independent from the online
development Phase-Rejoin solver.  It freezes the WP3C dynamics and hard
command envelope, but does not yet claim the terminal empirical gate or
execution compatibility set required by the formal method.
"""

import argparse
import os
import pathlib
import sys

import casadi as ca
import numpy as np
import yaml

from generate_delay_augmented_phase_transition import load_contract
from spmpc_delay_augmented_phase_model import (
    state_layout,
    transition_expression,
)


PACKAGE_ROOT = pathlib.Path(__file__).resolve().parents[3]
DEFAULT_OUTPUT = PACKAGE_ROOT / "generated" / "acados"
MODEL_NAME = "spmpc_delay_augmented_phase"
SOLVER_CAPABILITY_SCHEMA_VERSION = 1
SOLVER_ID = "delay_augmented_phase_acados_candidate_v1"

CAP_DISCRETE_DYNAMICS = 1 << 0
CAP_AUGMENTED_INITIAL_STATE = 1 << 1
CAP_PUBLISHED_COMMAND_BOUNDS = 1 << 2
CAP_ROBOT_SPEED_BOUNDS = 1 << 3
CAP_PUBLISHED_RATE_BOUNDS = 1 << 4
CAP_TERMINAL_EMPIRICAL_GATE = 1 << 5
CAP_EXECUTION_COMPATIBILITY_SET = 1 << 6

WP3C_CAPABILITIES = (
    CAP_DISCRETE_DYNAMICS
    | CAP_AUGMENTED_INITIAL_STATE
    | CAP_PUBLISHED_COMMAND_BOUNDS
    | CAP_ROBOT_SPEED_BOUNDS
    | CAP_PUBLISHED_RATE_BOUNDS
)
FORMAL_REQUIRED_CAPABILITIES = (
    WP3C_CAPABILITIES
    | CAP_TERMINAL_EMPIRICAL_GATE
    | CAP_EXECUTION_COMPATIBILITY_SET
)


def _load_yaml(relative_path):
    with (PACKAGE_ROOT / relative_path).open("r", encoding="utf-8") as stream:
        return yaml.safe_load(stream)


def load_solver_spec():
    contract = load_contract()
    layout = state_layout(contract)
    platform = _load_yaml("config/platforms/scout_mini.yaml")["robot"]
    return {
        "model_name": MODEL_NAME,
        "solver_id": SOLVER_ID,
        "capability_schema_version": SOLVER_CAPABILITY_SCHEMA_VERSION,
        "capabilities": WP3C_CAPABILITIES,
        "formal_required_capabilities": FORMAL_REQUIRED_CAPABILITIES,
        "contract": contract,
        "layout": layout,
        "a_max": float(platform["a_max"]),
        "alpha_max": float(platform.get("alpha_max", 1.2)),
        "vs_max": float(platform["v_max"]),
    }


def build_symbolic_spec(spec):
    contract = spec["contract"]
    layout = spec["layout"]
    x = ca.SX.sym("x", layout["state_width"])
    q = ca.SX.sym("q", layout["control_width"])
    x_next, published = transition_expression(x, q, contract, layout)

    a_scale = spec["a_max"]
    alpha_scale = spec["alpha_max"]
    vs_scale = spec["vs_max"]
    slosh = x[6:10]
    stage_cost = (
        (q[0] / a_scale) ** 2
        + (q[1] / alpha_scale) ** 2
        + 0.05 * (q[2] / vs_scale) ** 2
        + 1.0e-4 * ca.dot(slosh, slosh)
    )
    terminal_cost = 1.0e-4 * ca.dot(slosh, slosh)

    state_indices = [3, 5]
    state_lower = [contract["linear"]["output_min"],
                   contract["angular"]["output_min"]]
    state_upper = [contract["linear"]["output_max"],
                   contract["angular"]["output_max"]]
    for index in range(layout["linear_buffer_count"]):
        state_indices.append(layout["linear_buffer_offset"] + index)
        state_lower.append(contract["linear"]["output_min"])
        state_upper.append(contract["linear"]["output_max"])
    for index in range(layout["angular_buffer_count"]):
        state_indices.append(layout["angular_buffer_offset"] + index)
        state_lower.append(contract["angular"]["output_min"])
        state_upper.append(contract["angular"]["output_max"])

    return {
        "x": x,
        "q": q,
        "x_next": x_next,
        "published": published,
        "stage_cost": stage_cost,
        "terminal_cost": terminal_cost,
        "idxbu": np.array([0, 1, 2], dtype=int),
        "lbu": np.array(
            [-spec["a_max"], -spec["alpha_max"], 0.0]),
        "ubu": np.array(
            [spec["a_max"], spec["alpha_max"], spec["vs_max"]]),
        "idxbx": np.array(state_indices, dtype=int),
        "lbx": np.array(state_lower),
        "ubx": np.array(state_upper),
        "lh": np.array([
            contract["linear"]["output_min"],
            contract["angular"]["output_min"],
        ]),
        "uh": np.array([
            contract["linear"]["output_max"],
            contract["angular"]["output_max"],
        ]),
    }


def _cpp_float(value):
    return format(float(value), ".17g")


def emit_solver_manifest(spec, output_root):
    output_root = pathlib.Path(output_root)
    output_root.mkdir(parents=True, exist_ok=True)
    contract = spec["contract"]
    layout = spec["layout"]
    path = output_root / "spmpc_delay_augmented_phase_solver_manifest.h"
    content = f"""// Generated by tools/codegen/acados/generate_delay_augmented_phase_acados.py.
// Candidate WP3C solver contract only; not a formal Scout release artifact.
#pragma once

#include <cstdint>

namespace spmpc_local_planner {{
namespace delay_augmented_phase_solver_manifest {{

constexpr int kCapabilitySchemaVersion = {spec['capability_schema_version']};
constexpr const char kSolverId[] = "{spec['solver_id']}";
constexpr const char kModelName[] = "{spec['model_name']}";
constexpr const char kIntegratorType[] = "DISCRETE";
constexpr int kExecutionContractSchemaVersion = {contract['schema_version']};
constexpr const char kContractId[] = "{contract['contract_id']}";
constexpr const char kContractHash[] = "{contract['contract_hash']}";
constexpr int kStateCount = {layout['state_width']};
constexpr int kControlCount = {layout['control_width']};
constexpr int kHorizonSteps = {contract['horizon_steps']};
constexpr int kExecutionFrontSteps = {contract['execution_front_steps']};
constexpr int kLiquidHorizonSteps = {contract['liquid_horizon_steps']};
constexpr int kLinearBufferOffset = {layout['linear_buffer_offset']};
constexpr int kLinearBufferCount = {layout['linear_buffer_count']};
constexpr int kAngularBufferOffset = {layout['angular_buffer_offset']};
constexpr int kAngularBufferCount = {layout['angular_buffer_count']};
constexpr int kStateBoundCount = {2 + layout['linear_buffer_count'] + layout['angular_buffer_count']};
constexpr int kInitialStateBoundCount = {layout['state_width']};
constexpr int kTerminalStateBoundCount = kStateBoundCount;
constexpr int kControlBoundCount = {layout['control_width']};
constexpr int kPublishedCommandConstraintCount = 2;
constexpr int kTerminalPublishedCommandConstraintCount = 0;
constexpr double kDt = {_cpp_float(contract['dt'])};
constexpr double kLinearDelaySec = {_cpp_float(contract['linear']['delay_sec'])};
constexpr double kAngularDelaySec = {_cpp_float(contract['angular']['delay_sec'])};
constexpr int kLinearIntegerDelaySteps = {contract['linear']['integer_delay_steps']};
constexpr int kAngularIntegerDelaySteps = {contract['angular']['integer_delay_steps']};
constexpr double kLinearFractionalDelaySec = {_cpp_float(contract['linear']['fractional_delay_sec'])};
constexpr double kAngularFractionalDelaySec = {_cpp_float(contract['angular']['fractional_delay_sec'])};
constexpr double kLinearTimeConstantSec = {_cpp_float(contract['linear']['time_constant_sec'])};
constexpr double kAngularTimeConstantSec = {_cpp_float(contract['angular']['time_constant_sec'])};
constexpr double kLinearPositiveGain = {_cpp_float(contract['linear']['positive_gain'])};
constexpr double kLinearNegativeGain = {_cpp_float(contract['linear']['negative_gain'])};
constexpr double kAngularPositiveGain = {_cpp_float(contract['angular']['positive_gain'])};
constexpr double kAngularNegativeGain = {_cpp_float(contract['angular']['negative_gain'])};
constexpr double kLinearDeadzone = {_cpp_float(contract['linear']['deadzone'])};
constexpr double kAngularDeadzone = {_cpp_float(contract['angular']['deadzone'])};
constexpr double kLinearOutputMin = {_cpp_float(contract['linear']['output_min'])};
constexpr double kLinearOutputMax = {_cpp_float(contract['linear']['output_max'])};
constexpr double kAngularOutputMin = {_cpp_float(contract['angular']['output_min'])};
constexpr double kAngularOutputMax = {_cpp_float(contract['angular']['output_max'])};
constexpr double kAccelerationMax = {_cpp_float(spec['a_max'])};
constexpr double kAngularAccelerationMax = {_cpp_float(spec['alpha_max'])};
constexpr double kProgressRateMax = {_cpp_float(spec['vs_max'])};

constexpr std::uint32_t kDiscreteDynamics = {CAP_DISCRETE_DYNAMICS}u;
constexpr std::uint32_t kAugmentedInitialState = {CAP_AUGMENTED_INITIAL_STATE}u;
constexpr std::uint32_t kPublishedCommandBounds = {CAP_PUBLISHED_COMMAND_BOUNDS}u;
constexpr std::uint32_t kRobotSpeedBounds = {CAP_ROBOT_SPEED_BOUNDS}u;
constexpr std::uint32_t kPublishedRateBounds = {CAP_PUBLISHED_RATE_BOUNDS}u;
constexpr std::uint32_t kTerminalEmpiricalGate = {CAP_TERMINAL_EMPIRICAL_GATE}u;
constexpr std::uint32_t kExecutionCompatibilitySet = {CAP_EXECUTION_COMPATIBILITY_SET}u;
constexpr std::uint32_t kCapabilities = {spec['capabilities']}u;
constexpr std::uint32_t kFormalRequiredCapabilities = {spec['formal_required_capabilities']}u;

}}  // namespace delay_augmented_phase_solver_manifest
}}  // namespace spmpc_local_planner
"""
    path.write_text(content, encoding="utf-8")
    return path


def _import_acados_template():
    try:
        from acados_template import AcadosModel, AcadosOcp, AcadosOcpSolver
        return AcadosModel, AcadosOcp, AcadosOcpSolver
    except ImportError:
        source = os.environ.get("ACADOS_SOURCE_DIR", "")
        candidate = pathlib.Path(source) / "interfaces" / "acados_template"
        if source and candidate.is_dir():
            sys.path.insert(0, str(candidate))
            from acados_template import AcadosModel, AcadosOcp, AcadosOcpSolver
            return AcadosModel, AcadosOcp, AcadosOcpSolver
        raise


def build_ocp(spec):
    AcadosModel, AcadosOcp, _ = _import_acados_template()
    symbolic = build_symbolic_spec(spec)
    model = AcadosModel()
    model.name = MODEL_NAME
    model.x = symbolic["x"]
    model.u = symbolic["q"]
    model.disc_dyn_expr = symbolic["x_next"]

    ocp = AcadosOcp()
    ocp.model = model
    ocp.solver_options.N_horizon = spec["contract"]["horizon_steps"]
    ocp.solver_options.tf = (
        spec["contract"]["horizon_steps"] * spec["contract"]["dt"])
    ocp.cost.cost_type = "EXTERNAL"
    ocp.cost.cost_type_e = "EXTERNAL"
    ocp.model.cost_expr_ext_cost = symbolic["stage_cost"]
    ocp.model.cost_expr_ext_cost_e = symbolic["terminal_cost"]

    ocp.constraints.idxbu = symbolic["idxbu"]
    ocp.constraints.lbu = symbolic["lbu"]
    ocp.constraints.ubu = symbolic["ubu"]
    ocp.constraints.idxbx = symbolic["idxbx"]
    ocp.constraints.lbx = symbolic["lbx"]
    ocp.constraints.ubx = symbolic["ubx"]
    ocp.constraints.idxbx_e = symbolic["idxbx"]
    ocp.constraints.lbx_e = symbolic["lbx"]
    ocp.constraints.ubx_e = symbolic["ubx"]
    ocp.constraints.x0 = np.zeros(spec["layout"]["state_width"])
    ocp.model.con_h_expr = symbolic["published"]
    ocp.model.con_h_expr_0 = symbolic["published"]
    ocp.constraints.lh = symbolic["lh"]
    ocp.constraints.uh = symbolic["uh"]
    ocp.constraints.lh_0 = symbolic["lh"]
    ocp.constraints.uh_0 = symbolic["uh"]

    ocp.solver_options.integrator_type = "DISCRETE"
    ocp.solver_options.qp_solver = "PARTIAL_CONDENSING_HPIPM"
    ocp.solver_options.hessian_approx = "EXACT"
    ocp.solver_options.regularize_method = "PROJECT"
    ocp.solver_options.levenberg_marquardt = 1.0e-3
    ocp.solver_options.nlp_solver_type = "SQP_RTI"
    return ocp


def generate(output_root, build=True):
    _, _, AcadosOcpSolver = _import_acados_template()
    output_root = pathlib.Path(output_root).resolve()
    spec = load_solver_spec()
    manifest = emit_solver_manifest(spec, output_root)
    ocp = build_ocp(spec)
    export_dir = output_root / MODEL_NAME
    export_dir.mkdir(parents=True, exist_ok=True)
    ocp.code_gen_opts.code_export_directory = str(export_dir)
    json_path = export_dir / f"acados_ocp_{MODEL_NAME}.json"
    AcadosOcpSolver.generate(ocp, json_file=str(json_path), verbose=True)
    if build:
        AcadosOcpSolver.build(str(export_dir), with_cython=False, verbose=True)
    return manifest, json_path


def check():
    spec = load_solver_spec()
    symbolic = build_symbolic_spec(spec)
    if symbolic["x_next"].shape != (spec["layout"]["state_width"], 1):
        raise RuntimeError("delay-augmented discrete state width mismatch")
    if symbolic["published"].shape != (2, 1):
        raise RuntimeError("published-command constraint width mismatch")
    if spec["capabilities"] & spec["formal_required_capabilities"] != spec["capabilities"]:
        raise RuntimeError("invalid solver capability mask")
    print(
        "[check] delay-augmented Phase-Rejoin DISCRETE OCP",
        f"nx={spec['layout']['state_width']}",
        f"nu={spec['layout']['control_width']}",
        f"N={spec['contract']['horizon_steps']}",
        f"nbx={len(symbolic['idxbx'])}",
        "nh=2",
        f"capabilities=0x{spec['capabilities']:x}",
        f"hash={spec['contract']['contract_hash']}",
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", default=str(DEFAULT_OUTPUT))
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--no-build", action="store_true")
    args = parser.parse_args()
    spec = load_solver_spec()
    manifest = emit_solver_manifest(spec, args.output_dir)
    if args.check:
        check()
        print(f"[ok] solver manifest generated -> {manifest}")
        return 0
    generated = generate(args.output_dir, build=not args.no_build)
    for path in generated:
        print(f"[ok] generated {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
