"""Contract and schema helpers for the future mainline acados generator."""

from .contract_source import (
    STAGE0_CONTRACT_SHA256,
    ContractSourceError,
    Stage0ContractReference,
    load_stage0_contract_reference,
)
from .layout import (
    BASE_STATE_COUNT,
    CONTROL_COUNT,
    COST_SCHEMA,
    DEFAULT_DT_SEC,
    DEFAULT_HORIZON_STEPS,
    DISCRETIZATION_SCHEMA,
    EXECUTION_SUBSEGMENT_SLOTS,
    LAYOUT_SCHEMA_VERSION,
    LAYOUT_SCOPE,
    MAX_RETAINED_COMMANDS_PER_CHANNEL,
    MODEL_ID,
    LayoutError,
    LayoutPurpose,
    LayoutSpec,
    MainlineLayoutScaffold,
    build_layout,
    build_synthetic_layout,
    layout_from_dict,
)
from .manifest import (
    MANIFEST_SCHEMA_VERSION,
    MANIFEST_STATUS,
    ManifestError,
    build_scaffold_manifest,
    canonical_json,
    scaffold_identity_hash,
    sha256_json,
    validate_scaffold_manifest,
)

__all__ = [
    "BASE_STATE_COUNT",
    "CONTROL_COUNT",
    "COST_SCHEMA",
    "DEFAULT_DT_SEC",
    "DEFAULT_HORIZON_STEPS",
    "DISCRETIZATION_SCHEMA",
    "EXECUTION_SUBSEGMENT_SLOTS",
    "LAYOUT_SCHEMA_VERSION",
    "LAYOUT_SCOPE",
    "MANIFEST_SCHEMA_VERSION",
    "MANIFEST_STATUS",
    "MAX_RETAINED_COMMANDS_PER_CHANNEL",
    "MODEL_ID",
    "STAGE0_CONTRACT_SHA256",
    "ContractSourceError",
    "LayoutError",
    "LayoutPurpose",
    "LayoutSpec",
    "MainlineLayoutScaffold",
    "ManifestError",
    "Stage0ContractReference",
    "build_layout",
    "build_scaffold_manifest",
    "build_synthetic_layout",
    "canonical_json",
    "layout_from_dict",
    "load_stage0_contract_reference",
    "scaffold_identity_hash",
    "sha256_json",
    "validate_scaffold_manifest",
]
