# R8 liquid U3 GPU campaign static-audit profile; parser tools only.
# Every candidate and each of the 131 ET_REL inputs is exact-root enumerated.
abi <abi/4.0>,

include <tunables/global>

profile r8-liquid-motion-gauge-gpu-static-audit-20260812t073037z-v11 flags=(attach_disconnected,mediate_deleted) {
  userns create,

  /usr/bin/bwrap rix,
  /usr/bin/env rix,
  /usr/bin/prlimit rix,
  /usr/bin/python3 rix,
  /usr/bin/python3.12 rix,
  /usr/bin/file rix,
  /usr/bin/readelf rix,
  /usr/bin/x86_64-linux-gnu-readelf rix,
  /usr/bin/sha256sum rix,
  /usr/local/cuda-12.8/bin/cuobjdump rix,

  / r,
  /usr/ r,
  /usr/lib/** mr,
  /usr/lib64/** mr,
  /lib/** mr,
  /lib64/** mr,
  /etc/magic r,

  /home/ r,
  /home/zrj/ r,
  /home/zrj/scout_liquid_lab/ r,
  /home/zrj/scout_liquid_lab/build/ r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/ r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/ r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/artifacts/ r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/artifacts/DualSPHysics5.4_linux64 r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/ r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/ r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/ r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JXml.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/tinystr.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/tinyxml.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/tinyxmlerror.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/tinyxmlparser.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JMotion.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JMotionData.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JMotionList.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JMotionMov.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JMotionObj.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JMotionPos.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsMotion.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/Functions.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/FunGeo3d.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/FunSphKernelsCfg.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JAppInfo.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JBinaryData.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JCfgRunBase.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDataArrays.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JException.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JLinearValue.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JLog2.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JObject.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JOutputCsv.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JRadixSort.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JRangeFilter.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JReadDatafile.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSaveCsv2.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSpVtkData.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSpVtkShape.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JTimeControl.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JTrianglesMesh.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/randomc.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsphConfig.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsPips.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JPartDataBi4.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JPartDataHead.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsPartFloatSave.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsPartMotionSave.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JPartFloatInfoBi4.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JPartMotRefBi4Save.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JPartOutBi4Save.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JCaseCtes.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JCaseEParms.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JCaseParts.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JCaseProperties.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JArraysCpu.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JCellDivCpu.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDebugSphCpu.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphCfgRun.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JComputeMotionRef.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsDcell.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsDamping.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsExtraData.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsGaugeItem.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsGaugeSystem.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsPartsOut.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsSaveDt.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphShifting.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphShiftingAdv.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSph.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsAccInput.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphCpu.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphCpu_mdbc.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphCpu_preloop.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsInitialize.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphMk.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsOutputParts.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsPartsInit.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsFixedDt.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsViscoInput.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsOutputTime.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsTimers.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JWaveSpectrumGpu.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/main.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JCellDivCpuSingle.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JPartsLoad4.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphCpuSingle.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/FunctionsCuda.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JObjectGpu.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JArraysGpu.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDebugSphGpu.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JCellDivGpu.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphGpu.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsGpuInfo.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JCellDivGpuSingle.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphGpuSingle.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JCellDivGpu_ker.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JCellDivGpuSingle_ker.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsPips_ker.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsGauge_ker.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JReduSum_ker.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphShifting_ker.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsAccInput_ker.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphGpu_ker.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphGpuSimple_ker.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JWaveOrder2_ker.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JMLPistonsGpu.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JRelaxZonesGpu.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JRelaxZone_ker.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JChronoGeoObj.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JChronoObjects.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsMooredFloatings.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsFtForcePoints.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphCpu_InOut.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphCpuSingle_InOut.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphInOut.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphInOutZone.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphInOutGridData.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphInOutPoints.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphInOutVel.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphInOutVelAwas.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphInOutZsurf.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSimpleNeigs.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphGpuSingle_InOut.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JMeshData.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JMeshTDatas.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JMeshTDatasLoad.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JMeshTDatasSave.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JMeshTDatasDsVel.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JMeshTDatasXml.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphVRes.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphVResZone.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphCpuSingle_VRes.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphGpuSingle_VRes.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphCpu_VRes.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JCaseVRes.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JVResDataLimits.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsVresData.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JBoxDef.o r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphFlexStruc.o r,

  owner /proc/** r,
  owner /proc/*/uid_map w,
  owner /proc/*/gid_map w,
  owner /proc/*/setgroups w,
  /proc/filesystems r,
  /proc/sys/kernel/overflowuid r,
  /proc/sys/kernel/overflowgid r,
  /proc/sys/user/max_user_namespaces w,
  /dev/null rw,
  /dev/zero r,
  /dev/random r,
  /dev/urandom r,

  mount options=(rw, silent, rslave) -> /,
  mount fstype=tmpfs options=(rw, nosuid, nodev) -> /tmp/,
  mount options=(rw, rbind) /tmp/newroot/ -> /tmp/newroot/,
  pivot_root oldroot=/tmp/oldroot/ /tmp/,
  mount options=(rw, silent, rprivate) -> /oldroot/,
  umount /oldroot/,
  pivot_root oldroot=/newroot/ /newroot/,
  umount /,
  mount options=(rw, rbind) /oldroot/usr/ -> /newroot/usr/,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/usr/,
  mount fstype=tmpfs options=(rw, nosuid, nodev) -> /newroot/audit/,
  mount options=(rw, rbind) /oldroot/etc/magic -> /newroot/etc/magic,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/etc/magic,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/artifacts/DualSPHysics5.4_linux64 -> /newroot/audit/input/DualSPHysics5.4_linux64,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/DualSPHysics5.4_linux64,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JXml.o -> /newroot/audit/input/JXml.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/tinystr.o -> /newroot/audit/input/tinystr.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/tinyxml.o -> /newroot/audit/input/tinyxml.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/tinyxmlerror.o -> /newroot/audit/input/tinyxmlerror.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/tinyxmlparser.o -> /newroot/audit/input/tinyxmlparser.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JMotion.o -> /newroot/audit/input/JMotion.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JMotionData.o -> /newroot/audit/input/JMotionData.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JMotionList.o -> /newroot/audit/input/JMotionList.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JMotionMov.o -> /newroot/audit/input/JMotionMov.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JMotionObj.o -> /newroot/audit/input/JMotionObj.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JMotionPos.o -> /newroot/audit/input/JMotionPos.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsMotion.o -> /newroot/audit/input/JDsMotion.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/Functions.o -> /newroot/audit/input/Functions.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/FunGeo3d.o -> /newroot/audit/input/FunGeo3d.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/FunSphKernelsCfg.o -> /newroot/audit/input/FunSphKernelsCfg.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JAppInfo.o -> /newroot/audit/input/JAppInfo.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JBinaryData.o -> /newroot/audit/input/JBinaryData.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JCfgRunBase.o -> /newroot/audit/input/JCfgRunBase.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDataArrays.o -> /newroot/audit/input/JDataArrays.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JException.o -> /newroot/audit/input/JException.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JLinearValue.o -> /newroot/audit/input/JLinearValue.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JLog2.o -> /newroot/audit/input/JLog2.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JObject.o -> /newroot/audit/input/JObject.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JOutputCsv.o -> /newroot/audit/input/JOutputCsv.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JRadixSort.o -> /newroot/audit/input/JRadixSort.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JRangeFilter.o -> /newroot/audit/input/JRangeFilter.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JReadDatafile.o -> /newroot/audit/input/JReadDatafile.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSaveCsv2.o -> /newroot/audit/input/JSaveCsv2.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSpVtkData.o -> /newroot/audit/input/JSpVtkData.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSpVtkShape.o -> /newroot/audit/input/JSpVtkShape.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JTimeControl.o -> /newroot/audit/input/JTimeControl.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JTrianglesMesh.o -> /newroot/audit/input/JTrianglesMesh.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/randomc.o -> /newroot/audit/input/randomc.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsphConfig.o -> /newroot/audit/input/JDsphConfig.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsPips.o -> /newroot/audit/input/JDsPips.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JPartDataBi4.o -> /newroot/audit/input/JPartDataBi4.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JPartDataHead.o -> /newroot/audit/input/JPartDataHead.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsPartFloatSave.o -> /newroot/audit/input/JDsPartFloatSave.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsPartMotionSave.o -> /newroot/audit/input/JDsPartMotionSave.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JPartFloatInfoBi4.o -> /newroot/audit/input/JPartFloatInfoBi4.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JPartMotRefBi4Save.o -> /newroot/audit/input/JPartMotRefBi4Save.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JPartOutBi4Save.o -> /newroot/audit/input/JPartOutBi4Save.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JCaseCtes.o -> /newroot/audit/input/JCaseCtes.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JCaseEParms.o -> /newroot/audit/input/JCaseEParms.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JCaseParts.o -> /newroot/audit/input/JCaseParts.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JCaseProperties.o -> /newroot/audit/input/JCaseProperties.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JArraysCpu.o -> /newroot/audit/input/JArraysCpu.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JCellDivCpu.o -> /newroot/audit/input/JCellDivCpu.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDebugSphCpu.o -> /newroot/audit/input/JDebugSphCpu.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphCfgRun.o -> /newroot/audit/input/JSphCfgRun.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JComputeMotionRef.o -> /newroot/audit/input/JComputeMotionRef.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsDcell.o -> /newroot/audit/input/JDsDcell.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsDamping.o -> /newroot/audit/input/JDsDamping.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsExtraData.o -> /newroot/audit/input/JDsExtraData.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsGaugeItem.o -> /newroot/audit/input/JDsGaugeItem.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsGaugeSystem.o -> /newroot/audit/input/JDsGaugeSystem.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsPartsOut.o -> /newroot/audit/input/JDsPartsOut.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsSaveDt.o -> /newroot/audit/input/JDsSaveDt.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphShifting.o -> /newroot/audit/input/JSphShifting.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphShiftingAdv.o -> /newroot/audit/input/JSphShiftingAdv.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSph.o -> /newroot/audit/input/JSph.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsAccInput.o -> /newroot/audit/input/JDsAccInput.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphCpu.o -> /newroot/audit/input/JSphCpu.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphCpu_mdbc.o -> /newroot/audit/input/JSphCpu_mdbc.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphCpu_preloop.o -> /newroot/audit/input/JSphCpu_preloop.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsInitialize.o -> /newroot/audit/input/JDsInitialize.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphMk.o -> /newroot/audit/input/JSphMk.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsOutputParts.o -> /newroot/audit/input/JDsOutputParts.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsPartsInit.o -> /newroot/audit/input/JDsPartsInit.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsFixedDt.o -> /newroot/audit/input/JDsFixedDt.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsViscoInput.o -> /newroot/audit/input/JDsViscoInput.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsOutputTime.o -> /newroot/audit/input/JDsOutputTime.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsTimers.o -> /newroot/audit/input/JDsTimers.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JWaveSpectrumGpu.o -> /newroot/audit/input/JWaveSpectrumGpu.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/main.o -> /newroot/audit/input/main.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JCellDivCpuSingle.o -> /newroot/audit/input/JCellDivCpuSingle.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JPartsLoad4.o -> /newroot/audit/input/JPartsLoad4.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphCpuSingle.o -> /newroot/audit/input/JSphCpuSingle.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/FunctionsCuda.o -> /newroot/audit/input/FunctionsCuda.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JObjectGpu.o -> /newroot/audit/input/JObjectGpu.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JArraysGpu.o -> /newroot/audit/input/JArraysGpu.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDebugSphGpu.o -> /newroot/audit/input/JDebugSphGpu.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JCellDivGpu.o -> /newroot/audit/input/JCellDivGpu.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphGpu.o -> /newroot/audit/input/JSphGpu.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsGpuInfo.o -> /newroot/audit/input/JDsGpuInfo.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JCellDivGpuSingle.o -> /newroot/audit/input/JCellDivGpuSingle.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphGpuSingle.o -> /newroot/audit/input/JSphGpuSingle.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JCellDivGpu_ker.o -> /newroot/audit/input/JCellDivGpu_ker.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JCellDivGpuSingle_ker.o -> /newroot/audit/input/JCellDivGpuSingle_ker.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsPips_ker.o -> /newroot/audit/input/JDsPips_ker.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsGauge_ker.o -> /newroot/audit/input/JDsGauge_ker.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JReduSum_ker.o -> /newroot/audit/input/JReduSum_ker.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphShifting_ker.o -> /newroot/audit/input/JSphShifting_ker.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsAccInput_ker.o -> /newroot/audit/input/JDsAccInput_ker.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphGpu_ker.o -> /newroot/audit/input/JSphGpu_ker.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphGpuSimple_ker.o -> /newroot/audit/input/JSphGpuSimple_ker.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JWaveOrder2_ker.o -> /newroot/audit/input/JWaveOrder2_ker.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JMLPistonsGpu.o -> /newroot/audit/input/JMLPistonsGpu.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JRelaxZonesGpu.o -> /newroot/audit/input/JRelaxZonesGpu.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JRelaxZone_ker.o -> /newroot/audit/input/JRelaxZone_ker.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JChronoGeoObj.o -> /newroot/audit/input/JChronoGeoObj.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JChronoObjects.o -> /newroot/audit/input/JChronoObjects.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsMooredFloatings.o -> /newroot/audit/input/JDsMooredFloatings.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsFtForcePoints.o -> /newroot/audit/input/JDsFtForcePoints.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphCpu_InOut.o -> /newroot/audit/input/JSphCpu_InOut.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphCpuSingle_InOut.o -> /newroot/audit/input/JSphCpuSingle_InOut.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphInOut.o -> /newroot/audit/input/JSphInOut.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphInOutZone.o -> /newroot/audit/input/JSphInOutZone.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphInOutGridData.o -> /newroot/audit/input/JSphInOutGridData.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphInOutPoints.o -> /newroot/audit/input/JSphInOutPoints.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphInOutVel.o -> /newroot/audit/input/JSphInOutVel.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphInOutVelAwas.o -> /newroot/audit/input/JSphInOutVelAwas.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphInOutZsurf.o -> /newroot/audit/input/JSphInOutZsurf.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSimpleNeigs.o -> /newroot/audit/input/JSimpleNeigs.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphGpuSingle_InOut.o -> /newroot/audit/input/JSphGpuSingle_InOut.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JMeshData.o -> /newroot/audit/input/JMeshData.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JMeshTDatas.o -> /newroot/audit/input/JMeshTDatas.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JMeshTDatasLoad.o -> /newroot/audit/input/JMeshTDatasLoad.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JMeshTDatasSave.o -> /newroot/audit/input/JMeshTDatasSave.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JMeshTDatasDsVel.o -> /newroot/audit/input/JMeshTDatasDsVel.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JMeshTDatasXml.o -> /newroot/audit/input/JMeshTDatasXml.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphVRes.o -> /newroot/audit/input/JSphVRes.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphVResZone.o -> /newroot/audit/input/JSphVResZone.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphCpuSingle_VRes.o -> /newroot/audit/input/JSphCpuSingle_VRes.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphGpuSingle_VRes.o -> /newroot/audit/input/JSphGpuSingle_VRes.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphCpu_VRes.o -> /newroot/audit/input/JSphCpu_VRes.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JCaseVRes.o -> /newroot/audit/input/JCaseVRes.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JVResDataLimits.o -> /newroot/audit/input/JVResDataLimits.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsVresData.o -> /newroot/audit/input/JDsVresData.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JBoxDef.o -> /newroot/audit/input/JBoxDef.o,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSphFlexStruc.o -> /newroot/audit/input/JSphFlexStruc.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JXml.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/tinystr.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/tinyxml.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/tinyxmlerror.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/tinyxmlparser.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JMotion.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JMotionData.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JMotionList.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JMotionMov.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JMotionObj.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JMotionPos.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JDsMotion.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/Functions.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/FunGeo3d.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/FunSphKernelsCfg.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JAppInfo.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JBinaryData.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JCfgRunBase.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JDataArrays.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JException.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JLinearValue.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JLog2.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JObject.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JOutputCsv.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JRadixSort.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JRangeFilter.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JReadDatafile.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JSaveCsv2.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JSpVtkData.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JSpVtkShape.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JTimeControl.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JTrianglesMesh.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/randomc.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JDsphConfig.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JDsPips.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JPartDataBi4.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JPartDataHead.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JDsPartFloatSave.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JDsPartMotionSave.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JPartFloatInfoBi4.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JPartMotRefBi4Save.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JPartOutBi4Save.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JCaseCtes.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JCaseEParms.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JCaseParts.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JCaseProperties.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JArraysCpu.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JCellDivCpu.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JDebugSphCpu.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JSphCfgRun.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JComputeMotionRef.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JDsDcell.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JDsDamping.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JDsExtraData.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JDsGaugeItem.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JDsGaugeSystem.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JDsPartsOut.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JDsSaveDt.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JSphShifting.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JSphShiftingAdv.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JSph.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JDsAccInput.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JSphCpu.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JSphCpu_mdbc.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JSphCpu_preloop.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JDsInitialize.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JSphMk.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JDsOutputParts.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JDsPartsInit.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JDsFixedDt.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JDsViscoInput.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JDsOutputTime.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JDsTimers.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JWaveSpectrumGpu.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/main.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JCellDivCpuSingle.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JPartsLoad4.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JSphCpuSingle.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/FunctionsCuda.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JObjectGpu.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JArraysGpu.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JDebugSphGpu.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JCellDivGpu.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JSphGpu.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JDsGpuInfo.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JCellDivGpuSingle.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JSphGpuSingle.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JCellDivGpu_ker.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JCellDivGpuSingle_ker.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JDsPips_ker.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JDsGauge_ker.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JReduSum_ker.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JSphShifting_ker.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JDsAccInput_ker.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JSphGpu_ker.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JSphGpuSimple_ker.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JWaveOrder2_ker.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JMLPistonsGpu.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JRelaxZonesGpu.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JRelaxZone_ker.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JChronoGeoObj.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JChronoObjects.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JDsMooredFloatings.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JDsFtForcePoints.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JSphCpu_InOut.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JSphCpuSingle_InOut.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JSphInOut.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JSphInOutZone.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JSphInOutGridData.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JSphInOutPoints.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JSphInOutVel.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JSphInOutVelAwas.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JSphInOutZsurf.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JSimpleNeigs.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JSphGpuSingle_InOut.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JMeshData.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JMeshTDatas.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JMeshTDatasLoad.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JMeshTDatasSave.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JMeshTDatasDsVel.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JMeshTDatasXml.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JSphVRes.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JSphVResZone.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JSphCpuSingle_VRes.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JSphGpuSingle_VRes.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JSphCpu_VRes.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JCaseVRes.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JVResDataLimits.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JDsVresData.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JBoxDef.o,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/audit/input/JSphFlexStruc.o,

  /tmp/newroot/ rw,
  /tmp/newroot/** rw,
  /tmp/oldroot/ rw,
  /tmp/oldroot/** rw,
  /newroot/usr/ rw,
  /newroot/lib wl,
  /newroot/lib64 wl,
  /newroot/etc/ rw,
  /newroot/etc/magic rw,
  /newroot/audit/ rw,
  /newroot/audit/input/ rw,
  /newroot/audit/input/** rw,
  /newroot/audit/tmp/ rw,
  /audit/input/** r,
  /audit/tmp/ rw,
  /audit/tmp/** rw,

  capability sys_admin,
  capability sys_ptrace,
  capability sys_resource,
  capability setpcap,
  capability net_admin,
  ptrace (read, readby) peer=r8-liquid-motion-gauge-gpu-static-audit-20260812t073037z-v11,
  signal (send, receive) peer=r8-liquid-motion-gauge-gpu-static-audit-20260812t073037z-v11,
  network unix dgram,
  network netlink raw,

  # No shell, compiler, linker, Make, candidate execute, host writable bind,
  # guest proc/dev, GPU device or stream/packet network permission exists.
}
