# STATIC TEMPLATE ONLY. Render through the byte-pinned v9 generator.
abi <abi/4.0>,
include <tunables/global>

profile r8-liquid-s5b0-primary-bsmooth-b01-20260812t110635z-v9 flags=(attach_disconnected,mediate_deleted) {
  userns create,
  /usr/bin/bwrap rix,
  /runtime/candidate rix,

  / r,
  /usr/ r,
  /usr/** mr,
  /lib/** mr,
  /lib64/** mr,
  /etc/ld.so.cache r,
  /sys/ r,
  /sys/** r,

  /home/ r,
  /home/zrj/ r,
  /home/zrj/scout_liquid_lab/ r,
  /home/zrj/scout_liquid_lab/replays/ r,
  /home/zrj/scout_liquid_lab/replays/s5b0_primary_bsmooth_b01_20260812T110635Z_v9.stage.partial/ r,
  /home/zrj/scout_liquid_lab/replays/s5b0_primary_bsmooth_b01_20260812T110635Z_v9.stage.partial/runtime/ r,
  /home/zrj/scout_liquid_lab/replays/s5b0_primary_bsmooth_b01_20260812T110635Z_v9.stage.partial/runtime/** r,
  /home/zrj/scout_liquid_lab/replays/s5b0_primary_bsmooth_b01_20260812T110635Z_v9.stage.partial/case/ r,
  /home/zrj/scout_liquid_lab/replays/s5b0_primary_bsmooth_b01_20260812T110635Z_v9.stage.partial/case/** r,
  /home/zrj/scout_liquid_lab/replays/s5b0_primary_bsmooth_b01_20260812T110635Z_v9.stage.partial/restart/ r,
  /home/zrj/scout_liquid_lab/replays/s5b0_primary_bsmooth_b01_20260812T110635Z_v9.stage.partial/restart/** r,
  /home/zrj/scout_liquid_lab/replays/s5b0_primary_bsmooth_b01_20260812T110635Z_v9.stage.partial/guest-output/ rw,
  /home/zrj/scout_liquid_lab/replays/s5b0_primary_bsmooth_b01_20260812T110635Z_v9.stage.partial/guest-output/** rwk,

  owner /proc/** r,
  owner /proc/*/uid_map w,
  owner /proc/*/gid_map w,
  owner /proc/*/setgroups w,
  /proc/filesystems r,
  /proc/sys/kernel/overflowuid r,
  /proc/sys/kernel/overflowgid r,
  /proc/sys/user/max_user_namespaces w,
  /dev/null rw,
  /dev/zero r,
  /dev/random r,
  /dev/urandom r,
  /dev/nvidia0 rw,
  /dev/nvidiactl rw,
  /dev/nvidia-uvm rw,
  /dev/nvidia-uvm-tools rw,

  mount options=(rw, silent, rslave) -> /,
  mount fstype=tmpfs options=(rw, nosuid, nodev) -> /tmp/,
  mount options=(rw, rbind) /tmp/newroot/ -> /tmp/newroot/,
  pivot_root oldroot=/tmp/oldroot/ /tmp/,
  mount options=(rw, silent, rprivate) -> /oldroot/,
  umount /oldroot/,
  pivot_root oldroot=/newroot/ /newroot/,
  umount /,
  mount options=(rw, rbind) /oldroot/usr/ -> /newroot/usr/,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/usr/,
  mount options=(rw, bind) /oldroot/etc/ld.so.cache -> /newroot/etc/ld.so.cache,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/etc/ld.so.cache,
  mount fstype=proc options=(rw, nosuid, nodev, noexec) proc -> /newroot/proc/,
  mount fstype=tmpfs options=(rw, nosuid) -> /newroot/dev/,
  mount options=(rw, bind) /oldroot/dev/nvidia0 -> /newroot/dev/nvidia0,
  mount options=(rw, bind) /oldroot/dev/nvidiactl -> /newroot/dev/nvidiactl,
  mount options=(rw, bind) /oldroot/dev/nvidia-uvm -> /newroot/dev/nvidia-uvm,
  mount options=(rw, bind) /oldroot/dev/nvidia-uvm-tools -> /newroot/dev/nvidia-uvm-tools,
  mount options=(rw, rbind) /oldroot/sys/ -> /newroot/sys/,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/sys/,
  mount fstype=tmpfs options=(rw, nosuid, nodev) -> /newroot/tmp/,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/replays/s5b0_primary_bsmooth_b01_20260812T110635Z_v9.stage.partial/runtime/ -> /newroot/runtime/,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/runtime/,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/replays/s5b0_primary_bsmooth_b01_20260812T110635Z_v9.stage.partial/case/ -> /newroot/case/,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/case/,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/replays/s5b0_primary_bsmooth_b01_20260812T110635Z_v9.stage.partial/restart/ -> /newroot/restart/,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/restart/,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/replays/s5b0_primary_bsmooth_b01_20260812T110635Z_v9.stage.partial/guest-output/ -> /newroot/output/,
  remount options=(rw, nosuid, nodev, bind, silent, relatime) /newroot/output/,

  /tmp/newroot/ rw,
  /tmp/newroot/** rw,
  /tmp/oldroot/ rw,
  /tmp/oldroot/** rw,
  /newroot/usr/ rw,
  /newroot/lib wl,
  /newroot/lib64 wl,
  /newroot/etc/ rw,
  /newroot/etc/ld.so.cache rw,
  /newroot/proc/ rw,
  /newroot/dev/ rw,
  /newroot/dev/nvidia0 rw,
  /newroot/dev/nvidiactl rw,
  /newroot/dev/nvidia-uvm rw,
  /newroot/dev/nvidia-uvm-tools rw,
  /newroot/sys/ rw,
  /newroot/runtime/ rw,
  /newroot/case/ rw,
  /newroot/restart/ rw,
  /newroot/output/ rw,
  /newroot/tmp/ rw,
  /runtime/ r,
  /runtime/** mr,
  /case/ r,
  /case/** r,
  /restart/ r,
  /restart/** r,
  /output/ rw,
  /output/** rwk,
  /tmp/ rw,
  /tmp/** rwk,

  capability sys_admin,
  capability sys_ptrace,
  capability sys_resource,
  capability setpcap,
  capability net_admin,
  ptrace (read, readby) peer=r8-liquid-s5b0-primary-bsmooth-b01-20260812t110635z-v9,
  signal (send, receive) peer=r8-liquid-s5b0-primary-bsmooth-b01-20260812t110635z-v9,
  network unix dgram,
  network netlink raw,

  # No network stream, home/workspace write, optional bag, C2, unconfined
  # transition, extra GPU device, or second replay authority.
}
