# Exact v3 one-Make profile, only g++-11/CUDA 12.8 and isolated output.
abi <abi/4.0>,
include <tunables/global>
profile r8-liquid-motion-gauge-gpu-build-20260812t034446z-v3 flags=(attach_disconnected,mediate_deleted) {
  userns create,
  /usr/bin/bwrap rix,
  /usr/bin/env rix,
  /usr/bin/prlimit rix,
  /usr/bin/make rix,
  /usr/bin/dash rix,
  /usr/bin/rm rix,
  /usr/bin/x86_64-linux-gnu-g++-11 rix,
  /usr/lib/gcc/x86_64-linux-gnu/11/cc1plus rix,
  /usr/lib/gcc/x86_64-linux-gnu/11/collect2 rix,
  /usr/bin/x86_64-linux-gnu-as rix,
  /usr/bin/x86_64-linux-gnu-ld.bfd rix,
  /usr/bin/as rix,
  /usr/bin/ld rix,
  /usr/local/cuda-12.8/bin/nvcc rix,
  /usr/local/cuda-12.8/bin/cudafe++ rix,
  /usr/local/cuda-12.8/bin/ptxas rix,
  /usr/local/cuda-12.8/bin/fatbinary rix,
  /usr/local/cuda-12.8/bin/nvlink rix,
  /usr/local/cuda-12.8/nvvm/bin/cicc rix,
  /usr/ r,
  /usr/include/** r,
  /usr/lib/** mr,
  /usr/lib64/** mr,
  /lib/** mr,
  /lib64/** mr,
  /etc/ld.so.cache r,
  /usr/local/cuda-12.8/** r,
  /dev/null rw,
  /dev/zero r,
  /dev/urandom r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T034446Z_v1_a.partial/ rw,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T034446Z_v1_a.partial/output/ rw,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T034446Z_v1_a.partial/output/** rw,
  /tmp/newroot/ rw,
  /tmp/newroot/** rw,
  /tmp/oldroot/ rw,
  /tmp/oldroot/** rw,
  /newroot/work/ rw,
  /newroot/work/output/ rw,
  /work/ rw,
  /work/tmp/ rw,
  /work/tmp/** rw,
  /work/output/ rw,
  /work/output/** rw,
  mount options=(rw, silent, rslave) -> /,
  mount fstype=tmpfs options=(rw, nosuid, nodev) -> /tmp/, 
  mount options=(rw, rbind) /tmp/newroot/ -> /tmp/newroot/,
  pivot_root oldroot=/tmp/oldroot/ /tmp/,
  mount options=(rw, silent, rprivate) -> /oldroot/,
  umount /oldroot/,
  pivot_root oldroot=/newroot/ /newroot/,
  umount /,
  mount options=(rw, rbind) /oldroot/usr/ -> /newroot/usr/,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/usr/,
  mount fstype=tmpfs options=(rw, nosuid, nodev) -> /newroot/work/,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T034446Z_v1_a.partial/output/ -> /newroot/work/output/,
  remount options=(rw, nosuid, nodev, bind, silent, relatime) /newroot/work/output/,
  capability sys_admin,
  capability sys_ptrace,
  capability sys_resource,
  capability setpcap,
  capability net_admin,
}
