# R8 liquid U3 fresh GPU build profile; exact campaign instance.
# Delta from 20260810T162710Z-a: identity/root only.  The build-command fix is
# an argv encoding correction and does not expand this profile's permissions.
abi <abi/4.0>,

include <tunables/global>

profile r8-liquid-u3-gpu-build-20260810T165034Z-a flags=(attach_disconnected,mediate_deleted) {
  userns create,

  /usr/bin/bwrap rix,
  /usr/bin/env rix,
  /usr/bin/prlimit rix,
  /usr/bin/make rix,
  /usr/bin/dash rix,
  /usr/bin/rm rix,
  /usr/bin/x86_64-linux-gnu-g++-11 rix,
  /usr/lib/gcc/x86_64-linux-gnu/11/cc1plus rix,
  /usr/lib/gcc/x86_64-linux-gnu/11/collect2 rix,
  /usr/bin/x86_64-linux-gnu-as rix,
  /usr/bin/x86_64-linux-gnu-ld.bfd rix,
  /usr/bin/as rix,
  /usr/bin/ld rix,
  /usr/bin/ld.bfd rix,
  /usr/local/cuda-12.8/bin/nvcc rix,
  /usr/local/cuda-12.8/bin/cudafe++ rix,
  /usr/local/cuda-12.8/bin/ptxas rix,
  /usr/local/cuda-12.8/bin/fatbinary rix,
  /usr/local/cuda-12.8/bin/nvlink rix,
  /usr/local/cuda-12.8/nvvm/bin/cicc rix,

  / r,
  /usr/ r,
  /usr/include/ r,
  /usr/include/** r,
  /usr/lib/** mr,
  /usr/lib64/** mr,
  /usr/local/cuda-12.8/bin/nvcc.profile r,
  /usr/local/cuda-12.8/nvvm/libdevice/** mr,
  /usr/local/cuda-12.8/targets/x86_64-linux/include/** r,
  /usr/local/cuda-12.8/targets/x86_64-linux/lib/** mr,
  /lib/** mr,
  /lib64/** mr,
  /etc/ld.so.cache r,
  /etc/ld.so.conf r,
  /etc/ld.so.conf.d/** r,

  /home/ r,
  /home/zrj/ r,
  /home/zrj/scout_liquid_lab/ r,
  /home/zrj/scout_liquid_lab/build/ r,
  /home/zrj/scout_liquid_lab/build/u3_source_gpu_build_sm120_20260810T165034Z_a.partial/ rw,
  /home/zrj/scout_liquid_lab/build/u3_source_gpu_build_sm120_20260810T165034Z_a.partial/output/ rw,
  /home/zrj/scout_liquid_lab/build/u3_source_gpu_build_sm120_20260810T165034Z_a.partial/output/** rw,

  owner /proc/** r,
  owner /proc/*/uid_map w,
  owner /proc/*/gid_map w,
  owner /proc/*/setgroups w,
  /proc/filesystems r,
  /proc/sys/kernel/overflowuid r,
  /proc/sys/kernel/overflowgid r,
  /proc/sys/user/max_user_namespaces w,
  /dev/null rw,
  /dev/zero r,
  /dev/random r,
  /dev/urandom r,

  mount options=(rw, silent, rslave) -> /,
  mount fstype=tmpfs options=(rw, nosuid, nodev) -> /tmp/,
  mount options=(rw, rbind) /tmp/newroot/ -> /tmp/newroot/,
  pivot_root oldroot=/tmp/oldroot/ /tmp/,
  mount options=(rw, silent, rprivate) -> /oldroot/,
  umount /oldroot/,
  pivot_root oldroot=/newroot/ /newroot/,
  umount /,
  mount options=(rw, rbind) /oldroot/usr/ -> /newroot/usr/,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/usr/,
  mount fstype=tmpfs options=(rw, nosuid, nodev) -> /newroot/work/,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/u3_source_gpu_build_sm120_20260810T165034Z_a.partial/output/ -> /newroot/work/output/,
  remount options=(rw, nosuid, nodev, bind, silent, relatime) /newroot/work/output/,

  /tmp/newroot/ rw,
  /tmp/newroot/** rw,
  /tmp/oldroot/ rw,
  /tmp/oldroot/** rw,
  /newroot/usr/ rw,
  /newroot/lib wl,
  /newroot/lib64 wl,
  /newroot/work/ rw,
  /newroot/work/tmp/ rw,
  /newroot/work/output/ rw,
  /work/ rw,
  /work/tmp/ rw,
  /work/tmp/** rw,
  /work/output/ rw,
  /work/output/** rw,

  capability sys_admin,
  capability sys_ptrace,
  capability sys_resource,
  capability setpcap,
  capability net_admin,
  ptrace (read, readby) peer=r8-liquid-u3-gpu-build-20260810T165034Z-a,
  signal (send, receive) peer=r8-liquid-u3-gpu-build-20260810T165034Z-a,
  network unix dgram,
  network inet dgram,
  network inet6 dgram,
  network netlink raw,

  # No g++-13, GPU devices, stream networking, workspace access, host-wide
  # writes or unconfined transitions.
}
