# Fresh v11 exact six-file patch profile; no workspace glob or compiler/GPU/network surface.
abi <abi/4.0>,
include <tunables/global>

profile r8-liquid-motion-gauge-gpu-patch-20260812t073037z-v11 flags=(attach_disconnected,mediate_deleted) {
  userns create,
  /usr/bin/bwrap rix,
  /usr/bin/env rix,
  /usr/bin/prlimit rix,
  /usr/bin/python3 rix,
  /usr/bin/python3.12 rix,
  /home/zrj/scout_ws/src/scout_apps/simulation/scout_dualsphysics_liquid/scripts/r8_liquid_motion_gauge_gpu_patch_child_v11.py r,
  /home/zrj/scout_ws/src/scout_apps/simulation/scout_dualsphysics_liquid/scripts/r8_liquid_motion_attached_gauge_patch_gate_v1.py r,
  /usr/ r,
  /usr/lib/** mr,
  /usr/lib64/** mr,
  /lib/** mr,
  /lib64/** mr,
  /etc/ld.so.cache r,
  /home/ r,
  /home/zrj/ r,
  /home/zrj/scout_ws/ r,
  /home/zrj/scout_ws/src/ r,
  /home/zrj/scout_ws/src/scout_apps/ r,
  /home/zrj/scout_ws/src/scout_apps/simulation/ r,
  /home/zrj/scout_ws/src/scout_apps/simulation/scout_dualsphysics_liquid/ r,
  /home/zrj/scout_ws/src/scout_apps/simulation/scout_dualsphysics_liquid/scripts/ r,
  /home/zrj/scout_liquid_lab/ r,
  /home/zrj/scout_liquid_lab/build/ r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/ r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/ r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/ r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/ r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/ r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsGaugeItem.cpp rw,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsGaugeItem.h rw,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsGaugeSystem.cpp rw,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JDsGaugeSystem.h rw,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSph.cpp rw,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/JSph.h rw,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/.r8-motion-gauge-v11-JDsGaugeItem.cpp.partial rw,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/.r8-motion-gauge-v11-JDsGaugeItem.h.partial rw,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/.r8-motion-gauge-v11-JDsGaugeSystem.cpp.partial rw,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/.r8-motion-gauge-v11-JDsGaugeSystem.h.partial rw,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/.r8-motion-gauge-v11-JSph.cpp.partial rw,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/.r8-motion-gauge-v11-JSph.h.partial rw,
  owner /proc/** r,
  owner /proc/*/uid_map w,
  owner /proc/*/gid_map w,
  owner /proc/*/setgroups w,
  /proc/filesystems r,
  /proc/sys/kernel/overflowuid r,
  /proc/sys/kernel/overflowgid r,
  /proc/sys/user/max_user_namespaces w,
  /dev/null rw,
  /dev/zero r,
  /dev/random r,
  /dev/urandom r,
  mount options=(rw, silent, rslave) -> /,
  mount fstype=tmpfs options=(rw, nosuid, nodev) -> /tmp/,
  mount options=(rw, rbind) /tmp/newroot/ -> /tmp/newroot/,
  pivot_root oldroot=/tmp/oldroot/ /tmp/,
  mount options=(rw, silent, rprivate) -> /oldroot/,
  umount /oldroot/,
  pivot_root oldroot=/newroot/ /newroot/,
  umount /,
  mount options=(rw, rbind) /oldroot/usr/ -> /newroot/usr/,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/usr/,
  mount fstype=tmpfs options=(rw, nosuid, nodev) -> /newroot/work/,
  mount options=(rw, rbind) /oldroot/home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T073037Z_v11_a.partial/output/buildtree/src/source/ -> /newroot/work/source/,
  remount options=(rw, nosuid, nodev, bind, silent, relatime) /newroot/work/source/,
  mount options=(rw, bind) /oldroot/home/zrj/scout_ws/src/scout_apps/simulation/scout_dualsphysics_liquid/scripts/r8_liquid_motion_gauge_gpu_patch_child_v11.py -> /newroot/work/helper.py,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/work/helper.py,
  mount options=(rw, bind) /oldroot/home/zrj/scout_ws/src/scout_apps/simulation/scout_dualsphysics_liquid/scripts/r8_liquid_motion_attached_gauge_patch_gate_v1.py -> /newroot/work/patch_v1.py,
  remount options=(ro, nosuid, nodev, bind, silent, relatime) /newroot/work/patch_v1.py,
  /tmp/newroot/ rw,
  /tmp/newroot/** rw,
  /tmp/oldroot/ rw,
  /tmp/oldroot/** rw,
  /newroot/usr/ rw,
  /newroot/lib wl,
  /newroot/lib64 wl,
  /newroot/work/ rw,
  /newroot/work/source/ rw,
  /newroot/work/helper.py rw,
  /newroot/work/patch_v1.py rw,
  /work/helper.py r,
  /work/patch_v1.py r,
  /work/source/ r,
  /work/source/JDsGaugeItem.cpp rw,
  /work/source/JDsGaugeItem.h rw,
  /work/source/JDsGaugeSystem.cpp rw,
  /work/source/JDsGaugeSystem.h rw,
  /work/source/JSph.cpp rw,
  /work/source/JSph.h rw,
  /work/source/.r8-motion-gauge-v11-JDsGaugeItem.cpp.partial rw,
  /work/source/.r8-motion-gauge-v11-JDsGaugeItem.h.partial rw,
  /work/source/.r8-motion-gauge-v11-JDsGaugeSystem.cpp.partial rw,
  /work/source/.r8-motion-gauge-v11-JDsGaugeSystem.h.partial rw,
  /work/source/.r8-motion-gauge-v11-JSph.cpp.partial rw,
  /work/source/.r8-motion-gauge-v11-JSph.h.partial rw,
  capability sys_admin,
  capability sys_ptrace,
  capability sys_resource,
  capability setpcap,
  capability net_admin,
  ptrace (read, readby) peer=r8-liquid-motion-gauge-gpu-patch-20260812t073037z-v11,
  signal (send, receive) peer=r8-liquid-motion-gauge-gpu-patch-20260812t073037z-v11,
  network unix dgram,
  network netlink raw,
}
