# Exact create-new instance for the frozen motion-Gauge one-Make phase.
abi <abi/4.0>,
include <tunables/global>

profile r8-liquid-motion-gauge-gpu-build-20260812t034446z-v2 flags=(attach_disconnected,mediate_deleted) {
  /usr/bin/timeout rix,
  /usr/bin/aa-exec rix,
  /usr/bin/bwrap rix,
  /usr/bin/env rix,
  /usr/bin/prlimit rix,
  /usr/bin/make rix,
  /usr/bin/dash rix,
  /usr/bin/rm rix,
  /usr/bin/x86_64-linux-gnu-g++-11 rix,
  /usr/lib/gcc/x86_64-linux-gnu/11/cc1plus rix,
  /usr/lib/gcc/x86_64-linux-gnu/11/collect2 rix,
  /usr/bin/x86_64-linux-gnu-as rix,
  /usr/bin/x86_64-linux-gnu-ld.bfd rix,
  /usr/local/cuda-12.8/bin/nvcc rix,
  /usr/local/cuda-12.8/bin/cudafe++ rix,
  /usr/local/cuda-12.8/bin/ptxas rix,
  /usr/local/cuda-12.8/bin/fatbinary rix,
  /usr/local/cuda-12.8/bin/nvlink rix,
  /usr/local/cuda-12.8/nvvm/bin/cicc rix,
  /usr/ r,
  /usr/include/** r,
  /usr/lib/** mr,
  /usr/lib64/** mr,
  /lib/** mr,
  /lib64/** mr,
  /etc/ld.so.cache r,
  /usr/local/cuda-12.8/** r,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T034446Z_v1_a.partial/ rw,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T034446Z_v1_a.partial/output/ rw,
  /home/zrj/scout_liquid_lab/build/motion_gauge_gpu_build_sm120_20260812T034446Z_v1_a.partial/output/** rw,
  /work/output/ rw,
  /work/output/** rw,
  /work/tmp/ rw,
  /work/tmp/** rw,
}
