#!/usr/bin/env python3
"""Generate a build-only canonical D2b request for the D4 C++ wrapper test."""

from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path

PACKAGE_ROOT = Path(__file__).resolve().parents[2]
SCRIPTS_ROOT = PACKAGE_ROOT / "scripts"
if str(SCRIPTS_ROOT) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_ROOT))

from acados.mainline.cost_schedule import (  # noqa: E402
    ExperimentCondition,
    build_liquid_cost_schedule,
)
from acados.mainline.development_capacity import load_development_capacity  # noqa: E402
from acados.mainline.development_layout import build_development_layout  # noqa: E402
from acados.mainline.parameter_values import (  # noqa: E402
    ActuatorResponseParameters,
    CommonStageParameterValues,
    NormalizationParameters,
    ReferenceHorizonParameters,
    ReferencePolynomialParameters,
    RunningWeightParameters,
    SloshParameters,
    TerminalWeightParameters,
)
from acados.mainline.runtime_parameter_assembler import (  # noqa: E402
    assemble_runtime_stage_parameters,
)
from acados.mainline.runtime_schedule import (  # noqa: E402
    build_runtime_fractional_delay_schedule,
)

CAPACITY_PATH = (
    PACKAGE_ROOT
    / "config"
    / "mainline"
    / "contracts"
    / "development_capacity_v1.json"
)


def _number(value: float) -> str:
    if not math.isfinite(value):
        raise ValueError("fixture values must be finite")
    rendered = format(value, ".17g")
    return rendered if any(character in rendered for character in ".eE") else rendered + ".0"


def _render() -> str:
    capacity = load_development_capacity(CAPACITY_PATH)
    layout = build_development_layout(capacity)
    runtime = build_runtime_fractional_delay_schedule(
        capacity, 0.05, 0.07, 1.0e-12, 1.0e-12
    )
    values = CommonStageParameterValues(
        actuator=ActuatorResponseParameters(0.12, 1.03, 0.45, 0.98),
        reference=ReferenceHorizonParameters(
            polynomial=ReferencePolynomialParameters(
                ref_s_origin=2.0,
                ref_s_scale=0.8,
                ref_x_coeff=(0.1, 0.8, 0.05, -0.02),
                ref_y_coeff=(-0.2, 0.1, 0.03, 0.01),
                minimum_tangent_norm_per_s=0.5,
            ),
            ref_speed=tuple(0.2 - 0.1 * stage / 60.0 for stage in range(61)),
        ),
        slosh=SloshParameters(5.0, 0.05, 1.1, 0.9, 0.01, 0.3),
        normalization=NormalizationParameters(
            0.1, 0.2, 0.5, 1.0, 0.5, 0.8, 1.2, 2.0, 3.0
        ),
        running_weight=RunningWeightParameters(
            1.0, 0.2, 0.3, 0.7, 0.4, 0.1, 0.15, 0.05, 0.08
        ),
        terminal_weight=TerminalWeightParameters(2.0, 0.4, 1.5, 0.6),
    )
    snapshots = {
        condition.value: assemble_runtime_stage_parameters(
            capacity,
            layout,
            runtime,
            values,
            build_liquid_cost_schedule(condition, 8, 4.0, 7.0),
        )
        for condition in (ExperimentCondition.B0, ExperimentCondition.Bslosh)
    }
    initial_state = [0.0] * layout.NX
    initial_values = {
        "px": 0.1,
        "py": -0.2,
        "theta": math.atan2(0.1, 0.8),
        "s": 2.0,
        "v_actual": 0.1,
        "q_prev_v": 0.1,
    }
    for name, value in initial_values.items():
        initial_state[layout.state_offsets[name]] = value
    for name in layout.state_names:
        if name.startswith("older_v"):
            initial_state[layout.state_offsets[name]] = 0.1

    lines = [
        "// Build-only fixture generated by generate_mainline_solver_fixture.py.",
        "#pragma once",
        "namespace spmpc_local_planner { namespace mainline { namespace fixture {",
        "constexpr double kInitialState[48] = {",
        "  " + ", ".join(_number(value) for value in initial_state),
        "};",
    ]
    for condition, snapshot in snapshots.items():
        lines.append(f"constexpr double k{condition}StageParameters[61][162] = {{")
        lines.extend(
            "  {" + ", ".join(_number(value) for value in row) + "},"
            for row in snapshot.stage_parameters
        )
        lines.append("};")
    lines.extend(
        (
            "}}}  // namespace spmpc_local_planner::mainline::fixture",
            "",
        )
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    arguments = parser.parse_args()
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(_render(), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
